nagios plugin to alert on cluster state

diff --git a/plugins/nagios/s9s_cluster_status b/plugins/nagios/s9s_cluster_status
--- a/plugins/nagios/s9s_cluster_status
+++ b/plugins/nagios/s9s_cluster_status
@@ -1,57 +1,75 @@
 #!/bin/bash
-progname="check_clusterstatus"
-version=.01
-author="Severalnines"
 
-print_version() {
-echo "Version $version Author $author"
-echo
-}
+VERSION=0.1
+TEMP=`getopt -o h,H:,p:,P: --long help,host:,password:,port: -n 's9s_cluster_status' -- "$@"`
+eval set -- "$TEMP"
 
-print_help() {
-print_version $progname
-echo ""
-echo "$progname -> checks database cluster status"
-echo ""
-exit $unkown
-}
-while test -n "$1"; do
-case "$1" in
--help|-h)
-print_help
-exit $unknown
-;;
--version|-v)
-print_version $PROGNAME $VERSION
-exit $unknown
-;;
-*)
-echo "Unknown argument: $1"
-print_help
-exit $unknown
-;;
-esac
-shift
+while true ; do
+  case "$1" in
+    -h|--help) help="1" ; shift ;;
+    -H|--host) cmon_db_host="$2" ; shift 2 ;;
+    -p|--password) cmon_db_password="$2" ; shift 2 ;;
+    -P|--port) cmon_db_port="$2" ; shift 2 ;;
+    --) shift ; break ;;
+    *) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
+  esac
 done
-### CODE HERE TO GET STATE, 
-cmon_password='cmon'
-cmon_db_server='<cmon mysql host IP address>'
-cmon_db_port='3306'
 
+# Help menu
+if [ ! -z "$help" ]; then
+	echo "Plugin  : Check Database Cluster Status (Nagios)"
+	echo "Version : $VERSION"
+	echo "Author  : Severalnines"
+	echo ""
+	echo "Usage   : `basename $0` -H [host] -p [cmon_password] [options]"
+	echo ""
+	echo "-H, --host      : ClusterControl/cmon IP address"
+	echo "-p, --password  : DB password for user cmon"
+	echo "-P, --port      : MySQL port for the host (default 3306)"
+	echo "-h, --help      : Print help"
+	echo ""
+	echo "Example: `basename $0` -H 127.0.0.1 -p 'password'"
+	echo ""
+	exit 1
+fi
+
+[ -z $cmon_db_port ] && cmon_db_port=3306
+
+if [ -z "$cmon_db_host" ] || [ -z "$cmon_db_password" ]; then
+	echo "Please specify cmon host and user DB password. Use --help for more info."
+	exit 1
+fi
+
+# SQL query
+query='SELECT status FROM cmon.cluster_state WHERE id=1'
+
+# MySQL client
 mysqlbin=`which mysql`
-status=`$mysqlbin -h$cmon_db_server -u cmon -p$cmon_password -A -Bse 'select status from cmon.cluster_state where id=1'`
-#convert to upper case
-clustate=${status^^}
+if [ ! -z "$mysqlbin" ]; then
+        execute_query=`$mysqlbin -h$cmon_db_host -ucmon -p$cmon_db_password -P$cmon_db_port -A -Bse "$query"`
+	if [ ! $execute_query ]; then
+	        echo "Failed to query cmon database. The following query failed : $query"
+		echo "Unknown: Cluster status is UNKNOWN"
+	        stateid=3
+		exit $stateid
+	else
+		clustate=${execute_query^^}
+	fi
+else
+        echo "MySQL client not found. Kindly add the MySQL client into PATH or install MySQL client package"
+        exit 1
+fi
 
 if (( "$clustate" == "STARTED" )); then
-	echo "OK: Cluster status is OK"
-	stateid=0
+        echo "OK: Cluster status is OK"
+        stateid=0
 elif  (( "$clustate" == "CRITICAL" || "$clustate" == "UNKNOWN" || "$clustate" == "FAILURE" || "$clustate" == "STOPPED" || "$clustate" == "SHUTTING_DOWN" )); then
-	echo "Critical: Cluster status is $clustate"
-	stateid=2
+        echo "Critical: Cluster status is $clustate"
+        stateid=2
 else
-	echo "Warning: Unknown state"
-	stateid=1
+        echo "Warning: Cluster status is $clustate"
+        stateid=1
 fi
 
 exit $stateid
+
