updates

diff --git a/cluster/s9s_backupc b/cluster/s9s_backupc
--- a/cluster/s9s_backupc
+++ b/cluster/s9s_backupc
@@ -68,14 +68,15 @@ function init
 #INNOBACKUP_OPTS=" --lock-wait-threshold=40 --lock-wait-query-type=all --lock-wait-timeout=180 --kill-long-queries-timeout=20 --kill-long-query-type=all"
 function write_email
 {
-  SUBJECT=$1
-  MSG=$2
-  cat $BACKUP_LOGFILE | sed  -e "s/'/\\\'/g" -e 's/"/\\"/g' > /tmp/s9s_backup_log_escaped_${CLUSTER_ID}
-  df -h > /tmp/s9s_diskspace_${CLUSTER_ID}
-  MSG="$MSG \nBackup log follows:\n `cat /tmp/s9s_backup_log_escaped_${CLUSTER_ID}`\n\n`cat /tmp/s9s_diskspace_${CLUSTER_ID}`" 
-  QUERY="INSERT INTO simple_email(cid,subject,message) VALUES($CLUSTER_ID, \"$SUBJECT\", \"$MSG\")"
-  echo "$QUERY" > /tmp/query.sql
-  $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  < /tmp/query.sql 2>&1 >/tmp/err.log
+    true
+    #SUBJECT=$1
+    #MSG=$2
+    #cat $BACKUP_LOGFILE | sed  -e "s/'/\\\'/g" -e 's/"/\\"/g' > /tmp/s9s_backup_log_escaped_${CLUSTER_ID}
+    #df -h > /tmp/s9s_diskspace_${CLUSTER_ID}
+    #MSG="$MSG \nBackup log follows:\n `cat /tmp/s9s_backup_log_escaped_${CLUSTER_ID}`\n\n`cat /tmp/s9s_diskspace_${CLUSTER_ID}`" 
+    #QUERY="INSERT INTO simple_email(cid,subject,message) VALUES($CLUSTER_ID, \"$SUBJECT\", \"$MSG\")"
+    #echo "$QUERY" > /tmp/query.sql
+    #$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  < /tmp/query.sql 2>&1 >/tmp/err.log
 }
 
 function log_job_message
@@ -180,27 +181,27 @@ function start_backup
       exit 1
     fi
     if [ -z "$DISABLE_COMPRESSION" ]; then
-	COMPRESSION=1
+	    COMPRESSION=1
     fi
-
+    
     if [ -z "$USE_PIGZ" ]; then
-	USE_PIGZ="0"
-	COMPRESSION_TOOL="gzip"
+	    USE_PIGZ="0"
+	    COMPRESSION_TOOL="gzip"
     else
-	COMPRESSION_TOOL="pigz"
+	    COMPRESSION_TOOL="pigz"
     fi
     
     if [ -z "$BACKUP_HOSTNAME" ]; then
-      echo "s9s_backupc  --backup -h <backup hostname> missing"
-      exit 1
+        echo "s9s_backupc  --backup -h <backup hostname> missing"
+        exit 1
     fi
-
+    
     if [ -z "$TYPE" ]; then
-      echo "s9s_backupc  --backup -t <full|incr> missing"
-      exit 1
+        echo "s9s_backupc  --backup -t <full|incr> missing"
+        exit 1
     fi
     if [ "$jobid" = "" ]; then 
-	jobid=0
+	    jobid=0
     fi
     init 
     I=0
@@ -208,53 +209,53 @@ function start_backup
     load_opts $CLUSTER_ID
     MYCNF=${CONFIGDIR}/my.cnf
     if ! test -f $MYSQL_BIN; then
-	if ! test -f $MYSQL_BIN2; then
-	    log_job_message "Could not find mysql client" 1
-	    echo "Could not find mysql client binary"
-	    echo "Change MYSQL_BIN in beginning of the scipt"
-	    exit 1
-	fi
-	MYSQL_BIN=$MYSQL_BIN2
+	    if ! test -f $MYSQL_BIN2; then
+	        log_job_message "Could not find mysql client" 1
+	        echo "Could not find mysql client binary"
+	        echo "Change MYSQL_BIN in beginning of the scipt"
+	        exit 1
+	    fi
+	    MYSQL_BIN=$MYSQL_BIN2
     fi
     if ! test -f $MYSQL_BIN; then
-	echo "Could not find mysql client binary"
-	log_job_message "Could not find mysql client binary" 1
-	log_job 'FAILED' 'backup failed' 1
-	exit 1
+	    echo "Could not find mysql client binary"
+	    log_job_message "Could not find mysql client binary" 1
+	    log_job 'FAILED' 'backup failed' 1
+	    exit 1
     fi
-
+    
     write_defaults_file cmon $CMON_PASSWORD
     
     if [ -z "$BACKUPDIR" ]; then
-	BACKUPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='BACKUPDIR' AND cid=$CLUSTER_ID"`
+	    BACKUPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='BACKUPDIR' AND cid=$CLUSTER_ID"`
     fi
-
+    
     if [ -z "$BACKUPDIR" ]; then
       echo "s9s_backupc  --install -b <backupdir> missing"
       exit 1
     fi
     if [ -e $LOCKFILE ]; then
-       PID=`cat $LOCKFILE`
-       PID=`ps -ef |grep $PID |grep s9s_backup |grep -v $$`
-       if [ $? -eq 0 ]; then
-          log_job_message "An instance of s9s_backup is already running." 1; echo "An instance of s9s_backup is already running.";  
-          exit 1
-       fi
-       rm $LOCKFILE
+        PID=`cat $LOCKFILE`
+        PID=`ps -ef |grep $PID |grep s9s_backup |grep -v $$`
+        if [ $? -eq 0 ]; then
+            log_job_message "An instance of s9s_backup is already running." 1; echo "An instance of s9s_backup is already running.";  
+            exit 1
+        fi
+        rm $LOCKFILE
     fi
     if [ ! -e $LOCKFILE ]; then
-	trap "rm -f $LOCKFILE; killall -9 s9s_backupc_wd nc; rm -rf /tmp/xtrabackup_pid; ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME rm /tmp/s9s_pass; exit" INT TERM EXIT
-	echo $$ $LOCKFILE	
-	if which pv &> /dev/null; then
+	    trap "rm -f $LOCKFILE; killall -9 s9s_backupc_wd nc; rm -rf /tmp/xtrabackup_pid; ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME rm /tmp/s9s_pass; exit" INT TERM EXIT
+	    echo $$ $LOCKFILE	
+	    if which pv &> /dev/null; then
             #THROTTLE="--throttle=30"
-	    HAS_PV=1
-	else
+	        HAS_PV=1
+	    else
  # echo "pv not found"
  #echo "Warning: Throttling (--throttle=) will not be possible"
  #echo "Install with: "
  #echo "  apt: apt-get install pv "
  #echo "  yum: yum install pv "
-	    THROTTLE=""
+	        THROTTLE=""
 	fi
   # There is something wrong with throttle.. innobackup never seems to terminate
 	THROTTLE=""
@@ -460,11 +461,11 @@ function start_backup
 	if [ "$TYPE" = "full" ]; then   
 	    log_job 'RUNNING' 'Job is running' 0
 	    if [ $COMPRESSION -eq 1 ]; then
- 		ssh $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && LC_ALL=C $XTRABACKUP_BIN $GALERA_INFO   --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1  --port=$MONITORED_MYSQL_PORT $INNOBACKUP_OPTS $THROTTLE  --stream=tar ./  2>$BACKUP_LOGFILE | $COMPRESSION_TOOL  - | nc $STORAGE_HNAME $NETCAT_PORT  '" 	   		
-		ret=$?
+ 		    ssh $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && LC_ALL=C $XTRABACKUP_BIN $GALERA_INFO   --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1  --port=$MONITORED_MYSQL_PORT $INNOBACKUP_OPTS $THROTTLE  --stream=tar ./  2>$BACKUP_LOGFILE | $COMPRESSION_TOOL  - | nc $STORAGE_HNAME $NETCAT_PORT  '" 	   		
+		    ret=$?
 	    else
-		ssh $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO   --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1 --port=$MONITORED_MYSQL_PORT  $INNOBACKUP_OPTS $THROTTLE  --stream=tar ./  2>$BACKUP_LOGFILE | nc $STORAGE_HNAME $NETCAT_PORT  '" 
-		ret=$?
+		    ssh $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO   --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1 --port=$MONITORED_MYSQL_PORT  $INNOBACKUP_OPTS $THROTTLE  --stream=tar ./  2>$BACKUP_LOGFILE | nc $STORAGE_HNAME $NETCAT_PORT  '" 
+		    ret=$?
 	    fi
 	    scp -q $SCP_OPTS $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE $BACKUP_LOGFILE
 	    LSN=`cat $BACKUP_LOGFILE | grep 'xtrabackup: The latest check point (for incremental):' | awk -F ':' '{print $3;}'`
@@ -475,11 +476,11 @@ function start_backup
 	else
 	    log_job 'RUNNING' 'Job is running' 0
 	    if [ $COMPRESSION -eq 1 ]; then
- 		ssh  $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO  --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1  --port=$MONITORED_MYSQL_PORT  --incremental --incremental-lsn=$LSN $INNOBACKUP_OPTS $THROTTLE  --stream=xbstream ./  2>$BACKUP_LOGFILE | $COMPRESSION_TOOL  - | nc $STORAGE_HNAME $NETCAT_PORT  '" 
-		ret=$?
+ 		    ssh  $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO  --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1  --port=$MONITORED_MYSQL_PORT  --incremental --incremental-lsn=$LSN $INNOBACKUP_OPTS $THROTTLE  --stream=xbstream ./  2>$BACKUP_LOGFILE | $COMPRESSION_TOOL  - | nc $STORAGE_HNAME $NETCAT_PORT  '" 
+		    ret=$?
 	    else
- 		ssh  $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO  --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1  --port=$MONITORED_MYSQL_PORT  --incremental --incremental-lsn=$LSN $INNOBACKUP_OPTS $THROTTLE  --stream=xbstream ./  2>$BACKUP_LOGFILE | nc $STORAGE_HNAME $NETCAT_PORT  '" 
-		ret=$?
+ 		    ssh  $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO  --defaults-extra-file=/tmp/s9s_pass --host=127.0.0.1  --port=$MONITORED_MYSQL_PORT  --incremental --incremental-lsn=$LSN $INNOBACKUP_OPTS $THROTTLE  --stream=xbstream ./  2>$BACKUP_LOGFILE | nc $STORAGE_HNAME $NETCAT_PORT  '" 
+		    ret=$?
 	    fi
 	    
 	    scp -q $SCP_OPTS $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE $BACKUP_LOGFILE
@@ -566,11 +567,11 @@ function start_backup
 	fi
 	rm $LOCKFILE
 	trap - INT TERM EXIT
-	exit 0
+	exit $ret
     else
- 	write_email "Backup failed" "s9s_backupc failed - Lock file $LOCKFILE exists which indicates another backup may be running?" 
-	log_job_message "Lock file $LOCKFILE exists which indicates another backup may be running?" 1
-	log_job 'FAILED' 'Backup failed' 1
+ 	    write_email "Backup failed" "s9s_backupc failed - Lock file $LOCKFILE exists which indicates another backup may be running?" 
+	    log_job_message "Lock file $LOCKFILE exists which indicates another backup may be running?" 1
+	    log_job 'FAILED' 'Backup failed' 1
     fi	
 }
 
diff --git a/cluster/s9s_haproxy b/cluster/s9s_haproxy
--- a/cluster/s9s_haproxy
+++ b/cluster/s9s_haproxy
@@ -8,6 +8,7 @@
 # for the work on the makecfg, mysqlckk, and haproxy.cfg.tmpl
 JOBID=0
 HAPROXY_MYSQL_LISTEN_PORT="33306"
+LB_POLICY=leastconn
 HAPROXY_LOG='/tmp/s9s_haproxy.log'
 HAPROXY_LOG2='/tmp/s9s_haproxy2.log'
 LOCKFILE="/tmp/s9s_haproxy.lock"
@@ -253,6 +254,12 @@ SUFFIX="$2"
 TMPDIR2="$3"
 MAX_CONNECTIONS="$4"
 LISTEN_PORT="$5"
+LB_POLICY="$6"
+
+if [ -z "$LB_POLICY" ]; then
+    LB_POLICY=leastconn
+fi
+
 TEMPLATE=${TMPDIR2}/haproxy.cfg.tmpl
 if ([ -z "$DC" ] || [ -z "$SUFFIX" ]); then
         echo "specify PREFIX and SUFFIX: $0 <prefix> <suffix>; ie: $0 dt 1"
@@ -285,7 +292,7 @@ listen  "$DESC"
         mode tcp
         timeout client  60000ms
         timeout server  60000ms
-        balance leastconn 
+        balance ${LB_POLICY}
         option httpchk
         option allbackups
         default-server port 9200 inter 2s downinter 5s rise 3 fall 2 slowstart 60s maxconn $MAX_CONNECTIONS maxqueue 128 weight 100
@@ -793,7 +800,7 @@ function install_haproxy
 {
     LB_NODE_LIST=""
     MAX_CONNECTIONS=256
-    args=`getopt p:P:h:i:N:n:j:sf:c: $*`
+    args=`getopt p:P:h:i:N:n:j:sf:c:x: $*`
     set -- $args
     for i
     do
@@ -802,7 +809,7 @@ function install_haproxy
                 CMON_PASSWORD="$2"; shift;
                 shift;;
             -P)
-		HAPROXY_MYSQL_LISTEN_PORT="$2"; shift;
+		        HAPROXY_MYSQL_LISTEN_PORT="$2"; shift;
                 shift;;
             -i)
                 CLUSTER_ID="$2"; shift;
@@ -824,6 +831,9 @@ function install_haproxy
                 shift;;
             -N)
                 LB_NAME="$2"; shift;
+                shift;;
+            -x)
+                LB_POLICY="$2"; shift;
                 shift;;
             -j)
                 JOBID="$2"; shift;
@@ -870,6 +880,31 @@ function install_haproxy
     prepare
     chown -R $SSH_USER:$SSH_USER $TMPDIR
     sleep 1
+    case $CLUSTER_TYPE in
+        galera)
+        ;;
+        mysqlcluster)
+        ;;
+        *)
+            log_job_message "Cluster $CLUSTER_TYPE not supported" 1
+	        log_job 'FAILED' 's9s_haproxy failed' 1
+	        exit 1
+            ;;
+    esac
+    case $LB_POLICY in
+        'leastconn')
+            ;;
+        'roundrobin')
+            ;;
+        'source')
+            ;;
+        *)
+            log_job_message "LB_POLICY '$LB_POLICY' not one of leastconn, roundrobin, source" 1
+	        log_job 'FAILED' 's9s_haproxy failed' 1
+	        exit 1
+            ;;
+    esac
+    log_job_message "Using loadbalancing policy '$LB_POLICY'." 0
     log_job 'RUNNING' 'Job is running' 0
     case $OS in
         rhel|redhat)
@@ -910,17 +945,7 @@ function install_haproxy
             ;;
     esac
     log_job 'RUNNING' 'Job is running' 0
-    case $CLUSTER_TYPE in
-        galera)
-        ;;
-        mysqlcluster)
-        ;;
-        *)
-        log_job_message "Cluster $CLUSTER_TYPE not supported" 1
-	log_job 'FAILED' 's9s_haproxy failed' 1
-	exit 1
-        ;;
-    esac
+
     log_job 'RUNNING' 'Job is running' 0
     if [ -n "$LB_NODE_LIST" ]; then
 	LB_NODE_LIST2=`echo $LB_NODE_LIST | sed "s/,/','/g" | sed "s/^/'/g" | sed "s/$/'/g" |sed "s/[ ]*//g"`
@@ -974,7 +999,7 @@ function install_haproxy
     echo "*************************************************************"
     echo "* writing $TMPDIR/${PREFIX}_${LB_NAME}_haproxy.cfg               *"
     echo "*************************************************************"
-    $TMPDIR/makecfg.sh $PREFIX $SUFFIX $TMPDIR $MAX_CONNECTIONS $HAPROXY_MYSQL_LISTEN_PORT > $TMPDIR/${PREFIX}_${LB_NAME}_haproxy.cfg
+    $TMPDIR/makecfg.sh $PREFIX $SUFFIX $TMPDIR $MAX_CONNECTIONS $HAPROXY_MYSQL_LISTEN_PORT $LB_POLICY > $TMPDIR/${PREFIX}_${LB_NAME}_haproxy.cfg
     echo ""
     echo "*************************************************************"
     echo "* Installing haproxy on $LB_HOSTNAME                            *"
@@ -1007,7 +1032,7 @@ function install_haproxy
 	remote_cmd $LB_HOSTNAME "$PKG_MGR $BUILD"
 	remote_cmd $LB_HOSTNAME "tar xvfz /tmp/${HAPROXY_SRC} -C /tmp/"
 	remote_cmd_nofail $LB_HOSTNAME "killall -q  -9 haproxy"	
-	remote_cmd $LB_HOSTNAME "sh -c 'cd /tmp/`basename ${HAPROXY_SRC} .tar.gz` && make TARGET=linux26 && cp haproxy /usr/sbin/'"
+	remote_cmd $LB_HOSTNAME "sh -c 'cd /tmp/`basename ${HAPROXY_SRC} .tar.gz` && make TARGET=linux26 && cp -f haproxy /usr/sbin/'"
     else
 	remote_cmd $LB_HOSTNAME "$PKG_MGR2 haproxy"
     fi
diff --git a/cluster/s9s_mongodb_admin b/cluster/s9s_mongodb_admin
--- a/cluster/s9s_mongodb_admin
+++ b/cluster/s9s_mongodb_admin
@@ -113,7 +113,6 @@ function remote_copy()
    destfile=$3
    printf "%-4s: Copying '%s' " "$desthost" "$srcfile"
    scp $SSH_OPTS2 $srcfile $SSH_USER@$desthost:$destfile >> $HOME/s9s_deploy.log  2>/dev/null
-   echo "scp $SSH_OPTS2 $srcfile $SSH_USER@$desthost:$destfile >> $HOME/s9s_deploy.log  2>/dev/null"
    if [ $? -eq 0 ]; then
       log_job_message "copying file $srcfile --> $desthost:$destfile" 0
       printf "\033[32m[ok]\033[0m\n"
@@ -121,20 +120,26 @@ function remote_copy()
    else
        echo "FAILED: scp $SSH_OPTS2 $srcfile $SSH_USER@$desthost:$destfile >> $HOME/s9s_deploy.log  2>/dev/null"
        echo ""
-      log_job_message "copying file $srcfile --> $desthost:$destfile" 1
-      log_job 'FAILED' 's9s_haproxy failed' 1
+       log_job_message "Failed: scp $SSH_OPTS2 $srcfile $SSH_USER@$desthost:$destfile" 1
+       log_job 'FAILED' 'remove_copy failed' 1
       printf "\033[31m[failed]\033[0m\n"
       exit 1
    fi
 }
+
 
 function remote_cmd_nofail()
 {
    desthost=$1
    xcommand=$2
    printf "%-4s: Executing '%s'" "$desthost" "$xcommand"
-   ssh $SSH_OPTS $SSH_USER@$desthost "$SUDO $xcommand "  >> $HOME/s9s_deploy.log 2>&1
+   ssh -q $SSH_OPTS $SSH_USER@$desthost "$SUDO $xcommand "  >> $HOME/s9s_deploy.log 2>&1
    ret=$?
+   if [ $ret -ne 0 ]; then
+       log_job_message "Failed (but moving on) $desthost : $xcommand" 0
+   else
+       log_job_message "Executed $desthost : $xcommand" 0
+   fi
    printf "\033[32m[ok]\033[0m\n"
    return $ret
 }
@@ -241,21 +246,21 @@ function load_opts
     MONGODB_DATADIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select dbpath from  mongodb_server where node_type=0 AND dbpath<>'' and cid=$CLUSTER_ID limit 1"`
     MONGODB_PIDFILEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select pidfilepath from  mongodb_server where node_type=0 and pidfilepath<>'' and cid=$CLUSTER_ID limit 1"`
     MONGODB_PIDFILEPATH=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select pidfilepath from  mongodb_server where node_type=0 and pidfilepath<>'' and cid=$CLUSTER_ID limit 1"`
-    if [ -z ${MONGODB_PIDFILEPATH} ]; then
-	log_job_message "Failed to MONGODB_PIDFILEPATH " 1
-	exit 1
-    fi
-    if [ -z ${MONGODB_PIDFILEDIR} ]; then
-	log_job_message "Failed to MONGODB_PIDFILEDIR " 1
-	exit 1
-    fi
-    MONGODB_PIDFILEDIR=`dirname $MONGODB_PIDFILEDIR`
-    MONGODB_LOGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select logpath from  mongodb_server where node_type=0 and logpath<>'' and cid=$CLUSTER_ID limit 1"`
-    if [ -z ${MONGODB_LOGDIR} ]; then
-	log_job_message "Failed to MONGODB_LOGDIR " 1
-	exit 1
-    fi
-    MONGODB_LOGDIR=`dirname $MONGODB_LOGDIR`
+#    if [ -z ${MONGODB_PIDFILEPATH} ]; then
+#	log_job_message "Failed to MONGODB_PIDFILEPATH " 1
+#	exit 1
+#    fi
+#    if [ -z ${MONGODB_PIDFILEDIR} ]; then
+#	log_job_message "Failed to MONGODB_PIDFILEDIR " 1
+#	exit 1
+#    fi
+#    MONGODB_PIDFILEDIR=`dirname $MONGODB_PIDFILEDIR`
+ #   MONGODB_LOGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select logpath from  mongodb_server where node_type=0 and logpath<>'' and cid=$CLUSTER_ID limit 1"`
+ #   if [ -z ${MONGODB_LOGDIR} ]; then
+#	log_job_message "Failed to MONGODB_LOGDIR " 1
+#	exit 1
+#   fi
+#    MONGODB_LOGDIR=`dirname $MONGODB_LOGDIR`
     MONGODB_BASEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MONGODB_BASEDIR' AND cid=$CLUSTER_ID"`
     MONGODB_CONFIGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MONGODB_CONFIGDIR' AND cid=$CLUSTER_ID"`
 #    MONGODB_CNF=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select data  from cmon.cluster_configuration_templates where cid=${CLUSTER_ID} limit 1"`
@@ -275,9 +280,9 @@ function load_opts
        MONGODB_CONFIGDIR="/etc/"
     fi
 
-    if [ -z "$MONGODB_PIDFILEDIR" ]; then
-	MONGODB_PIDFILEDIR="/var/run/mongodb/"
-    fi
+#    if [ -z "$MONGODB_PIDFILEDIR" ]; then
+#	MONGODB_PIDFILEDIR="/var/run/mongodb/"
+#    fi
     
     mkdir -p $S9S_TMPDIR
     echo $MONGODB_CNF |  sed 's#\\n#\n\r#g' > $S9S_TMPDIR/mongodb.conf
@@ -781,12 +786,10 @@ function install_mongodb
 
     local xhost=$SERVER1
 
-    remote_cmd_nofail $xhost "killall -9 cmon mongod"
-    remote_cmd_nofail $xhost "rm -rf /etc/mongodb.conf"
-    remote_cmd_nofail $xhost "rm -rf /var/lib/mongodb"
-    remote_cmd_nofail $xhost "rm -rf /var/log/mongodb"
-    remote_cmd_nofail $xhost "rm -rf /etc/init.d/mongod"
-    remote_cmd_nofail $xhost "rm -rf ${MONGODB_DATADIR}"
+    remote_cmd_nofail $xhost "killall -9 mongod"
+    remote_cmd_nofail $R "mkdir -p $S9S_TMPDIR"
+    remote_cmd_nofail $R "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
+
     case $VENDOR in
 	tokutek)
 	    if [ -z "$TGZ_FILE" ]; then
@@ -853,21 +856,29 @@ enabled=1
 EOF
 		    remote_copy $S9S_TMPDIR/10gen.repo $xhost $S9S_TMPDIR/ 
 		    remote_cmd $xhost "mv $S9S_TMPDIR/10gen.repo /etc/yum.repos.d/"
-		    remote_cmd_nofail $xhost "$HTTP_PROXY yum -y remove mongodb*"
+#		    remote_cmd_nofail $xhost "$HTTP_PROXY yum -y remove mongodb*"
 		    remote_cmd_nofail $xhost "$HTTP_PROXY yum -y install mongodb-org"
 		    remote_cmd $xhost  "chown 755 /etc/init.d/mongod"
 		    remote_cmd $xhost  "/sbin/chkconfig --add mongod"
 		    ;;
 		debian)
 		    remote_cmd $xhost "apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10"
-		    remote_cmd_nofail $xhost "touch /etc/init.d/mongodb"
-		    remote_cmd_nofail $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -y remove mongo*"
-		    remote_cmd_nofail $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -y remove mongodb-10gen"
-		    remote_cmd_nofail $xhost "rm -rf /etc/init.d/mongo*"
+#		    remote_cmd_nofail $xhost "touch /etc/init.d/mongodb"
+#		    remote_cmd_nofail $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -y remove mongodb*"
+
+#		    remote_cmd_nofail $xhost "rm -rf /etc/init.d/mongo*"
 		    remote_cmd_nofail $xhost "sed -i.bak '/10gen/d'  /etc/apt/sources.list"
-		    remote_cmd $xhost "/bin/sh -c 'echo \"deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen\" >> /etc/apt/sources.list'"
+
+		    osdist=$(remote_cmd_getreply $xhost "lsb_release -i -s")
+            osdist=`echo $osdist |tr -d '\r'`
+		    echo "$osdist"
+		    if [ "$osdist" = "ubuntu" ] || [ "$osdist" = "Ubuntu" ]; then
+			    remote_cmd $xhost "/bin/sh -c 'echo \"deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen\" >> /etc/apt/sources.list'"
+		    else
+			    remote_cmd $xhost "/bin/sh -c 'echo \"deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist dist 10gen\" >> /etc/apt/sources.list'"
+		    fi
 		    remote_cmd $xhost "$HTTP_PROXY apt-get -q -y update"
-		    remote_cmd $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install mongodb-10gen"
+		    remote_cmd $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install mongodb-org"
 		    ;;
 		*)
 		    echo "OS is unknonwn / not supported" 		  
@@ -881,17 +892,10 @@ EOF
 	    ;;
     esac
     
-    remote_cmd_nofail ${xhost} "killall -9 mongod mongos cmon"
-    echo "Creating mongodb datadirs in ${mongodb_datadir} if not already exists ..."
-    remote_cmd ${xhost} "mkdir -p ${MONGODB_DATADIR}"
-    remote_cmd ${xhost} "mkdir -p ${MONGODB_DATADIR}/config"
-    remote_cmd ${xhost} "mkdir -p ${MONGODB_LOGDIR}"
-    remote_cmd ${xhost} "mkdir -p ${MONGODB_PIDFILEDIR}"
+    remote_cmd_nofail ${xhost} "killall -9 mongod mongos"
     remote_cmd_nofail $xhost "/usr/sbin/groupadd mongodb"
     remote_cmd_nofail $xhost "/usr/sbin/useradd mongodb -g mongodb"
-    remote_cmd $xhost "chown mongodb:mongodb -R $MONGODB_DATADIR"
-    remote_cmd $xhost "chown mongodb:mongodb -R $MONGODB_LOGDIR"
-    remote_cmd $xhost "chown mongodb:mongodb -R ${MONGODB_PIDFILEDIR}"
+	log_job_message "Completed installation of $xhost" 0
 }
 
 function start_rs
@@ -2163,26 +2167,6 @@ EOF
   TYPE="'shardsvr','arbiter'"
   SERVER_LIST=$(get_servers2 $TYPE)
   FOUND=0
-#  if [ "$SERVER_LIST" != "NULL" ]; then
-#      for r in $SERVER_LIST
-#      do
-#	  HNAME=`echo $r | awk -F ',' '{print $1};'`
-#	  NODEID=`echo $r | awk -F ',' '{print $2};'`
-#	  PORT=`echo $r | awk -F ',' '{print $3};'`
-#	  if [ "$HNAME" = "$XHOSTNAME" ] && [ "$PORT" = "$XPORT" ]; then
-#	      stop_node $HNAME $NODEID
-#	      FOUND=1
-#	  fi
-#     done
-#  else
-#      exit 1
-#  fi  
-
-
-## if [ $FOUND -eq 0 ]; then
-#     echo "$XHOSTNAME:$XPORT was not found in mongodb_server, cannot remove."
-#     exit 1
-# fi
 
   sleep 2
   TYPE="shardsvr"
@@ -2222,12 +2206,14 @@ EOF
   sed  -i.bak "s#ARBIT_PORT#${XPORT}#g"  /tmp/remove.js
   
   ${MONGODB_BASEDIR}/bin/mongo ${RS_HNAME}:${RS_PORT} /tmp/remove.js
-  
+  log_job_message " ${MONGODB_BASEDIR}/bin/mongo ${RS_HNAME}:${RS_PORT} /tmp/remove.js" 0
   if [ $? -ne 0 ]; then
       sleep 1
       ${MONGODB_BASEDIR}/bin/mongo  ${RS_HNAME}:${RS_PORT} /tmp/remove.js
+      log_job_message " ${MONGODB_BASEDIR}/bin/mongo ${RS_HNAME}:${RS_PORT} /tmp/remove.js" 0
       if [ $? -ne 0 ]; then
 	  ${MONGODB_BASEDIR}/bin/mongo   ${RS_HNAME}:${RS_PORT} --eval "rs.remove('$XHOSTNAME:$XPORT')"
+	  log_job_message " ${MONGODB_BASEDIR}/bin/mongo ${RS_HNAME}:${RS_PORT} --eval rs.remove('$XHOSTNAME:$XPORT')" 0
 	  if [ $? -ne 0 ]; then
 	      echo "failed to remove $XHOSTNAME:$XPORT"
 	      exit 1
