add install of perl

diff --git a/cluster/s9s_backup b/cluster/s9s_backup
--- a/cluster/s9s_backup
+++ b/cluster/s9s_backup
@@ -38,6 +38,20 @@ function init
 ### NO MODS BELOW UNLESS YOU KNOW WHAT YOU DO:
     jobid=0    
     OSUSER=$USER    
+    if ! test -f $MYSQL_BIN; then
+	if ! test -f $MYSQL_BIN2; then
+	    echo "Could not find mysql client binary"
+	    echo "Change MYSQL_BIN in beginning of the scipt"
+	    exit 1
+	fi
+	MYSQL_BIN=$MYSQL_BIN2
+    fi
+    if ! test -f $MYSQL_BIN; then
+	echo "Could not find mysql client binary"
+	log_job_message "Could not find mysql client binary" 1
+	log_job 'FAILED' 'backup failed' 1
+	exit 1
+    fi
 }
 
 function load_opts 
