updated scripts

diff --git a/cluster/s9s_backup b/cluster/s9s_backup
--- a/cluster/s9s_backup
+++ b/cluster/s9s_backup
@@ -3,34 +3,93 @@
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
 
+function init
+{
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`    
+    FILES="$FILES $FILES2"
+    configfile=""
+    for f in $FILES 
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `	
+	if [ $? -eq 0 ]; then 
+	    source $f
+            configfile=$f
+	fi
+    done
 
-if [ ! -e /etc/cmon.cnf ] ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
-else
-    source /etc/cmon.cnf
-fi
+    if [ -z "$configfile" ]; then
+	echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+	exit 1
+    fi
+    
+    source $configfile
 #CLUSTER_ID=$cluster_id
-CMON_USER=cmon
-CMON_PASSWORD=$mysql_password
-CMON_DB_HOST=$mysql_hostname
-CMON_DB_DB=cmon
-MYSQL_BIN=$mysql_basedir/bin//mysql
-MYSQL_BIN2=$mysql_bindir/mysql
-BACKUP_LOGFILE=/tmp/s9s_backup.log
-LOCKFILE="/tmp/s9s_backup.lock"
-XTRABACKUP_BIN=/usr/bin/innobackupex
-ULIMIT=32768
+    CMON_USER=cmon
+    CMON_PASSWORD=$mysql_password
+    CMON_DB_HOST=$mysql_hostname
+    CMON_DB_DB=cmon
+    MYSQL_BIN=$mysql_basedir/bin//mysql
+    MYSQL_BIN2=$mysql_bindir/mysql
+    BACKUP_LOGFILE=/tmp/s9s_backup.log
+    LOCKFILE="/tmp/s9s_backup.lock"
+    XTRABACKUP_BIN=/usr/bin/innobackupex
+    ULIMIT=32768
 ### NO MODS BELOW UNLESS YOU KNOW WHAT YOU DO:
-jobid=0
+    jobid=0    
+    OSUSER=$USER    
+}
 
-ACTION=$1
+function load_opts 
+{
+    local CLUSTER_ID=$1
+    echo "load opts $CLUSTER_ID"
+    OS=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS' AND cid=$CLUSTER_ID" 2>/dev/null`
+    CONFIGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='CONFIGDIR' AND cid=$CLUSTER_ID" 2>/dev/null`
+    HTTP_PROXY=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='HTTP_PROXY' AND cid=$CLUSTER_ID" 2>/dev/null`
+    MYSQL_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MYSQL_PORT' AND cid=$CLUSTER_ID" 2>/dev/null`
+    GALERA_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='GALERA_PORT' AND cid=$CLUSTER_ID" 2>/dev/null`
+    MYSQL_BASEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MYSQL_BASEDIR' AND cid=$CLUSTER_ID" 2>/dev/null`
+    MYSQL_SCRIPTDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SCRIPTDIR' AND cid=$CLUSTER_ID" 2>/dev/null`
+    SSH_IDENTITY=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SSH_IDENTITY' AND cid=$CLUSTER_ID" 2>/dev/null`
+    SSH_USER=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SSH_USER' AND cid=$CLUSTER_ID" 2>/dev/null`
+    SSH_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SSH_PORT' AND cid=$CLUSTER_ID" 2>/dev/null`
+    SUDO=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SUDO' AND cid=$CLUSTER_ID" 2>/dev/null`
+    S9S_TMPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='STAGING_DIR' AND cid=$CLUSTER_ID"`
+    OS_USER_HOME=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS_USER_HOME' AND cid=$CLUSTER_ID" 2>/dev/null`
+    DATADIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon.cluster_config where variable='datadir' and cid=1 order by id asc limit 1" 2>/dev/null`
+    
+    SSH_OPTS="-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -oNumberOfPasswordPrompts=0 -oConnectTimeout=10"
+    if [ "$SSH_IDENTITY" = "" ]; then
+	SSH_IDENTITY="-oIdentityFile=${OS_USER_HOME}/.ssh/id_rsa"
+    else
+	SSH_IDENTITY="-oIdentityFile=$SSH_IDENTITY"
+    fi
 
-OSUSER=$USER
-if [ "$OSUSER" != "root" ]; then
-    echo "must be executed as 'root' or with 'sudo'"
-    exit 1
-fi
+    SSH_OPTS="-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -oNumberOfPasswordPrompts=0 -oConnectTimeout=10 $SSH_IDENTITY"
+    SCP_OPTS="-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -oNumberOfPasswordPrompts=0 -oConnectTimeout=10 $SSH_IDENTITY"
+    if [ "$SSH_USER" != "root" ]; then
+	SSH_OPTS="-q -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -oNumberOfPasswordPrompts=0 -oConnectTimeout=10 $SSH_IDENTITY"
+	SCP_OPTS="-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -oNumberOfPasswordPrompts=0 -oConnectTimeout=10 $SSH_IDENTITY"
+	if [ "$SUDO" = "" ] || [ "$SUDO" = "NULL" ];  then
+           SUDO=sudo
+        fi
+    fi
+
+    if [ "$SSH_PORT" = "" ] || [ "$SSH_PORT" = "NULL" ];  then
+        SSH_PORT="22"
+    fi
+    SSH_OPTS="-p$SSH_PORT $SSH_OPTS -n"    
+    SSH_OPTS2="-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -oNumberOfPasswordPrompts=0 -oConnectTimeout=10 $SSH_IDENTITY -p$SSH_PORT"    
+    if [ "$SSH_USER" != "root" ]; then
+	SSH_OPTS="$SSH_OPTS -t"    
+    fi
+    SCP_OPTS="-P$SSH_PORT $SCP_OPTS"    
+    if [ "$S9S_TMPDIR" = "" ] || [ "$TMPDIR" = "NULL" ];  then
+	S9S_TMPDIR="/tmp/"
+	TMPDIR="/tmp/"
+    fi
+}
 
 
 function write_email
@@ -38,7 +97,7 @@ function write_email
   SUBJECT=$1
   MSG=$2
   cat $BACKUP_LOGFILE | sed  -e "s/'/\\\'/g" -e 's/"/\\"/g' > /tmp/s9s_backup_log_escaped
-  MSG="$MSG \n `cat /tmp/s9s_backup_log_escaped`" 
+  MSG="$MSG \nBackup log follows:\n `cat /tmp/s9s_backup_log_escaped`" 
   QUERY="INSERT INTO simple_email(cid,subject,message) VALUES($CLUSTER_ID, \"$SUBJECT\", \"$MSG\")"
   $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log
 }
@@ -117,7 +176,7 @@ function start_backup
       echo "s9s_backup  --backup -i <clusterid> missing"
       exit 1
     fi
-
+    init
     if [ -z "$TYPE" ]; then
       echo "s9s_backup  --backup -t <full|incr> missing"
       exit 1
@@ -291,7 +350,7 @@ function start_backup
 	QUERY="UPDATE mysql_backup SET status='failed', error=1 WHERE status='running' AND hostname='$HNAME' "
 	$MYSQL_BIN --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "$QUERY"
 	
-	QUERY="INSERT INTO mysql_backup(backupid, cid, hostname,directory,filename, size, error, status, report_ts, backup_type, backup_method) VALUES($ID, $CLUSTER_ID, '$HNAME', '$BACKUPDIR','',0,0,'running',now(), '$TYPE', 'xtrabackup')"
+	QUERY="INSERT INTO mysql_backup(backupid, cid, hostname,directory,filename, size, error, status, report_ts, backup_type, backup_method, storage_host) VALUES($ID, $CLUSTER_ID, '$HNAME', '$BACKUPDIR','',0,0,'running',now(), '$TYPE', 'xtrabackup', '$HNAME')"
 	$MYSQL_BIN --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "$QUERY"
 	if [ $? -ne 0 ]; then
 	    log_job_message "Failed to create backup record" 1
@@ -410,7 +469,7 @@ function purge_backups
       echo "s9s_backup  --backup -i <clusterid> missing"
       exit 1
     fi
-
+    init
     if ! test -f $MYSQL_BIN; then
 	if ! test -f $MYSQL_BIN2; then
 	    echo "Could not find mysql client binary"
@@ -522,7 +581,7 @@ function purge_backups
 
 function restore
 {    
-    args=`getopt p:h:i:b:t: $*`
+    args=`getopt p:h:i:b:t:e: $*`
     set -- $args
     for i
     do
@@ -539,6 +598,9 @@ function restore
             -t)
 		TARGETDIR="$2"; shift;
 		shift;;
+            -e)
+		EXCLUDE_BACKUPID="$2"; shift;
+		shift;;
             --)
 		shift; break;;
 		esac
@@ -548,6 +610,7 @@ function restore
 	echo "s9s_backup  --restore -i <clusterid> missing"
 	exit 1
     fi
+    init 
     if [ -z "$BACKUPID" ]; then
 	echo "s9s_backup  --restore -b <backup set> missing"
 	exit 1
@@ -654,6 +717,9 @@ function restore
       for f in $LIST
       do      
 	  backupid=`echo $f | awk -F ',' '{print $1;}'`
+	  if [ $backupid -ge $EXCLUDE_BACKUPID ];  then
+	      continue
+	  fi
 	  backup_type=`echo $f | awk -F ',' '{print $2;}'`
 	  location=`echo $f | awk -F ',' '{print $3;}'`
 	  status=`echo $f | awk -F ',' '{print $4;}'`
@@ -737,7 +803,7 @@ function list_backups
       echo "s9s_backup  --list -i <clusterid> missing"
       exit 1
     fi
-
+    init
     if ! test -f $MYSQL_BIN; then
 	if ! test -f $MYSQL_BIN2; then
 	    echo "Could not find mysql client binary"
@@ -836,7 +902,7 @@ function install
       echo "s9s_backup  --install -i <clusterid> missing"
       exit 1
     fi
-
+    init
     if [ -z "$BACKUPDIR" ]; then
 	BACKUPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='BACKUPDIR' AND cid=$CLUSTER_ID"`
     fi
@@ -869,15 +935,17 @@ function install
 	echo "./s9s_backup --install -i <clusterid -c "
 	exit 1
     fi
-    
+    load_opts $CLUSTER_ID
+    mkdir -p $S9S_TMPDIR
+    chown -R ${SSH_USER}:${SSH_USER} ${S9S_TMPDIR}
     chown mysql:mysql  $MYCNF 
     log_job_message "Installing xtrabackup" 0
     case $OS in
 	redhat)
-            rpm -Uhv http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm
-	    yum -y install xtrabackup  
-	    yum -y install perl-Time-HiRes
-	    yum -y install nc 
+            $HTTP_PROXY rpm -Uhv http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm
+	    $HTTP_PROXY yum -y install xtrabackup  
+	    $HTTP_PROXY yum -y install perl-Time-HiRes
+	    $HTTP_PROXY yum -y install nc
 
 	    if [ $? -ne 0 ]; then
                    log_job_message "Installation of xtrabackup failed" 1
@@ -886,16 +954,18 @@ function install
 	    fi
 	    ;;
 	debian)
+	    $HTTP_PROXY apt-get -q -y update 
+	    hash lsb_release 2>/dev/null || {  $HTTP_PROXY apt-get install lsb-release ; }
 	    LSB=`lsb_release -c -s`
 	    if [ -z "$LSB" ]; then
 		echo "'lsb_release -c -s' return empty"
                 log_job_message "lsb_release -c -s return empty" 1
 		exit 1
 	    fi
-	    gpg --keyserver  hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
+	    $HTTP_PROXY gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona
 	    if [ $? -ne 0 ]; then
-		echo "FAILED: gpg --keyserver  hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A"
-                log_job_message "FAILED: gpg --keyserver  hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A" 1
+		echo "FAILED: $HTTP_PROXY gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
+                log_job_message "FAILED: $HTTP_PROXY gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona" 1
 		exit 1
 	    fi
 	    gpg -a --export CD2EFD2A | apt-key add -
@@ -907,15 +977,15 @@ function install
 	    sed -i.bak '/percona/d' /etc/apt/sources.list
 	    echo "deb http://repo.percona.com/apt $LSB main" |  tee --append /etc/apt/sources.list
 	    echo "deb-src http://repo.percona.com/apt $LSB main" | tee --append /etc/apt/sources.list
-	    apt-get -q -y update
-	    LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install percona-xtrabackup 
+	    $HTTP_PROXY apt-get -q -y update
+	    LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install percona-xtrabackup 
 	    if [ $? -ne 0 ]; then
 		echo "Installation of xtrabackup failed"
-                log_job_message "Installation of xtrabackup failed : apt-get install percona-xtrabackup nc" 1
+                log_job_message "Installation of xtrabackup failed : $HTTP_PROXY apt-get install percona-xtrabackup nc" 1
 		cp  $CONFIGDIR/my.cnf.dpkg-old $CONFIGDIR/my.cnf
 		exit 1
 	    fi
-	    LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install nc netcat
+	    LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install netcat-openbsd netcat
 	    cp  $CONFIGDIR/my.cnf.dpkg-old $CONFIGDIR/my.cnf
 	    ;;
 	*)
@@ -981,20 +1051,20 @@ function checkenv
 
 function check_mysql_client()
 {
-   if [ ! -f $MYSQL_BIN ]; then
+    if [ ! -f $MYSQL_BIN ]; then
         # Try normal locations:
         MYSQL_BIN="/usr/bin/mysql"
         if [ ! -f $MYSQL_BIN ]; then
-             MYSQL_BIN="/usr/local/mysql/bin/mysql"
-             if [ ! -f $MYSQL_BIN ]; then
-		 echo "The MySQL client binary could not be found"         
-		 if [ "$mysql_basedir" = "" ]; then
-		     echo "mysql_basedir in /etc/cmon.cnf is not set. Add it to /etc/cmon.cnf"
-		     exit 1		     
-		 fi
-             fi
+            MYSQL_BIN="/usr/local/mysql/bin/mysql"
+            if [ ! -f $MYSQL_BIN ]; then
+		echo "The MySQL client binary could not be found"         
+		if [ "$mysql_basedir" = "" ]; then
+		    echo "mysql_basedir in /etc/cmon.cnf is not set. Add it to /etc/cmon.cnf"
+		    exit 1		     
+		fi
+            fi
 	fi
-   fi
+    fi
 }
 
 check_mysql_client
diff --git a/cluster/s9s_backupc b/cluster/s9s_backupc
--- a/cluster/s9s_backupc
+++ b/cluster/s9s_backupc
@@ -2,40 +2,61 @@
 # Copyright 2012 Severalnines AB
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
-
-
-if [ ! -e /etc/cmon.cnf ] ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
-else
-    source /etc/cmon.cnf
-fi
-#CLUSTER_ID=$cluster_id
-CMON_USER=cmon
-CMON_PASSWORD=$mysql_password
-CMON_DB_HOST=$mysql_hostname
-CMON_DB_DB=cmon
-CMON_DB_PORT=$mysql_port
-MYSQL_BIN=$mysql_basedir/bin//mysql
-MYSQL_BIN2=$mysql_bindir/mysql
-BACKUP_LOGFILE=/tmp/s9s_backup.log
-LOCKFILE="/tmp/s9s_backup.lock"
-XTRABACKUP_BIN=/usr/bin/innobackupex
-NETCAT_PORT=59999
-ULIMIT=32768
-### NO MODS BELOW UNLESS YOU KNOW WHAT YOU DO:
 jobid=0
+function init
+{    
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`    
+    FILES="$FILES $FILES2"
+    configfile=""
+    for f in $FILES 
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `	
+	if [ $? -eq 0 ]; then 
+	    source $f
+            configfile=$f
+	fi
+    done
 
-ACTION=$1
+    if [ -z "$configfile" ]; then
+	echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+	exit 1
+    fi
+    
+    source $configfile
+    
+#CLUSTER_ID=$cluster_id
+    CMON_USER=cmon
+    CMON_PASSWORD=$mysql_password
+    CMON_DB_HOST=$mysql_hostname
+    CMON_DB_DB=cmon
+    CMON_DB_PORT=$mysql_port
+    MYSQL_BIN=$mysql_basedir/bin//mysql
+    MYSQL_BIN2=$mysql_bindir/mysql
+    BACKUP_LOGFILE=/tmp/s9s_backup.log
+    LOCKFILE="/tmp/s9s_backup.lock"
+    XTRABACKUP_BIN=/usr/bin/innobackupex
+    NETCAT_PORT=59999
+    ULIMIT=32768
+### NO MODS BELOW UNLESS YOU KNOW WHAT YOU DO:
+    OSUSER=$USER    
+    check_mysql_client
+    
+    
+    if [ "$OSUSER" != "root" ]; then
+	log_job_message "must be executed as 'root' or with 'sudo'" 1
+	exit 1
+    fi
 
-OSUSER=$USER
+}
+
 #INNOBACKUP_OPTS=" --lock-wait-threshold=40 --lock-wait-query-type=all --lock-wait-timeout=180 --kill-long-queries-timeout=20 --kill-long-query-type=all"
 function write_email
 {
   SUBJECT=$1
   MSG=$2
   cat $BACKUP_LOGFILE | sed  -e "s/'/\\\'/g" -e 's/"/\\"/g' > /tmp/s9s_backup_log_escaped
-  MSG="$MSG \n `cat /tmp/s9s_backup_log_escaped`" 
+  MSG="$MSG \nBackup log follows:\n `cat /tmp/s9s_backup_log_escaped`" 
   QUERY="INSERT INTO simple_email(cid,subject,message) VALUES($CLUSTER_ID, \"$SUBJECT\", \"$MSG\")"
   $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log
 }
@@ -113,19 +134,23 @@ function start_backup
     done    
 
     if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_backup  --backup -i <clusterid> missing"
+      echo "s9s_backupc  --backup -i <clusterid> missing"
       exit 1
     fi
     if [ -z "$BACKUP_HOSTNAME" ]; then
-      echo "s9s_backup  --backup -h <backup hostname> missing"
+      echo "s9s_backupc  --backup -h <backup hostname> missing"
       exit 1
     fi
 
     if [ -z "$TYPE" ]; then
-      echo "s9s_backup  --backup -t <full|incr> missing"
+      echo "s9s_backupc  --backup -t <full|incr> missing"
       exit 1
     fi
-    log_job 'RUNNING' 'Job is running' 0
+    if [ "$jobid" = "" ]; then 
+	jobid=0
+    fi
+    init 
+    I=0
     log_job_message "Loading options" 0
     load_opts $CLUSTER_ID
     MYCNF=${CONFIGDIR}/my.cnf
@@ -155,7 +180,7 @@ function start_backup
     fi
 
     if [ ! -e $LOCKFILE ]; then
-	trap "rm -f $LOCKFILE; killall -9 s9s_backupc_wd; rm -rf /tmp/xtrabackup_pid; exit" INT TERM EXIT
+	trap "rm -f $LOCKFILE; killall -9 s9s_backupc_wd nc; rm -rf /tmp/xtrabackup_pid; exit" INT TERM EXIT
 	touch $LOCKFILE	
 	if which pv &> /dev/null; then
             #THROTTLE="--throttle=30"
@@ -175,10 +200,13 @@ function start_backup
   ##Where to store the backup
 
 	FAIL=0
-	if [ "$jobid" = "" ]; then 
-	    jobid=0
-	fi
-	
+
+	while [ $I -lt 5 ]; 
+	do
+	    log_job 'RUNNING' 'Job is running' 0
+	    I=`expr $I + 1`
+	    sleep 1
+	done	
 #        echo $SSH_OPTS
 	x=`ssh $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME '$SUDO which innobackupex' 2>/dev/null`
 	if [ "$x" = ""  ]; then
@@ -192,7 +220,7 @@ function start_backup
 	    log_job 'FAILED' 'backup failed' 1
 	    exit 1
 	fi
-
+	log_job 'RUNNING' 'Job is running' 0
 	QUERY="select count(id) from mysql_server where cid=$CLUSTER_ID AND hostname='$BACKUP_HOSTNAME'"
 	CNT=`$MYSQL_BIN  -A -B -N --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" `
 	if [ $CNT -eq 0 ]; then 
@@ -319,19 +347,36 @@ function start_backup
 	remote_cmd_nofail $BACKUP_HOSTNAME "rm -rf $BACKUP_LOGFILE"
 	remote_cmd_nofail $BACKUP_HOSTNAME "/bin/sh -c 'echo start_backup >>  $BACKUP_LOGFILE'"
 	if [ -f /usr/bin/s9s_backupc_wd ]; then
-           /usr/bin/s9s_backupc_wd $BACKUP_LOGFILE $BACKUP_HOSTNAME $SSH_USER "$SSH_OPTS2" "$SCP_OPTS" "$SUDO" $NETCAT_PORT $BACKUPDIR/$FILENAME   &
+            /usr/bin/s9s_backupc_wd $BACKUP_LOGFILE $BACKUP_HOSTNAME $SSH_USER "$SSH_OPTS2" "$SCP_OPTS" "$SUDO" $NETCAT_PORT $BACKUPDIR/$FILENAME   &
+            pid="$!"
+	    #echo "   /usr/bin/s9s_backupc_wd $BACKUP_LOGFILE $BACKUP_HOSTNAME $SSH_USER "$SSH_OPTS2" "$SCP_OPTS" "$SUDO" $NETCAT_PORT $BACKUPDIR/$FILENAME   "
+	    ##exit 1
+	    log_job 'RUNNING' 'Job is running' 0
         else
   	   if [ -f /usr/local/cmon/bin/s9s_backupc_wd ]; then
                /usr/local/cmon/bin/s9s_backupc_wd $BACKUP_LOGFILE $BACKUP_HOSTNAME $SSH_USER "$SSH_OPTS2" "$SCP_OPTS" "$SUDO" $NETCAT_PORT $BACKUPDIR/$FILENAME &
+               pid="$!"
 	   else
                echo "s9s_backup_wd not found in /usr/bin/s9s_backupc_wd  or /usr/local/cmon/bin/s9s_backupc_wd " 
 	       log_message "s9s_backupc_wd was not found in /usr/bin/s9s_backupc_wd  or /usr/local/cmon/bin/s9s_backupc_wd " 1 
+	       log_job 'FAILED' 'job failed' 0
 	       exit 1
            fi 
         fi
-        pid="$!"
+	log_job_message "s9s_backupc_wd started with pid=$pid" 0
 	sleep 5
+	nc_pid=`pgrep -f 'nc -d'`
+	if [ -z "$nc_pid" ]; then
+                write_email "Backup failed" "could not start nc -d -l 59999"
+                log_job_message "could not start nc -d -l 59999" 1
+                log_job 'FAILED' 'backup failed' 1
+                rm -rf $LOCKFILE
+                trap - INT TERM EXIT
+                exit 1
+	fi		
+	log_job_message "nc started with pid=$nc_pid" 0
 	if [ "$TYPE" = "full" ]; then   
+	    log_job 'RUNNING' 'Job is running' 0
  	    ssh $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO   --defaults-file=$MYCNF --host=127.0.0.1 --user=$CMON_USER --password=$CMON_PASSWORD $INNOBACKUP_OPTS $THROTTLE  --stream=tar ./  2>$BACKUP_LOGFILE | gzip  - | nc $STORAGE_HNAME $NETCAT_PORT  '" 
 	    ret=$?
 	    scp -q $SCP_OPTS $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE $BACKUP_LOGFILE
@@ -341,6 +386,7 @@ function start_backup
 		ret=1
 	    fi
 	else
+	    log_job 'RUNNING' 'Job is running' 0
  	    ssh  $SSH_OPTS  $SSH_USER@$BACKUP_HOSTNAME "$SUDO sh -c 'ulimit -n $ULIMIT && $XTRABACKUP_BIN $GALERA_INFO  --defaults-file=$MYCNF --host=127.0.0.1 --user=$CMON_USER --password=$CMON_PASSWORD --incremental --incremental-lsn=$LSN $INNOBACKUP_OPTS $THROTTLE  --stream=xbstream ./  2>$BACKUP_LOGFILE | gzip  - | nc $STORAGE_HNAME $NETCAT_PORT  '" 
 	    ret=$?
 	    scp -q $SCP_OPTS $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE $BACKUP_LOGFILE
@@ -359,6 +405,7 @@ function start_backup
 	    ret=1
 	fi
         wait $pid  || let "FAIL=1"
+	log_job_message "wait $pid  --> FAIL=$FAIL" 0
 	scp -q $SCP_OPTS  $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE  $BACKUP_LOGFILE	
 	write_logfile $ID
 	remote_cmd_nofail $BACKUP_HOSTNAME "rm -rf /tmp/xtrabackup_pid"
@@ -456,8 +503,8 @@ function purge_backups
 	echo "s9s_backupc  --purge -i <clusterid> missing"
 	exit 1
     fi
-
-
+    init
+    
     if ! test -f $MYSQL_BIN; then
 	if ! test -f $MYSQL_BIN2; then
 	    echo "Could not find mysql client binary"
@@ -569,7 +616,7 @@ function purge_backups
 
 function restore
 {    
-    args=`getopt h:i:b:t: $*`
+    args=`getopt h:i:b:t:e: $*`
     set -- $args
     for i
     do
@@ -586,6 +633,9 @@ function restore
             -t)
 		TARGETDIR="$2"; shift;
 		shift;;
+            -e)
+		EXCLUDE_BACKUPID="$2"; shift;
+		shift;;
             --)
 		shift; break;;
 		esac
@@ -595,6 +645,7 @@ function restore
 	echo "s9s_backupc  --restore -i <clusterid> missing"
 	exit 1
     fi
+    init
     if [ -z "$BACKUPID" ]; then
 	echo "s9s_backupc  --restore -b <backup set> missing"
 	exit 1
@@ -724,6 +775,9 @@ function restore
   for f in $LIST
   do      
       backupid=`echo $f | awk -F ',' '{print $1;}'`
+      if [ $backupid -ge $EXCLUDE_BACKUPID ];  then
+	  continue
+      fi
       backup_type=`echo $f | awk -F ',' '{print $2;}'`
       location=`echo $f | awk -F ',' '{print $3;}'`
       status=`echo $f | awk -F ',' '{print $4;}'`
@@ -781,6 +835,7 @@ function load_opts
     echo "load opts $CLUSTER_ID"
     OS=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS' AND cid=$CLUSTER_ID" 2>/dev/null`
     CONFIGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='CONFIGDIR' AND cid=$CLUSTER_ID" 2>/dev/null`
+    HTTP_PROXY=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='HTTP_PROXY' AND cid=$CLUSTER_ID" 2>/dev/null`
     MYSQL_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MYSQL_PORT' AND cid=$CLUSTER_ID" 2>/dev/null`
     GALERA_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='GALERA_PORT' AND cid=$CLUSTER_ID" 2>/dev/null`
     MYSQL_BASEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MYSQL_BASEDIR' AND cid=$CLUSTER_ID" 2>/dev/null`
@@ -789,7 +844,7 @@ function load_opts
     SSH_USER=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SSH_USER' AND cid=$CLUSTER_ID" 2>/dev/null`
     SSH_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SSH_PORT' AND cid=$CLUSTER_ID" 2>/dev/null`
     SUDO=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SUDO' AND cid=$CLUSTER_ID" 2>/dev/null`
-    
+    S9S_TMPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='STAGING_DIR' AND cid=$CLUSTER_ID"`
     OS_USER_HOME=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS_USER_HOME' AND cid=$CLUSTER_ID" 2>/dev/null`
     DATADIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon.cluster_config where variable='datadir' and cid=1 order by id asc limit 1" 2>/dev/null`
     
@@ -819,6 +874,10 @@ function load_opts
 	SSH_OPTS="$SSH_OPTS -t"    
     fi
     SCP_OPTS="-P$SSH_PORT $SCP_OPTS"    
+    if [ "$S9S_TMPDIR" = "" ] || [ "$TMPDIR" = "NULL" ];  then
+	S9S_TMPDIR="/tmp/"
+	TMPDIR="/tmp/"
+    fi
 }
 
 function list_backups
@@ -843,7 +902,7 @@ function list_backups
 	echo "s9s_backupc  --list -i <clusterid> missing"
 	exit 1
     fi
-
+    init
     if ! test -f $MYSQL_BIN; then
 	if ! test -f $MYSQL_BIN2; then
 	    echo "Could not find mysql client binary"
@@ -935,6 +994,7 @@ function install
       echo "s9s_backup  --install -i <clusterid> missing"
       exit 1
     fi
+    init 
     if [ -z "$BACKUP_HOSTNAME" ]; then
       echo "s9s_backup  --install -h <backup hostname> missing"
       exit 1
@@ -974,10 +1034,10 @@ function install
     log_job_message "Installing xtrabackup" 0
     case $OS in
 	redhat)
-            remote_cmd $BACKUP_HOSTNAME "rpm -Uhv http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
-            remote_cmd $BACKUP_HOSTNAME "yum -y install xtrabackup  "
-	    remote_cmd $BACKUP_HOSTNAME "yum -y install perl-Time-HiRes"
-	    remote_cmd $BACKUP_HOSTNAME "yum -y install nc "
+            remote_cmd $BACKUP_HOSTNAME "$HTTP_PROXY rpm -Uhv http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
+            remote_cmd $BACKUP_HOSTNAME "$HTTP_PROXY yum -y install xtrabackup  "
+	    remote_cmd $BACKUP_HOSTNAME "$HTTP_PROXY yum -y install perl-Time-HiRes"
+	    remote_cmd $BACKUP_HOSTNAME "$HTTP_PROXY yum -y install nc "
 	    ;;
 	debian)
 	    LSB=`lsb_release -c -s`
@@ -986,16 +1046,19 @@ function install
                 log_job_message "lsb_release -c -s return empty" 1
 		exit 1
 	    fi
-	    remote_cmd $BACKUP_HOSTNAME "sh -c 'gpg --keyserver  hkp://keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A'"
+	    remote_cmd_nofail $BACKUP_HOSTNAME "mkdir -p $S9S_TMPDIR"
+	    remote_cmd $BACKUP_HOSTNAME "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
+	    remote_cmd $BACKUP_HOSTNAME "$HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona"
+	    remote_cmd $BACKUP_HOSTNAME "gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
 	    remote_cmd $BACKUP_HOSTNAME "sh -c 'gpg -a --export CD2EFD2A | apt-key add -'"
 	    remote_cmd $BACKUP_HOSTNAME "sed -i.bak '/percona/d' /etc/apt/sources.list"
 	    remote_cmd $BACKUP_HOSTNAME "sh -c 'echo \"deb http://repo.percona.com/apt $LSB main\" >> /etc/apt/sources.list'"
 	    remote_cmd $BACKUP_HOSTNAME "sh -c 'echo \"deb-src http://repo.percona.com/apt $LSB main\" >> /etc/apt/sources.list'"
-	    remote_cmd $BACKUP_HOSTNAME "apt-get -q -y update"
-	    remote_cmd $BACKUP_HOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install percona-xtrabackup "
+	    remote_cmd $BACKUP_HOSTNAME "$HTTP_PROXY apt-get -q -y update"
+	    remote_cmd $BACKUP_HOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install percona-xtrabackup "
 	    
-	    remote_cmd $BACKUP_HOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install netcat"
-	    remote_cmd_nofail $BACKUP_HOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install netcat-openbsd"
+	    remote_cmd $BACKUP_HOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install netcat"
+	    remote_cmd_nofail $BACKUP_HOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install netcat-openbsd"
 	    remote_cmd_nofail $BACKUP_HOSTNAME "cp  $CONFIGDIR/my.cnf.dpkg-old $CONFIGDIR/my.cnf"
 	    ;;
 	*)
@@ -1111,33 +1174,28 @@ function check_mysql_client()
    fi
 }
 
-check_mysql_client
+ulimit -n $ULIMIT
+ARG=$1
+shift
 
-
-if [ "$OSUSER" != "root" ]; then
-    log_job_message "must be executed as 'root' or with 'sudo'" 1
-    exit 1
-fi
-
-
-case $1 in
+case $ARG in
     --backup)
-	start_backup $2 $3 $4 $5 $6 $7 $8 $9
+	start_backup $*
 	;;
     --purge)
-	purge_backups $2 $3 $4 $5 $6 $7 $8 $9
+	purge_backups $*
 	;;
     --list)
-	list_backups  $2 $3 $4 $5 $6 $7 $8 $9
+	list_backups  $*
 	;;
     --install)
-	install $2 $3 $4 $5 $6 $7 $8 $9
+	install $*
 	;;
     --restore)
-	restore $2 $3 $4 $5 $6 $7 $8 $9
+	restore $*
 	;;
     --checkenv)
-	checkenv $2 $3 $4 $5 $6 $7 $8 $9
+	checkenv $*
 	;;
     *)
     echo "Usage:"
diff --git a/cluster/s9s_backupc_wd b/cluster/s9s_backupc_wd
--- a/cluster/s9s_backupc_wd
+++ b/cluster/s9s_backupc_wd
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+set -x 
 BACKUP_LOGFILE=$1
 BACKUP_HOSTNAME=$2
 SSH_USER=$3
@@ -19,10 +19,13 @@ ret=$?
 pid=$!
 
 if [ $ret -ne 0 ]; then
-   echo "Failed to start netcat"
-   exit 1
+   nc -d -l $NETCAT_PORT > $BACKUPFILE &
+   ret=$?
+   if [ $ret -ne 0 ]; then
+     echo "Failed to start netcat" >> /tmp/s9s_backupc_wd.log
+     exit 1
+   fi
 fi
-#echo $SSH_OPTS
 sleep 60
 
 while [ 1 ]; 
@@ -30,7 +33,6 @@ do
     x=`ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME "pgrep -f innobackupex" `
     ret=$?
     echo "s9s_backupc_wd:  $x " >> $BACKUP_LOGFILE
-   #if [ $ret -eq 0 ]; 
     if [ -n "$x" ]; 
     then
 	scp -q $SCP_OPTS $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE $BACKUP_LOGFILE
@@ -39,6 +41,7 @@ do
             sleep $SLEEPTIME
             ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME "$SUDO killall -q -9 xtrabackup innobackupex xtrabackup_55 xtrabackup_56"
             echo "BACKUP FAILED: $err " >> $BACKUP_LOGFILE
+            echo "BACKUP FAILED: $err " >> /tmp/s9s_backupc_wd.log
 	    kill -9 $pid 2>/dev/null
             exit 1
 	fi
@@ -48,6 +51,7 @@ do
 	    do
 		ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME "$SUDO kill -15 $p"
 	    done
+            echo "BACKUP FAILED: $err " >> /tmp/s9s_backupc_wd.log
 	    kill -9 $pid 2>/dev/null
 	    exit 0
 	fi
diff --git a/cluster/s9s_clone b/cluster/s9s_clone
--- a/cluster/s9s_clone
+++ b/cluster/s9s_clone
@@ -2,32 +2,45 @@
 # Copyright 2012 Severalnines AB
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
-
-
-if [ ! -e /etc/cmon.cnf ] ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
-else
-    source /etc/cmon.cnf
-fi
-
-
-CMON_DB_HOST=127.0.0.1
-CMON_DB_PORT=$mysql_port
-CMON_USER=cmon
-CMON_DB_DB=cmon
-CMON_PASSWORD=$mysql_password
-MYSQL_BIN=$mysql_basedir/bin/mysql
-CONNECT_TIMEOUT=10
-CLUSTER_TYPE=$type
-MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
 LOCKFILE="/tmp/s9s_clone.lock"
-OSUSER=$USER
-JOBID=0
-if [ "$OSUSER" != "root" ]; then
-    echo "must be executed as 'root' or with 'sudo'"
-    exit 1
-fi
+JOBID=0    
+function init
+{
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`    
+    FILES="$FILES $FILES2"
+    configfile=""
+    for f in $FILES 
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `	
+	if [ $? -eq 0 ]; then 
+	    source $f
+            configfile=$f
+	fi
+    done
+
+    if [ -z "$configfile" ]; then
+	echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+	exit 1
+    fi
+    
+    source $configfile
+    
+    CMON_DB_HOST=127.0.0.1
+    CMON_DB_PORT=$mysql_port
+    CMON_USER=cmon
+    CMON_DB_DB=cmon
+    CMON_PASSWORD=$mysql_password
+    MYSQL_BIN=$mysql_basedir/bin/mysql
+    CONNECT_TIMEOUT=10
+    CLUSTER_TYPE=$type
+    MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
+    OSUSER=$USER
+    if [ "$OSUSER" != "root" ]; then
+	echo "must be executed as 'root' or with 'sudo'"
+	exit 1
+    fi
+}
  
 
 function log_job_message
@@ -196,16 +209,17 @@ function install_agent
 		shift;;
 	esac
     done    
+    if [ -z "$CLUSTER_ID" ]; then
+	echo "s9s_clone "
+	exit 1
+    fi
+    init
 
     if [ -z "$CMON_PASSWORD" ]; then
 	echo "s9s_clone "
 	exit 1
     fi
     
-    if [ -z "$CLUSTER_ID" ]; then
-	echo "s9s_clone "
-	exit 1
-    fi
     
     if [ ! -f $AGENT_BINARY ]; then
 	echo "s9s_clone "
@@ -294,6 +308,13 @@ function install_mysql
 		shift;;
 	esac
     done    
+    
+    if [ -z "$CLUSTER_ID" ]; then
+	echo "s9s_clone "
+	exit 1
+    fi
+
+    init
     if [ -z "$CMON_PASSWORD" ]; then
 	echo "s9s_clone "
 	exit 1
@@ -301,11 +322,6 @@ function install_mysql
 
     if [ -z "$DONOR" ]; then
 	echo "donor -d not set "
-	exit 1
-    fi
-    
-    if [ -z "$CLUSTER_ID" ]; then
-	echo "s9s_clone "
 	exit 1
     fi
     
@@ -333,7 +349,7 @@ function install_mysql
 
 
 function create_cluster
-{
+{    
     DETACH=0
     OPTIONS=$*
     args=`getopt p:s:P:h:t:N:j:D $*`
@@ -365,6 +381,7 @@ function create_cluster
     done    
    
     CLUSTER_ID=${SOURCE_CLUSTER_ID} 
+    init
     log_job 'RUNNING' 's9s_clone is running' 0
     log_job_message "Checking arguments" 0
     if [ -z "$CMON_PASSWORD" ]; then
@@ -640,17 +657,18 @@ function delete_cluster
 		shift;;
 	esac
     done    
+    if [ -z "$CLUSTER_ID" ]; then
+	log_job_message "s9s_clone --delete -i <cluster id of cluster to be deleted> missing" 1
+	log_job 'FAILED' 's9s_clone --delete failed' 1
+	exit 1
+    fi
+    init
+
     log_job 'RUNNING' 's9s_clone --delete is running' 0
     log_job_message "Checking arguments" 0
 
     if [ -z "$CMON_PASSWORD" ]; then
 	log_job_message "s9s_clone --delete -p  missing" 1
-	log_job 'FAILED' 's9s_clone --delete failed' 1
-	exit 1
-    fi
-    
-    if [ -z "$CLUSTER_ID" ]; then
-	log_job_message "s9s_clone --delete -i <cluster id of cluster to be deleted> missing" 1
 	log_job 'FAILED' 's9s_clone --delete failed' 1
 	exit 1
     fi
@@ -747,6 +765,8 @@ function delete_cluster
 }
 function list_cluster
 {
+    CLUSTER_ID=1
+    init
     QUERY="select group_concat(id SEPARATOR ' ') FROM cluster"    
     RESULT=`$MYSQL_BIN  -A -B -N --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" `           
 
@@ -792,17 +812,18 @@ function move_node
 		shift;;
 	esac
     done    
+    if [ -z "$CLUSTER_ID" ]; then
+      log_job_message "s9s_clone  --move-node -s <source clusterid> missing" 1
+      log_job 'FAILED' 's9s_clone --move-node failed' 1
+      exit 1
+    fi
+    init
+
     log_job 'RUNNING' 's9s_clone --move-node is running' 0
     log_job_message "Checking arguments" 0
     
     if [ -z "$CMON_PASSWORD" ]; then
       log_job_message "s9s_clone  --move-node  -p  missing" 1
-      log_job 'FAILED' 's9s_clone --move-node failed' 1
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      log_job_message "s9s_clone  --move-node -s <source clusterid> missing" 1
       log_job 'FAILED' 's9s_clone --move-node failed' 1
       exit 1
     fi
@@ -931,17 +952,18 @@ function detach_cluster
 		shift;;
 	esac
     done    
+    if [ -z "$CLUSTER_ID" ]; then
+	log_job_message "s9s_clone --detach -i <clusterid> missing" 1
+	log_job 'FAILED' 's9s_clone --detach failed' 1
+	exit 1
+    fi
+    init
+
     log_job 'RUNNING' 's9s_clone --detach is running' 0
     log_job_message "Checking arguments" 0
 
     if [ -z "$CMON_PASSWORD" ]; then
 	log_job_message "s9s_clone --detach -p  missing" 1
-	log_job 'FAILED' 's9s_clone --detach failed' 1
-	exit 1
-    fi
-    
-    if [ -z "$CLUSTER_ID" ]; then
-	log_job_message "s9s_clone --detach -i <clusterid> missing" 1
 	log_job 'FAILED' 's9s_clone --detach failed' 1
 	exit 1
     fi
diff --git a/cluster/s9s_galera b/cluster/s9s_galera
--- a/cluster/s9s_galera
+++ b/cluster/s9s_galera
@@ -2,34 +2,46 @@
 # Copyright 2013 Severalnines AB
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
-
-
-if [ ! -e /etc/cmon.cnf ] ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
-else
-    source /etc/cmon.cnf
-fi
-
-
-CMON_DB_HOST=127.0.0.1
-CMON_DB_PORT=$mysql_port
-CMON_USER=cmon
-CMON_DB_DB=cmon
-CMON_PASSWORD=$mysql_password
-MYSQL_BIN=$mysql_basedir/bin/mysql
-CONNECT_TIMEOUT=10
-CLUSTER_TYPE=$type
-MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
 LOCKFILE="/tmp/s9s_galera.lock"
-OSUSER=$USER
 jobid=0
+function init
+{    
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`    
+    FILES="$FILES $FILES2"
+    configfile=""
+    for f in $FILES 
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `	
+	if [ $? -eq 0 ]; then 
+	    source $f
+            configfile=$f
+	fi
+    done
 
+    if [ -z "$configfile" ]; then
+	echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+	exit 1
+    fi
+    
+    source $configfile   
 
-if [ "$OSUSER" != "root" ]; then
-    echo "must be executed as 'root' or with 'sudo'"
-    exit 1
-fi
+    CMON_DB_HOST=127.0.0.1
+    CMON_DB_PORT=$mysql_port
+    CMON_USER=cmon
+    CMON_DB_DB=cmon
+    CMON_PASSWORD=$mysql_password
+    MYSQL_BIN=$mysql_basedir/bin/mysql
+    CONNECT_TIMEOUT=10
+    CLUSTER_TYPE=$type
+    MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
+    OSUSER=$USER
+        
+    if [ "$OSUSER" != "root" ]; then
+	echo "must be executed as 'root' or with 'sudo'"
+	exit 1
+    fi
+}
  
 function log_job_message
 {    
@@ -201,13 +213,13 @@ function install_agent
 		shift; break;;
 	esac
     done    
-
-    if [ -z "$CMON_PASSWORD" ]; then
+    if [ -z "$CLUSTER_ID" ]; then
 	echo "s9s_galera "
 	exit 1
     fi
-    
-    if [ -z "$CLUSTER_ID" ]; then
+    init 
+
+    if [ -z "$CMON_PASSWORD" ]; then
 	echo "s9s_galera "
 	exit 1
     fi
@@ -243,6 +255,7 @@ function load_opts
     SUDO=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SUDO' AND cid=$CLUSTER_ID" 2>/dev/null`    
     OS_USER_HOME=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS_USER_HOME' AND cid=$CLUSTER_ID" 2>/dev/null`
     TMPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='STAGING_DIR' AND cid=$CLUSTER_ID"`
+    HTTP_PROXY=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='HTTP_PROXY' AND cid=$CLUSTER_ID"`
     S9S_TMPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='STAGING_DIR' AND cid=$CLUSTER_ID"`
     VENDOR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='VENDOR' AND cid=$CLUSTER_ID" 2>/dev/null`
     DATADIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon.cluster_config where variable='datadir' and cid=1 order by id asc limit 1" 2>/dev/null`
@@ -311,6 +324,12 @@ function install_mysql
 		shift; break;;
 	esac
     done    
+    if [ -z "$CLUSTER_ID" ]; then
+	echo "s9s_galera "
+	exit 1
+    fi
+    init
+
     if [ -z "$CMON_PASSWORD" ]; then
 	echo "s9s_galera "
 	exit 1
@@ -318,11 +337,6 @@ function install_mysql
 
     if [ -z "$DONOR" ]; then
 	echo "donor -d not set "
-	exit 1
-    fi
-    
-    if [ -z "$CLUSTER_ID" ]; then
-	echo "s9s_galera "
 	exit 1
     fi
     
@@ -374,18 +388,18 @@ function stop_cluster
 		esac
     done    
    
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --stop-cluster -i <clusterid>  missing"
+      exit 1
+    fi
+    init
+
 
 
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --stop-cluster -p  missing"
       exit 1
     fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --stop-cluster -i <clusterid>  missing"
-      exit 1
-    fi
-
 
     
     case $CLUSTER_TYPE in
@@ -421,7 +435,7 @@ function stop_cluster
 
 function install_notifycc
 {
-    KILLSIG=15
+    KILLSIG=15    
     args=`getopt p:u:P:h:t:N:j:i:f $*`
     set -- $args
     for i
@@ -436,6 +450,9 @@ function install_notifycc
             -j)
 		jobid="$2"; shift;
 		shift;;
+            -h)
+		XHOSTNAME="$2"; shift;
+		shift;;
             -f)
 		KILLSIG="9"; shift;
 		shift;;
@@ -444,20 +461,18 @@ function install_notifycc
 		esac
     done    
    
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --install-notifycc -i <clusterid>  missing"
+      exit 1
+    fi
+    init
 
-
+   
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --install-notifycc -p  missing"
       exit 1
     fi
 
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --install-notifycc -i <clusterid>  missing"
-      exit 1
-    fi
-
-
-    
     case $CLUSTER_TYPE in
 	galera)
 	    ;;
@@ -466,15 +481,18 @@ function install_notifycc
 	    exit 1;	           	     
     esac
     load_opts $CLUSTER_ID 
-    
-    QUERY="select group_concat(hostname SEPARATOR ' ') from ${CMON_DB_DB}.mysql_server where cid=${CLUSTER_ID}"
-    SERVER_LIST=`$MYSQL_BIN $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD  --host=127.0.0.1 --port=$CMON_DB_PORT -N -Bse "$QUERY"  2>/dev/null`
-    if [ -z "$OS" ]; then
-	if [ `hash /usr/sbin/update-rc.d 2>/dev/null`  ]; then
-	    OS="redhat"
-	else
-	    OS="debian"
-	fi	
+    if [ -z "$XHOSTNAME" ]; then
+	QUERY="select group_concat(hostname SEPARATOR ' ') from ${CMON_DB_DB}.mysql_server where cid=${CLUSTER_ID}"
+	SERVER_LIST=`$MYSQL_BIN $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD  --host=127.0.0.1 --port=$CMON_DB_PORT -N -Bse "$QUERY"  2>/dev/null`
+	if [ -z "$OS" ]; then
+	    if [ `hash /usr/sbin/update-rc.d 2>/dev/null`  ]; then
+		OS="redhat"
+	    else
+		OS="debian"
+	    fi	
+	fi
+    else
+	SERVER_LIST="$XHOSTNAME"
     fi
 
 
@@ -552,6 +570,10 @@ case $STATUS in
 	Joined)
 	   STATUS_VAL=6
            ;;
+        Undefined)
+           STATUS='Initialized'
+	   STATUS_VAL=0
+           ;;
         *)
            STATUS_VAL=0
            ;;
@@ -560,16 +582,16 @@ esac
 if [ -n "$MEMBERS" ]; then
   CLU_SZ=$(echo $MEMBERS | sed 's/, /_ /g' | tr ',' '\n' | wc -l)
 else
-  CLU_SZ=""
+  CLU_SZ="0"
 fi
 
 if [ -n "$MYSQL_HOSTNAME" ]; then
-    QUERY="BEGIN; UPDATE galera_status SET value=$STATUS_VAL, value_txt='$STATUS', report_ts=NOW()  WHERE cid=$CLUSTER_ID AND hostid=$HID AND  var='WSREP_LOCAL_STATE'"
+    QUERY="BEGIN;  REPLACE INTO galera_status SET value=$STATUS_VAL, value_txt='$STATUS', report_ts=NOW(), cid=$CLUSTER_ID , hostid=$HID , var='WSREP_LOCAL_STATE'"
     
     if [ -n "$CLU_SZ" ]; then
-       QUERY="$QUERY; UPDATE galera_status SET value=$CLU_SZ, value_txt='$CLU_SZ', report_ts=NOW()  WHERE cid=$CLUSTER_ID AND hostid=$HID AND var='WSREP_CLUSTER_SIZE'"
+       QUERY="$QUERY; REPLACE INTO galera_status SET value=$CLU_SZ, value_txt='$CLU_SZ', report_ts=NOW(), cid=$CLUSTER_ID , hostid=$HID , var='WSREP_CLUSTER_SIZE'"
     fi
-       QUERY="$QUERY; UPDATE galera_status SET value=0, value_txt='$STATUS', report_ts=NOW()  WHERE cid=$CLUSTER_ID AND hostid=$HID AND var='WSREP_LOCAL_STATE_COMMENT';COMMIT"
+       QUERY="$QUERY; REPLACE INTO galera_status SET value=0, value_txt='$STATUS', report_ts=NOW() , cid=$CLUSTER_ID , hostid=$HID , var='WSREP_LOCAL_STATE_COMMENT';COMMIT"
     $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/dev/null
 fi
 EOF
@@ -585,6 +607,7 @@ EOF
 	    remote_cmd $HNAME "chown mysql:mysql /usr/bin//wsrep_notify_cc"
 	    remote_cmd $HNAME "chmod u+x /usr/bin/wsrep_notify_cc"
 	    remote_cmd $HNAME "chmod 755 /usr/bin/wsrep_notify_cc"
+	    remote_cmd $HNAME "chown mysql.mysql /etc/cmon.cnf"
 	    remote_cmd $HNAME "sed -i.bak 's#.*wsrep_notify_cmd=.*#wsrep_notify_cmd=/usr/bin/wsrep_notify_cc#g' $CONFIGDIR/my.cnf"
 	done
     fi
@@ -621,14 +644,13 @@ function stop_node
 		esac
     done    
    
-
-    if [ -z "$CMON_PASSWORD" ]; then
-      echo "s9s_galera --create -p  missing"
-      exit 1
-    fi
-
     if [ -z "$CLUSTER_ID" ]; then
       echo "s9s_galera --stop-node -i <clusterid>  missing"
+      exit 1
+    fi
+    init
+    if [ -z "$CMON_PASSWORD" ]; then
+      echo "s9s_galera --create -p  missing"
       exit 1
     fi
 
@@ -692,7 +714,7 @@ function stop_node_int
 		break
 	    fi
 	    remote_cmd_nofail $xHNAME "killall -${KILLSIG} mysqld mysqld_safe"
-	    remote_cmd_nofail $xHNAME "killall -9 nc xtrabackup innobackupex"
+	    remote_cmd_nofail $xHNAME "killall -9 nc socat xtrabackup innobackupex"
 	done
     fi
 
@@ -723,7 +745,9 @@ function start_node_donor
 	echo "Node $xHNAME is already started"
 	exit 1
     fi
-    ###remote_cmd3 $xHNAME "nohup nice /etc/init.d/mysql start --wsrep-cluster-address=gcomm:// > /dev/null 2>&1"    
+    ###remote_cmd3 $xHNAME "nohup nice /etc/init.d/mysql start --wsrep-cluster-address=gcomm:// > /dev/null 2>&1"   
+##    remote_cmd $XHNAME "sed -i.bak 's/^wsrep_cluster_address=.*/\#wsrep_cluster_address=gcomm:\/\//g' $CONFIGDIR/my.cnf" 
+ ##   remote_cmd $XHNAME "sed -i.bak 's/^\#wsrep_cluster_address=.*/wsrep_cluster_address=gcomm:\/\//g' $CONFIGDIR/my.cnf"
     remote_cmd3 $xHNAME "nohup $MYSQL_BASEDIR/bin/mysqld_safe --wsrep-cluster-address=gcomm://  >/dev/null 2>&1"    
     sleep 2
     STATE=$(check_node_up $xHNAME)
@@ -772,15 +796,14 @@ function install_garbd
 		shift; break;;
 	esac
     done    
-    
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --install-garbd -i <cluster id> missing"
+      exit 1
+    fi
+    init     
 
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --install-garbd -p  missing"
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --install-garbd -i <cluster id> missing"
       exit 1
     fi
 
@@ -848,9 +871,9 @@ function install_garbd
 		remote_cmd $XHOSTNAME "apt-get update"
 		remote_cmd_nofail $XHOSTNAME "apt-get -y install  libssl0.9.8  wget rsync psmisc"
 		remote_cmd_nofail $XHOSTNAME "sed -i.bak '/repo.percona.com/d'  /etc/apt/sources.list"
-		wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona
+		$HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona
 		if [ $? -ne 0 ]; then
-		    log_job_message "Failed: wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona" 1
+		    log_job_message "Failed: $HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona" 1
 		    log_job 'FAILED' 'install garbd failed' 1
 		    exit 1
 		fi
@@ -1002,15 +1025,14 @@ function remove_garbd
 		shift; break;;
 	esac
     done    
-    
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --remove-garbd -i <cluster id> missing"
+      exit 1
+    fi
+    init       
 
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --remove-garbd -p  missing"
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --remove-garbd -i <cluster id> missing"
       exit 1
     fi
 
@@ -1206,18 +1228,18 @@ function reinit_cluster
 		shift; break;;
 	esac
     done    
+
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --reinit-cluster -i <cluster id> missing"
+      exit 1
+    fi
+    init
     
 
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --reinit-cluster -p  missing"
       exit 1
     fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --reinit-cluster -i <cluster id> missing"
-      exit 1
-    fi
-
     if [ -z "$DONOR_HOSTNAME" ]; then
       echo "s9s_galera --reinit-cluster -d <donor_addres -donor node is missing, specify one server address part of the cluster> missing"
       exit 1
@@ -1339,15 +1361,15 @@ function make_primary
 		shift; break;;
 	esac
     done    
-    
-
-    if [ -z "$CMON_PASSWORD" ]; then
-      echo "s9s_galera --make-primary -p  missing"
-      exit 1
-    fi
 
     if [ -z "$CLUSTER_ID" ]; then
       echo "s9s_galera --make-primary -i <cluster id> missing"
+      exit 1
+    fi
+    init    
+
+    if [ -z "$CMON_PASSWORD" ]; then
+      echo "s9s_galera --make-primary -p  missing"
       exit 1
     fi
 
@@ -1435,14 +1457,14 @@ function start_cluster
 	esac
     done    
     
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --start-cluster -i <cluster id> missing"
+      exit 1
+    fi
+    init
 
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --start-cluster -p  missing"
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --start-cluster -i <cluster id> missing"
       exit 1
     fi
 
@@ -1534,18 +1556,16 @@ function status_cluster
 		shift; break;;
 	esac
     done    
-    
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --status -i <cluster id> missing"
+      exit 1
+    fi
+    init    
 
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --status -p  missing"
       exit 1
     fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --status -i <cluster id> missing"
-      exit 1
-    fi
-
 
 ##    CMON_DB_DB="cmon_${CLUSTER_ID}"
     
@@ -1629,15 +1649,15 @@ function start_node
 		shift; break;;
 	esac
     done    
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_galera --start-node -i <cluster id> missing"
+      exit 1
+    fi
+    init
     
 
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_galera --start-node -p  missing"
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --start-node -i <cluster id> missing"
       exit 1
     fi
 
diff --git a/cluster/s9s_haproxy b/cluster/s9s_haproxy
--- a/cluster/s9s_haproxy
+++ b/cluster/s9s_haproxy
@@ -45,14 +45,29 @@ function init
     HAPROXY_MYSQL_LISTEN_PORT="33306"
     HAPROXY_OPTS="-f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -st \$(cat /var/run/haproxy.pid)"
     LB_ADMIN_USER='admin'
-    LB_ADMIN_PORT="9600"
+    LB_ADMIN_PORT="9800"
     LB_ADMIN_PASSWORD='admin'
+    HAPROXY_LOG='/tmp/s9s_haproxy.log'
+    HAPROXY_LOG2='/tmp/s9s_haproxy2.log'
 
     if [ "$OSUSER" != "root" ]; then
 	echo "must be executed as 'root' or with 'sudo'"
 	exit 1
     fi
+    echo "" > $HAPROXY_LOG
+    echo "" > $HAPROXY_LOG2
 }
+
+function write_email
+{
+  SUBJECT=$1
+  MSG=$2
+  cat $HAPROXY_LOG | sed  -e "s/'/\\\'/g" -e 's/"/\\"/g' > /tmp/s9s_haproxy_log_escaped
+  MSG="$MSG \nBackup log follows:\n `cat /tmp/s9s_haproxy_log_escaped`" 
+  QUERY="INSERT INTO simple_email(cid,subject,message) VALUES($CLUSTER_ID, \"$SUBJECT\", \"$MSG\")"
+  $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log
+}
+
 
 
 function log_job_message
@@ -65,12 +80,25 @@ function log_job_message
     QUERY="INSERT INTO cmon_job_message(cid, jobid,message,exit_code,report_ts) VALUES($CLUSTER_ID,$JOBID,\"$MSG\",$EXIT_CODE,now())"
     if [ $JOBID -ne 0 ]; then 
 	$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log
+	if [ $EXIT_CODE -ne 0 ]; then
+	    echo "Failed: $MSG" >> $HAPROXY_LOG
+	else
+	    echo "$MSG" >> $HAPROXY_LOG
+	fi
     else
 	if [ $EXIT_CODE -ne 0 ]; then
-	    echo ""
-	    echo "Failed: $MSG"
+	    echo "Failed: $MSG" >> $HAPROXY_LOG
+	else
+	    echo "$MSG" >> $HAPROXY_LOG
 	fi
     fi
+}
+
+function log_message
+{    
+    MSG=$1
+    echo "$MSG" >> $HAPROXY_LOG2
+    echo "$MSG"
 }
 
 function log_job
@@ -121,7 +149,7 @@ userlist STATSUSERS
         user ADMIN_USER insecure-password ADMIN_PASSWORD
         user stats insecure-password PASSWORD
 
-listen admin_page 0.0.0.0:9600
+listen admin_page 0.0.0.0:ADMIN_PORT
         mode http
         stats enable
         stats refresh 60s
@@ -146,7 +174,7 @@ vrrp_script chk_haproxy {
 }
  
 vrrp_instance VI_1 {
-   interface eth0                # interface to monitor
+   interface ETHINTERFACE                # interface to monitor
    state MASTER
    virtual_router_id 51          # Assign one ID for this route
    priority PRIORITY                   # 101 on master, 100 on backup
@@ -161,6 +189,7 @@ EOF
 
 sed -i.bak "s#PRIORITY#$3#g" $TMPDIR/keepalived.conf.$1
 sed -i.bak "s#VIRTUAL_IP#$2#g" $TMPDIR/keepalived.conf.$1
+sed -i.bak "s#ETHINTERFACE#$4#g" $TMPDIR/keepalived.conf.$1
 }	
 
 
@@ -201,7 +230,7 @@ userlist STATSUSERS
         user ADMIN_USER insecure-password ADMIN_PASSWORD
         user stats insecure-password USER_PASSWORD
 
-listen admin_page 0.0.0.0:9600
+listen admin_page 0.0.0.0:ADMIN_PORT
         mode http
         stats enable
         stats refresh 60s
@@ -373,6 +402,7 @@ function test_ssh()
        echo "   http://support.severalnines.com/tickets/new"
        log_job_message 'Could not ssh to remote host, you must setup shared keys to the host first.' 1
        log_job 'FAILED' 's9s_haproxy failed' 1
+       write_email 's9s_haproxy installation failed' 'Could not ssh to remote host, you must setup shared keys to the host first.' 
        exit 1
        return 1
   fi
@@ -445,7 +475,7 @@ function remote_cmd()
 {
    desthost=$1
    xcommand=$2
-   MAX_RETRIES=1
+   MAX_RETRIES=3
    printf "%-4s: Executing '%s' " "$desthost" "$xcommand"
    retry=0
    while [ $retry -lt $MAX_RETRIES ]; 
@@ -463,6 +493,7 @@ function remote_cmd()
    done
    log_job_message "FAILED: ${desthost} : ${xcommand}" 1
    log_job 'FAILED' 's9s_haproxy failed' 1
+   write_email 's9s_haproxy installation failed' "FAILED: ${desthost} : ${xcommand}"
    printf "\033[31m[failed]\033[0m\n"
    echo $x
    echo 'The following command failed:'
@@ -486,6 +517,7 @@ function remote_cmd3()
        printf "\033[31m[failed]\033[0m\n"
        log_job_message "FAILED: ${desthost}@${xcommand}" 1
        log_job 'FAILED' 's9s_haproxy failed' 1
+       write_email 's9s_haproxy installation failed' "FAILED: ${desthost} : ${xcommand}"
        exit 1
    fi
 }
@@ -613,6 +645,7 @@ function load_opts
     SSH_OPTSX=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SSH_OPTS' AND cid=$CLUSTER_ID"`
     SUDO=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SUDO' AND cid=$CLUSTER_ID"`
     TMPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='STAGING_DIR' AND cid=$CLUSTER_ID"`
+    HTTP_PROXY=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='HTTP_PROXY' AND cid=$CLUSTER_ID"`
     S9S_TMPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='STAGING_DIR' AND cid=$CLUSTER_ID"`
     VENDOR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='VENDOR' AND cid=$CLUSTER_ID" 2>/dev/null`
     OS_USER_HOME=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS_USER_HOME' AND cid=$CLUSTER_ID"`
@@ -630,11 +663,13 @@ function load_opts
     if [ -z "$MYSQL_PORT" ]; then 
         log_job_message "MYSQL_PORT not set in Cluster Settings"
 	log_job 'FAILED' 's9s_haproxy failed' 1
+	write_email 's9s_haproxy installation failed' "MYSQL_PORT not set in Cluster Settings"
         exit 1
     fi
 
     if [ -z "$SSH_USER" ]; then 
         log_job_message "SSH_USER not set in Cluster Settings"
+	write_email 's9s_haproxy installation failed' "SSH_USER not set in Cluster Settings"
 	log_job 'FAILED' 's9s_haproxy failed' 1
         exit 1
     fi
@@ -646,6 +681,7 @@ function load_opts
     
     if [ -z "$OS" ]; then 
         log_job_message "OS not set in Cluster Settings"
+	write_email 's9s_haproxy installation failed' "OS not set in Cluster Settings"
 	log_job 'FAILED' 's9s_haproxy failed' 1
         exit 1
     fi
@@ -812,17 +848,17 @@ function install_haproxy
     log_job 'RUNNING' 'Job is running' 0
     case $OS in
         rhel|redhat)
-            PKG_MGR="yum -y install "
-            PKG_MGR2="yum -y install "
+            PKG_MGR="$HTTP_PROXY yum -y install "
+            PKG_MGR2="$HTTP_PROXY yum -y install "
             PHP_CURL="php-curl"
 	    BUILD="gcc make"
             CENTOS=$(remote_cmd_getreply $LB_HOSTNAME 'test -f /etc/redhat-release && cat /etc/redhat-release  | grep -i centos |grep "6"')
 	    if [ -z "$BUILD_FROM_SRC" ]; then
 		if [ -n "$CENTOS" ]; then
-		    remote_cmd $LB_HOSTNAME "yum -y install centos-release-cr"
+		    remote_cmd $LB_HOSTNAME "$HTTP_PROXY yum -y install centos-release-cr"
 		    remote_cmd_nofail $LB_HOSTNAME "sed  -i.bak  's/enabled=1/enabled=0/g' /etc/yum.repos.d/CentOS-CR.repo"
-		    PKG_MGR2="yum -y --enablerepo=cr install "
-		    PKG_MGR="yum -y install "
+		    PKG_MGR2="$HTTP_PROXY yum -y --enablerepo=cr install "
+		    PKG_MGR="$HTTP_PROXY yum -y install "
 		    PHP_CURL="php-curl"
 		    OS=rhel
 		else
@@ -836,8 +872,8 @@ function install_haproxy
 	    OS=centos6
 	    ;;	
         debian|ubuntu)
-            PKG_MGR="apt-get install -y "
-            PKG_MGR2="apt-get install -y "
+            PKG_MGR="$HTTP_PROXY apt-get install -y "
+            PKG_MGR2="$HTTP_PROXY apt-get install -y "
             PHP_CURL="php5-curl"
 	    BUILD="gcc make"
             OS=debian
@@ -874,11 +910,12 @@ function install_haproxy
     if [ -z "$hostnames" ]; then
        echo "No hostnames found."
        log_job 'FAILED' 's9s_haproxy failed' 1
+       write_email 's9s_haproxy installation failed' "No hostnames found"
        exit 1
     fi
 
     if [ "$hostnames" = "NULL" ]; then
-       echo "No hostnames found."
+       write_email 's9s_haproxy installation failed' "No hostnames found"
        log_job 'FAILED' 's9s_haproxy failed' 1
        exit 1
     fi
@@ -921,10 +958,10 @@ function install_haproxy
     remote_cmd $LB_HOSTNAME "$PKG_MGR wget"
 
     if [ $OS = "rhel" ] || [ $OS = "centos6" ]; then
-	remote_cmd_nofail $LB_HOSTNAME "wget  --no-check-certificate --tries=5 -O ${S9S_TMPDIR}/epel-release-6-8.noarch.rpm  http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
+	remote_cmd_nofail $LB_HOSTNAME "$HTTP_PROXY wget  --no-check-certificate --tries=5 -O ${S9S_TMPDIR}/epel-release-6-8.noarch.rpm  http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
 	remote_cmd_nofail $LB_HOSTNAME "rpm -Uvh --force ${S9S_TMPDIR}/epel-release-6-8.noarch.rpm"
 	remote_cmd_nofail $LB_HOSTNAME "rpm --import http://apt.sw.be/RPM-GPG-KEY.dag.txt"
-	remote_cmd_nofail $LB_HOSTNAME "rpm -Uvh http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm"
+	remote_cmd_nofail $LB_HOSTNAME "$HTTP_PROXY rpm -Uvh http://packages.sw.be/rpmforge-release/rpmforge-release-0.5.2-2.el6.rf.x86_64.rpm"
     fi
     remote_cmd_nofail $LB_HOSTNAME "$PKG_MGR $PHP_CURL"
     if [ -n "$BUILD_FROM_SRC" ]; then
@@ -933,12 +970,13 @@ function install_haproxy
 	    if [ ! -f $BUILD_FROM_SRC_FILE ]; then
 		echo "$BUILD_FROM_SRC_FILE could not be found"
 		log_job 'FAILED' 's9s_haproxy failed' 1
+		write_email 's9s_haproxy installation failed' "$BUILD_FROM_SRC_FILE could not be found"
 		exit 1
 	    fi
 	    HAPROXY_SRC=`basename $BUILD_FROM_SRC_FILE`
 	    remote_copy $BUILD_FROM_SRC_FILE $LB_HOSTNAME /tmp/
 	else
-	    remote_cmd $LB_HOSTNAME "sh -c 'wget -O/tmp/${HAPROXY_SRC}  http://haproxy.1wt.eu/download/1.4/src/${HAPROXY_SRC}'"	 	
+	    remote_cmd $LB_HOSTNAME "sh -c '$HTTP_PROXY wget -O/tmp/${HAPROXY_SRC}  http://haproxy.1wt.eu/download/1.4/src/${HAPROXY_SRC}'"	 	
 	    
 	fi
 	remote_cmd $LB_HOSTNAME "$PKG_MGR $BUILD"
@@ -1000,6 +1038,7 @@ function install_haproxy
             echo ""
             cat /tmp/err.log           
 	    log_job 'FAILED' 's9s_haproxy failed' 1
+	    write_email 's9s_haproxy installation failed' "Query failed: $QUERY"
 	    exit 1
         fi
     fi
@@ -1012,27 +1051,37 @@ function install_haproxy
     QUERY="REPLACE INTO ext_proc (cid, hostname,bin, opts,cmd, proc_name, port) VALUES($CLUSTER_ID, '$LB_HOSTNAME','/usr/sbin/haproxy', \"${HAPROXY_OPTS}\", \"/usr/sbin/haproxy ${HAPROXY_OPTS}\",'haproxy', $LB_ADMIN_PORT)"
     $MYSQL_BIN -B -N  -ucmon -p$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST  --port=${CMON_DB_PORT} -e "$QUERY" 2>&1 >/tmp/err.log
     if [  $? -ne 0 ]; then
-      log_job_message "Query failed: $QUERY"
-       echo ""
-       cat /tmp/err.log
-       log_job 'FAILED' 's9s_haproxy failed' 1
-       exit 1
+	log_job_message "Query failed: $QUERY"
+	echo ""
+	cat /tmp/err.log
+	log_job 'FAILED' 's9s_haproxy failed' 1
+	write_email 's9s_haproxy installation failed' "Query failed: $QUERY"
+	exit 1
     fi
 
 
-    echo ""
-    echo "** Reboot is recommended of $LB_HOSTNAME for network settings to take effect! **"
-    echo ""
-    echo "FIREWALL: To access Haproxy within ClusterControl, you should allow the clustercontrol server to connect to $x on port 9600, and HaProxy must be able to communicate on port 9200 with the MySQL Servers."
-    echo "**The admin interface is on http://${LB_HOSTNAME}:9600 **"
-    echo ""
-    echo "**The admin interface is on http://${LB_HOSTNAME}:9600 **"
-    echo "**Login with ${LB_ADMIN_USER}/${LB_ADMIN_PASSWORD}"
-    echo "**HAProxy listens on ${LB_HOSTNAME}:${HAPROXY_MYSQL_LISTEN_PORT} for mysql connections."
-    echo "**Don't forget to GRANT ${LB_HOSTNAME} on your mysql servers:"
-    echo "GRANT <privs> ON <db>.* TO '<user>'@'${LB_HOSTNAME}' IDENTIFIED BY '<password>'"
-    echo ""
+    log_message ""  
+    log_message  "** Reboot is recommended of $LB_HOSTNAME for network settings to take effect! **"
+    log_message  ""
+    log_message  "FIREWALL: To access HAproxy within ClusterControl, you should allow the clustercontrol server to connect to $LB_HOSTNAME on port ${LB_ADMIN_PORT}, and HAProxy must be able to communicate on port 9200 and 3306 with the MySQL Servers."
+    log_message  ""
+    log_message  "**The admin interface is on http://${LB_HOSTNAME}:${LB_ADMIN_PORT} **"
+    log_message  "  Login with ${LB_ADMIN_USER}/${LB_ADMIN_PASSWORD}"
+    log_message  ""
+    log_message  "** Connect from applications: "
+    log_message  "  HAProxy listens on ${LB_HOSTNAME}:${HAPROXY_MYSQL_LISTEN_PORT} for mysql connections."
+    log_message  ""
+    log_message  " ** Don't forget to GRANT ${LB_HOSTNAME} on your mysql servers:"
+    log_message  "  GRANT <privs> ON <db>.* TO '<user>'@'${LB_HOSTNAME}' IDENTIFIED BY '<password>'"
+    log_message  ""
+    
+    cat $HAPROXY_LOG2  > /tmp/s9s_result
+    cat $HAPROXY_LOG  >> /tmp/s9s_result
+    mv /tmp/s9s_result  $HAPROXY_LOG 
+    rm $HAPROXY_LOG2
+    
     log_job 'FINISHED' 's9s_haproxy --install completed' 0
+    write_email 's9s_haproxy installation completed' "s9s_haproxy --install completed"
     exit 0
 
 }
@@ -1042,7 +1091,7 @@ function install_keepalived
 {
     LB_NODE_LIST=""
     KEEPALIVED_NAME="keepalived"
-    args=`getopt p:P:h:i:N:n:j:sf:c:x:y:v: $*`
+    args=`getopt p:P:h:i:N:n:j:sf:c:x:y:v:I: $*`
     set -- $args
     for i
     do
@@ -1055,6 +1104,9 @@ function install_keepalived
                 shift;;
             -i)
                 CLUSTER_ID="$2"; shift;
+                shift;;
+            -I)
+                ETHINTERFACE="$2"; shift;
                 shift;;
             -x)
                 LB_HOSTNAME1="$2"; shift;
@@ -1087,19 +1139,26 @@ function install_keepalived
       exit 1
     fi
 
+    if [ -z "$ETHINTERFACE" ]; then
+	ETHINTERFACE="eth0"
+    fi
+
     if [ -z "$LB_HOSTNAME1" ]; then
         log_job_message "s9s_haproxy --install-ka  -x <loadbalancer host> missing" 1
+	write_email 's9s_haproxy keepalived installation failed' "s9s_haproxy --install-ka  -x <loadbalancer host> missing" 
 	log_job 'FAILED' 's9s_haproxy failed' 1
         exit 1
     fi
 
     if [ -z "$LB_HOSTNAME2" ]; then
+	write_email 's9s_haproxy keepalived installation failed' "s9s_haproxy --install-ka  -y <loadbalancer host> missing" 
         log_job_message "s9s_haproxy --install-ka  -y <loadbalancer host> missing" 1
 	log_job 'FAILED' 's9s_haproxy failed' 1
         exit 1
     fi
 
     if [ -z "$VIRTUAL_IP" ]; then
+	write_email 's9s_haproxy keepalived installation failed' "s9s_haproxy --install-ka  -v <virtual ip> missing" 
         log_job_message "s9s_haproxy --install-ka  -v <virtual ip> missing" 1
 	log_job 'FAILED' 's9s_haproxy failed' 1
         exit 1
@@ -1113,11 +1172,11 @@ function install_keepalived
 
     log_job 'RUNNING' 'Job is running' 1
     load_opts $CLUSTER_ID
-    prepare_keepalived $LB_HOSTNAME1 $VIRTUAL_IP 101
-    prepare_keepalived $LB_HOSTNAME2 $VIRTUAL_IP 100
+    prepare_keepalived $LB_HOSTNAME1 $VIRTUAL_IP 101 $ETHINTERFACE
+    prepare_keepalived $LB_HOSTNAME2 $VIRTUAL_IP 100 $ETHINTERFACE
     case $OS in
         rhel|redhat)
-            PKG_MGR="yum -y install "
+            PKG_MGR="$HTTP_PROXY yum -y install "
             PHP_CURL="php-curl"
 	    OS=rhel
             ;;
@@ -1125,7 +1184,7 @@ function install_keepalived
 	    OS=centos6
 	    ;;	
         debian|ubuntu)
-            PKG_MGR="apt-get install -y "	    
+            PKG_MGR="$HTTP_PROXY apt-get install -y "	    
             OS=debian
             ;;
         *)
@@ -1136,14 +1195,14 @@ function install_keepalived
 
     case $CLUSTER_TYPE in
         galera)
-        ;;
+            ;;
         mysqlcluster)
-        ;;
+            ;;
         *)
-        log_job_message "Cluster $CLUSTER_TYPE not supported" 1
-	log_job 'FAILED' 's9s_haproxy failed' 1
-	exit 1
-        ;;
+            log_job_message "Cluster $CLUSTER_TYPE not supported" 1
+	    log_job 'FAILED' 's9s_haproxy failed' 1
+	    exit 1
+            ;;
     esac
 
     for LB_HOSTNAME in $LB_HOSTNAME1 $LB_HOSTNAME2
@@ -1178,6 +1237,7 @@ function install_keepalived
 	    log_job_message "Query failed: $QUERY"
 	    echo ""
 	    cat /tmp/err.log
+	    write_email 's9s_haproxy keepalived installation failed' "s9s_haproxy --install-ka query failed: $QUERY"
 	    log_job 'FAILED' 's9s_haproxy --install-ka failed' 1
 	    exit 1
 	fi
@@ -1199,6 +1259,7 @@ function install_keepalived
     done
     log_job_message "Access your cluster on $VIRTUAL_IP and the listening port of HAProxy (33306 default)" 0
     log_job 'FINISHED' 's9s_haproxy --install-ka completed' 0
+    write_email 's9s_haproxy keepalived installation completed' "Access your cluster on $VIRTUAL_IP and the listening port of HAProxy (33306 default)" 
     exit 0
 
 }
@@ -1281,7 +1342,7 @@ function delete_keepalived
     load_opts $CLUSTER_ID
     case $OS in
         rhel|redhat)
-            PKG_MGR="yum -y remove "
+            PKG_MGR="$HTTP_PROXY yum -y remove "
             PHP_CURL="php-curl"
 	    OS=rhel
             ;;
@@ -1289,7 +1350,7 @@ function delete_keepalived
 	    OS=centos6
 	    ;;	
         debian|ubuntu)
-            PKG_MGR="apt-get remove -y "	    
+            PKG_MGR="$HTTP_PROXY apt-get remove -y "	    
             OS=debian
             ;;
         *)
@@ -1412,11 +1473,11 @@ function delete_haproxy
 
     case $OS in
         rhel|redhat|centos6)
-            PKG_MGR="yum -y remove "
+            PKG_MGR="$HTTP_PROXY yum -y remove "
             OS=rhel
             ;;
         debian|ubuntu)
-            PKG_MGR="apt-get -y remove "
+            PKG_MGR="$HTTP_PROXY apt-get -y remove "
             OS=debian
             ;;
         *)
@@ -1536,12 +1597,12 @@ function remove_node
 
     case $OS in
         rhel|redhat)
-            PKG_MGR="yum install -y "
+            PKG_MGR="$HTTP_PROXY yum install -y "
             PHP_CURL="php-curl"
             OS=rhel
             ;;
         debian|ubuntu)
-            PKG_MGR="apt-get install -y "
+            PKG_MGR="$HTTP_PROXY apt-get install -y "
             PHP_CURL="php5-curl"
             OS=debian
             ;;
@@ -1644,12 +1705,12 @@ function add_node
 
     case $OS in
         rhel|redhat)
-            PKG_MGR="yum install -y "
+            PKG_MGR="$HTTP_PROXY yum install -y "
             PHP_CURL="php-curl"
             OS=rhel
             ;;
         debian|ubuntu)
-            PKG_MGR="apt-get install -y "
+            PKG_MGR="$HTTP_PROXY apt-get install -y "
             PHP_CURL="php5-curl"
             OS=debian
             ;;
diff --git a/cluster/s9s_mongodb_admin b/cluster/s9s_mongodb_admin
--- a/cluster/s9s_mongodb_admin
+++ b/cluster/s9s_mongodb_admin
@@ -3,35 +3,52 @@
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
 
-
-if [ ! -e /etc/cmon.cnf ]  ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
-else
-    source /etc/cmon.cnf
-fi
-CID=$cluster_id
-CMON_USER=cmon
-CMON_DB_PORT=$mysql_port
-CMON_PASSWORD=$mysql_password
-CMON_DB_HOST=$mysql_hostname
-CMON_DB_DB=cmon
-MYSQL_BIN=$mysql_basedir/bin//mysql
-MYSQL_BIN2=$mysql_bindir/mysql
-CLUSTER_STATE_TIMEOUT=3600
-START_BALANCER_TIMEOUT=3600
-BACKUP_LOGFILE="/tmp/s9s_mongodb_backup.log"
 JOBID=0
+function init
+{    
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`    
+    FILES="$FILES $FILES2"
+    configfile=""
+    for f in $FILES 
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `	
+	if [ $? -eq 0 ]; then 
+	    source $f
+            configfile=$f
+	fi
+    done
+
+    if [ -z "$configfile" ]; then
+	echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+	exit 1
+    fi
+   
+    source $configfile;
+
+
+    CID=$cluster_id
+    CMON_USER=cmon
+    CMON_DB_PORT=$mysql_port
+    CMON_PASSWORD=$mysql_password
+    CMON_DB_HOST=$mysql_hostname
+    CMON_DB_DB=cmon
+    MYSQL_BIN=$mysql_basedir/bin//mysql
+    MYSQL_BIN2=$mysql_bindir/mysql
+    CLUSTER_STATE_TIMEOUT=3600
+    START_BALANCER_TIMEOUT=3600
+    BACKUP_LOGFILE="/tmp/s9s_mongodb_backup.log"
 ### NO MODS BELOW UNLESS YOU KNOW WHAT YOU DO:
-
-export LC_ALL=C
-OSUSER=$USER
-
-
-if [ "$OSUSER" != "root" ]; then
-    echo "must be executed as 'root' or with 'sudo'"
-    exit 1
-fi
+    
+    export LC_ALL=C
+    OSUSER=$USER
+    
+    
+    if [ "$OSUSER" != "root" ]; then
+	echo "must be executed as 'root' or with 'sudo'"
+	exit 1
+    fi
+}
 
 if ! test -f $MYSQL_BIN; then
     if ! test -f $MYSQL_BIN2; then
@@ -181,6 +198,16 @@ function remote_cmd()
    exit 1
 }
 
+function write_email
+{
+  SUBJECT=$1
+  MSG=$2
+  cat $BACKUP_LOGFILE | sed  -e "s/'/\\\'/g" -e 's/"/\\"/g' > /tmp/s9s_backup_log_escaped
+  MSG="$MSG \nBackup log follows:\n `cat /tmp/s9s_backup_log_escaped`" 
+  QUERY="INSERT INTO simple_email(cid,subject,message) VALUES($CLUSTER_ID, \"$SUBJECT\", \"$MSG\")"
+  $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log
+}
+
 
 function load_opts 
 {
@@ -189,6 +216,7 @@ function load_opts
     OS=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS' AND cid=$CLUSTER_ID"`
     CONFIGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='CONFIGDIR' AND cid=$CLUSTER_ID"`
     MYSQL_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MYSQL_PORT' AND cid=$CLUSTER_ID"`
+    HTTP_PROXY=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='HTTP_PROXY' AND cid=$CLUSTER_ID"`
     GALERA_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='GALERA_PORT' AND cid=$CLUSTER_ID"`
     MYSQL_BASEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MYSQL_BASEDIR' AND cid=$CLUSTER_ID"`
     MONGODB_BASEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MONGODB_BASEDIR' AND cid=$CLUSTER_ID"`
@@ -350,7 +378,7 @@ function remove_lockfile
       echo "s9s_mongodb_admin --remove-lockfile -i <cluster id> -h <hostname> -t <configsvr|shardsvr>"
       exit 1
   fi
-
+  init 
   if [ -z "$XHOSTNAME" ]; then
       echo "s9s_mongodb_admin --remove-lockfile -i <cluster id> -h <hostname> -t <configsvr|shardsvr>"
       exit 1
@@ -417,7 +445,7 @@ function add_shard
       echo "s9s_mongodb_admin --add-shard -i <cluster id>"
       exit 1
   fi
-  
+  init 
   if [ -z "$SERVER1" ]; then
       echo "s9s_mongodb_admin --add-shard -a <replica set member address>"
       exit 1
@@ -529,6 +557,7 @@ function upgrade_mongodb
 	echo "s9s_mongodb_admin --upgrade-mongodb -i <cluster id>"
 	exit 1
     fi
+    init
     load_opts $CLUSTER_ID
 
     if [ -z $XHOST ]; then	
@@ -565,11 +594,11 @@ function upgrade_mongodb
 	    10gen)
 		case $OS in
 		    redhat)
-			remote_cmd $xhost "yum -y install mongo-10gen mongo-10gen-server"
+			remote_cmd $xhost "$HTTP_PROXY yum -y install mongo-10gen mongo-10gen-server"
 			;;
 		    debian)
-	   		remote_cmd $xhost "apt-get -q -y update"
-			remote_cmd $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install mongodb-10gen"
+	   		remote_cmd $xhost "$HTTP_PROXY apt-get -q -y update"
+			remote_cmd $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install mongodb-10gen"
 			;;
 		    *)
 			echo "unknown OS"
@@ -616,6 +645,7 @@ function rolling_restart
 	echo "s9s_mongodb_admin --upgrade-mongodb -i <cluster id>"
 	exit 1
     fi
+    init
     load_opts $CLUSTER_ID
     
     echo "Rolling restart"
@@ -706,21 +736,21 @@ function install_mongodb
 		    exit 1
 		    remote_copy 10gen.repo $xhost $S9S_TMPDIR/ 
 		    remote_cmd $xhost "mv $S9S_TMPDIR/10gen.repo /etc/yum.repos.d/"
-		    remote_cmd_nofail $xhost "yum -y remove mongo-10gen mongo-10gen-server"
-		    remote_cmd_nofail $xhost "yum -y install mongo-10gen mongo-10gen-server"
+		    remote_cmd_nofail $xhost "$HTTP_PROXY yum -y remove mongo-10gen mongo-10gen-server"
+		    remote_cmd_nofail $xhost "$HTTP_PROXY yum -y install mongo-10gen mongo-10gen-server"
 		    remote_cmd $xhost  "chown 755 /etc/init.d/mongod"
 		    remote_cmd $xhost  "/sbin/chkconfig --add mongod"
 		    ;;
 		debian)
 		    remote_cmd $xhost "apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10"
 		    remote_cmd_nofail $xhost "touch /etc/init.d/mongodb"
-		    remote_cmd_nofail $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -y remove mongo*"
-		    remote_cmd_nofail $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -y remove mongodb-10gen"
+		    remote_cmd_nofail $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -y remove mongo*"
+		    remote_cmd_nofail $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -y remove mongodb-10gen"
 		    remote_cmd_nofail $xhost "rm -rf /etc/init.d/mongo*"
 		    remote_cmd_nofail $xhost "sed -i.bak '/10gen/d'  /etc/apt/sources.list"
 		    remote_cmd $xhost "/bin/sh -c 'echo \"deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen\" >> /etc/apt/sources.list'"
-		    remote_cmd $xhost "apt-get -q -y update"
-		    remote_cmd $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install mongodb-10gen"
+		    remote_cmd $xhost "$HTTP_PROXY apt-get -q -y update"
+		    remote_cmd $xhost "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive $HTTP_PROXY apt-get -o Dpkg::Options::='--force-confnew' -y -q install mongodb-10gen"
 		    ;;
 		*)
 		    echo "OS is unknonwn / not supported" 		  
@@ -862,11 +892,13 @@ function set_nodestate
 {
     NODEID=$1
     STATE=$2
-    QUERY="UPDATE mongodb_server SET status=$STATE WHERE cid=$CLUSTER_ID AND nodeid=$NODEID"  
-    `$MYSQL_BIN $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=127.0.0.1 --port=$CMON_DB_PORT --auto-vertical-output -Bse "$QUERY"`
-    if [ $? -ne 0 ]; then
-	echo "setting state failed"
-	exit 1
+    if [ -n "$STATE" ]; then
+	QUERY="UPDATE mongodb_server SET status=$STATE WHERE cid=$CLUSTER_ID AND nodeid=$NODEID"  
+	`$MYSQL_BIN $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=127.0.0.1 --port=$CMON_DB_PORT --auto-vertical-output -Bse "$QUERY"`
+	if [ $? -ne 0 ]; then
+	    echo "setting state failed"
+	    exit 1
+	fi
     fi
 }
 
@@ -1095,9 +1127,7 @@ function stop_cluster
       echo "s9s_mongodb_admin --stop-cluster -i <cluster id>"
       exit 1
   fi
-
-
-  echo $CLUSTER_ID
+  init
   load_opts $CLUSTER_ID
   
   echo "Are you sure you want to stop the cluster? Enter YES to stop the cluster."
@@ -1165,9 +1195,7 @@ function start_cluster
       echo "s9s_mongodb_admin --start-cluster -i <cluster id>"
       exit 1
   fi
-
-
-  echo $CLUSTER_ID
+  init
   load_opts $CLUSTER_ID
   
   echo "Are you sure you want to start the cluster? Enter YES to start the cluster."
@@ -1263,9 +1291,7 @@ function backup_cluster
       echo "s9s_mongodb_admin --backup -i <cluster id>"
       exit 1
   fi
-
-
-  echo $CLUSTER_ID
+  init
   load_opts $CLUSTER_ID
 
   if [ -n "$XBACKUPDIR" ]; then
@@ -1276,12 +1302,13 @@ function backup_cluster
   if [ ! -f $MONGODB_BASEDIR/bin/mongo ]; then
       log_job_message "Could not find $MONGODB_BASEDIR/bin/mongo on the controller, please install the mongo client utilities" 1
       log_job "FAILED" "Backup Failed" 1
+      write_email "Backup failed" "Could not find $MONGODB_BASEDIR/bin/mongo on the controller, please install the mongo client utilities"
       exit 1
   fi
 
   echo "starting mongodb shard backup" > $BACKUP_LOGFILE
   sleep 5
-  log_job_message "Startinng backup" 0
+  log_job_message "Starting backup" 0
   log_job "RUNNING" "Backup started" 0
   
 
@@ -1308,6 +1335,7 @@ EOF
   if [ $CNT_UP -ne $CNT_ALL ]; then
       log_job_message "All servers are not started - refusing to start backup." 1
       log_job "FAILED" "Backup Failed" 1
+      write_email "Backup failed" "All servers are not started - refusing to start backup"
       exit 1
   fi
 
@@ -1337,6 +1365,7 @@ EOF
   if [ $? -ne 0 ]; then
       log_job_message  "Failed to create backup record" 1
       log_job "FAILED" "Backup Failed" 1
+      write_email "Backup failed" "Failed to create backup record"
       exit 1
   fi
 
@@ -1358,6 +1387,7 @@ EOF
 	  set_backup_status 'failed' 1
 	  log_job_message "No cfg servers found" 1
 	  log_job "FAILED" "Backup Failed" 1
+	  write_email "Backup failed" "No configuration servers found."
 	  exit 1
       fi
   fi
@@ -1378,6 +1408,7 @@ EOF
           if [ $? -ne 0 ];  then
 	      echo "Failed to lock shard server" >> $BACKUP_LOGFILE
 	      log_job_message "Failed to lock shard  $RS_HNAME:$RS_PORT" 1
+	      write_email "Backup failed" "Failed to lock shard  $RS_HNAME:$RS_PORT" 
 	      set_backup_status 'failed' 1
 	      exit 1
 	  fi	  
@@ -1386,6 +1417,7 @@ EOF
       log_job_message "No rs servers" 1
       set_backup_status 'failed' 1
       log_job "FAILED" "Backup Failed" 1
+      write_email "Backup failed" "No replica set servers found." 
       exit 1
   fi
 
@@ -1411,6 +1443,7 @@ EOF
       else
 	  set_backup_status 'failed' 1
 	  log_job_message "No cfg server to dump from" 1
+	  write_email "Backup failed" "No config servers found to run mongodump on." 
 	  log_job "FAILED" "Backup Failed" 1
 	  exit 1
       fi
@@ -1437,6 +1470,7 @@ EOF
   else
       set_backup_status 'failed' 1
       log_job_message "No rs servers" 1
+      write_email "Backup failed" "No replica set servers found to run mongodump on." 
       log_job "FAILED" "Backup Failed" 1
       exit 1
   fi
@@ -1477,6 +1511,7 @@ EOF
 	      echo "Failed to unlock shard server" >> $BACKUP_LOGFILE
 	      log_job_message "Failed to unlock shard  $RS_HNAME:$PORT" 1
 	      set_backup_status 'failed' 1
+	      write_email "Backup failed" "Failed to unlock shard  $RS_HNAME:$PORT" 
 	      log_job "FAILED" "Backup Failed" 1
 	      exit 1
           fi
@@ -1518,6 +1553,7 @@ EOF
 		  if [ $? -ne 0 ];  then
 		      echo "Failed to start balancer" >> $BACKUP_LOGFILE
 		      log_job_message "Failed to start balancer (1) - could not connect to mongos  $HNAME:$PORT" 1
+		      write_email "Backup failed" "Failed to start balancer (1) - could not connect to mongos  $HNAME:$PORT" 
 		      set_backup_status 'failed' 1
 		      log_job "FAILED" "Backup Failed" 1
 		      exit 1
@@ -1526,6 +1562,7 @@ EOF
 		  BAL_STATE=`$MONGODB_BASEDIR/bin/mongo $HNAME:$PORT --quiet --eval "sh.getBalancerState()"`
 		  if [ $? -ne 0 ];  then
 		      echo "Failed to start balancer" >> $BACKUP_LOGFILE
+		      write_email "Backup failed" "Failed to start balancer (2) - could not connect to mongos  $HNAME:$PORT" 
 		      log_job_message "Failed to start balancer (2) - could not connect to mongos  $HNAME:$PORT" 1
 		      set_backup_status 'failed' 1
 		      log_job "FAILED" "Backup Failed" 1
@@ -1543,7 +1580,8 @@ EOF
 	      break
 	  done
 	  if [ $OK -eq 0 ]; then
-	      log_job_message "Failed to start balancer" 1
+	      log_job_message "Failed to start balancer (3)" 1
+	      write_email "Backup failed" "Failed to start balancer (2)"
 	      set_backup_status 'failed' 1
 	      log_job "FAILED" "Backup Failed" 1
 	      exit 1
@@ -1553,9 +1591,11 @@ EOF
 
   if [ $FAIL -eq 0 ]; then
      set_backup_status 'completed' 0
+     write_email "Backup Completed" "Backup successful"
      log_job "FINISHED" "Backup Successful" 0
   else
      set_backup_status 'failed' 1 
+     write_email "Backup Failed" "Backup Failed"
      log_job "FAILED" "Backup Failed" 1
   fi
   exit 0
@@ -1564,7 +1604,7 @@ EOF
 ## ADD ARBITER
 function add_arbiter
 {        
-    args=`getopt i:N:P:j:d:h: $*`
+    args=`getopt i:N:P:j:d:h:k: $*`
     set -- $args
     for i
     do
@@ -1587,6 +1627,9 @@ function add_arbiter
 	    -d)
 		ARBIT_DATADIR="$2"; shift;
 		shift;;
+	    -k)
+		KEYFILE="--keyFile=$2 --auth"; shift;
+		shift;;
             --)
 		shift; break;;
 	esac
@@ -1597,7 +1640,7 @@ function add_arbiter
       echo "s9s_mongodb_admin --add-arbiter -i <cluster id>"
       exit 1
   fi
-
+  init 
   if [ -z "$RS_NAME" ]; then
       echo "s9s_mongodb_admin --add-arbiter -N <replica set name to add the arbiter to>"
       exit 1
@@ -1656,8 +1699,11 @@ EOF
   remote_cmd $ARBIT_HOSTNAME "mkdir -p /var/log/mongodb"
   remote_cmd $ARBIT_HOSTNAME "mkdir -p /var/run/mongodb"
   PIDFILE="/var/run/mongodb/arbiter_${ARBIT_PORT}.pid"
-  CMDLINE="$MONGODB_BASEDIR/bin/mongod --port $ARBIT_PORT --dbpath $ARBIT_DATADIR --replSet $RS_NAME  --logpath /var/log/mongodb/arbiter_${ARBIT_PORT}.log --pidfilepath $PIDFILE --smallfiles"
-  
+  if [ "$VENDOR" != "tokutek" ]; then
+     MORE_OPTS="--smallfiles"
+  fi
+  CMDLINE="$MONGODB_BASEDIR/bin/mongod --port $ARBIT_PORT --dbpath $ARBIT_DATADIR --replSet $RS_NAME  --logpath /var/log/mongodb/arbiter_${ARBIT_PORT}.log --pidfilepath $PIDFILE $MORE_OPTS $KEYFILE $AUTH"
+
   remote_cmd3 $ARBIT_HOSTNAME "$CMDLINE"
   
   sed  -i.bak "s#ARBIT_HOSTNAME#${ARBIT_HOSTNAME}#g"  /tmp/addArbiter.js
@@ -1771,7 +1817,7 @@ function remove_member
       echo "s9s_mongodb_admin --remove-member -i <cluster id>"
       exit 1
   fi
-
+  init
   if [ -z "$RS_NAME" ]; then
       echo "s9s_mongodb_admin --remove-member -N <replica set name to add the arbiter to>"
       exit 1
@@ -1957,7 +2003,7 @@ case $ARG in
 	;;
     *)
     echo "Usage:"
-    echo "bash ./s9s_mongodb_admin <--remove-lockfile|start-cluster|stop-cluster|--backup|--remove-member|--add-arbiter|upgrade-mongodb> <options follows>"
+    echo "bash ./s9s_mongodb_admin <--remove-lockfile|start-cluster|stop-cluster|--backup|--remove-member|--add-arbiter|upgrade-mongodb|--rolling-restart> <options follows>"
     exit 1
     ;;
 esac
diff --git a/cluster/s9s_rebuild_slave b/cluster/s9s_rebuild_slave
--- a/cluster/s9s_rebuild_slave
+++ b/cluster/s9s_rebuild_slave
@@ -2,23 +2,47 @@
 # Copyright 2012 Severalnines AB
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
+
 LOCKFILE="/tmp/s9s_rebuild_slave.lock"
 
-if [ ! -e /etc/cmon.cnf ] ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
+function init
+{    
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`
+    FILES="$FILES $FILES2"
+    configfile=""
+    for f in $FILES
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `
+	if [ $? -eq 0 ]; then
+            source $f
+            configfile=$f
+        fi
+    done
+
+    if [ -z "$configfile" ]; then
+        echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+        exit 1
+    fi
+    source $configfile;
+    
+    if [ ! -e /etc/cmon.cnf ] ; then
+	echo "Could not find /etc/cmon.cnf"
+	exit 1
     else
-    source /etc/cmon.cnf
-fi
-CID=$cluster_id
-CMON_USER=cmon
-CMON_PASSWORD=$mysql_password
-CMON_DB_HOST=$mysql_hostname
-CMON_DB_PORT=$mysql_port
-CMON_DB_DB=cmon
-MYSQL_BIN=$mysql_basedir/bin/mysql
-MYCNF="/etc/my.cnf"
-JOBID=0
+	source /etc/cmon.cnf
+    fi
+    
+    CID=$cluster_id
+    CMON_USER=cmon
+    CMON_PASSWORD=$mysql_password
+    CMON_DB_HOST=$mysql_hostname
+    CMON_DB_PORT=$mysql_port
+    CMON_DB_DB=cmon
+    MYSQL_BIN=$mysql_basedir/bin/mysql
+    MYCNF="/etc/my.cnf"
+    JOBID=0
+}
 
 function load_opts
 {
@@ -307,11 +331,12 @@ ADDNODE=0
 
 
 
-if [ "$CLUSTER_ID" = "" ]; then
+if [ -z "$CLUSTER_ID" ]; then
     log_job_message "-i <clusterid> not set" 1
     log_job 'FAILED' 'rebuild slave failed' 1
     exit 1
 fi
+init
 
 
 if [ "$MASTER" = "" ]; then
diff --git a/cluster/s9s_ulimit b/cluster/s9s_ulimit
--- a/cluster/s9s_ulimit
+++ b/cluster/s9s_ulimit
@@ -50,16 +50,25 @@ elif [ ! -z "$default_value" ] && [ ! -z "$ulimit_value" ] && [ ! -z "$ulimit_ty
         exit 1
 fi
 
-CMON_CONFIG=/etc/cmon.cnf
-if [ ! -e $CMON_CONFIG ] ; then
-	echo "Could not find $CMON_CONFIG"
-	exit 1
-else
-	source $CMON_CONFIG
-fi
 
-ULIMIT_FILE=/etc/security/limits.conf
-[ ! -e $ULIMIT_FILE ] && echo "ulimit configuration file not found." && exit 1
+FILES=`ls /etc/cmon.cnf 2>&1`
+FILES2=`ls /etc/cmon.d/*.cnf 2>&1`
+FILES="$FILES $FILES2"
+configfile=""
+for f in $FILES
+do
+    X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `
+    if [ $? -eq 0 ]; then
+        source $f
+        configfile=$f
+    fi
+done
+
+if [ -z "$configfile" ]; then
+    echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+    exit 1
+fi
+source $configfile
 
 CMON_DB_HOST=127.0.0.1
 CMON_DB_PORT=$mysql_port
@@ -71,6 +80,12 @@ CONNECT_TIMEOUT=10
 CLUSTER_TYPE=$type
 MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
 OSUSER=`whoami`
+CMON_CONFIG=$configfile
+
+
+ULIMIT_FILE=/etc/security/limits.conf
+[ ! -e $ULIMIT_FILE ] && echo "ulimit configuration file not found." && exit 1
+
 [ ! -z "$osuser" ] && os_user=$osuser
 [ -z "$ssh_port" ] && ssh_port=22
 
