garbd installation pxc

diff --git a/cluster/s9s_galera b/cluster/s9s_galera
--- a/cluster/s9s_galera
+++ b/cluster/s9s_galera
@@ -42,10 +42,10 @@ function init
 	MYSQL_BIN=$MYSQL_BIN2
     fi
     if ! test -f $MYSQL_BIN; then
-	echo "Could not find mysql client binary"
-	log_job_message "Could not find mysql client binary" 1
-	log_job 'FAILED' 'backup failed' 1
-	exit 1
+	    echo "Could not find mysql client binary"
+	    log_job_message "Could not find mysql client binary" 1
+	    log_job 'FAILED' 'job failed' 1
+	    exit 1
     fi
 
     CONNECT_TIMEOUT=10
@@ -54,8 +54,8 @@ function init
     OSUSER=$USER
         
     if [ "$OSUSER" != "root" ]; then
-	echo "must be executed as 'root' or with 'sudo'"
-	exit 1
+	    echo "must be executed as 'root' or with 'sudo'"
+	    exit 1
     fi
 }
  
@@ -100,6 +100,7 @@ function remote_cmd_getreply()
    if [ $? -ne 0 ]; then
        echo "Command failed: ssh -q $SSH_OPTS $SSH_USER@$desthost \"$SUDO $xcommand\""
        log_job_message "FAILED: $ssh -q $SSH_OPTS ${SSH_USER}@${desthost} $SUDO ${xcommand}" 1
+	   log_job 'FAILED' 'job failed' 1
        exit 1
    fi
    x=`echo $x | grep -v "password"`
@@ -138,7 +139,7 @@ function remote_cmdx()
       return 0
    else
       log_job_message "command failed: $xcommand" 1
-      log_job 'FAILED' 'backup failed' 1
+      log_job 'FAILED' 'job failed' 1
       printf "\033[31m[failed]\033[0m\n"
       exit 1
    fi
@@ -178,6 +179,7 @@ function remote_cmd()
       sleep 1
    done
    log_job_message "FAILED: $ssh -q $SSH_OPTS ${SSH_USER}@${desthost} $SUDO ${xcommand}" 1
+   log_job 'FAILED' 'job failed' 1
    printf "\033[31m[failed]\033[0m\n"
    echo $x
    echo 'The following command failed:'
@@ -200,6 +202,7 @@ function remote_cmd3()
    else
       printf "\033[31m[failed]\033[0m\n"
       log_job_message "FAILED: ${desthost}@${xcommand}" 1
+	  log_job 'FAILED' 'job failed' 1
       exit 1
    fi
 }
@@ -831,6 +834,7 @@ function install_garbd
     done    
     if [ -z "$CLUSTER_ID" ]; then
       echo "s9s_galera --install-garbd -i <cluster id> missing"
+	  log_job 'FAILED' 'install garbd failed' 1
       exit 1
     fi
     init     
@@ -848,46 +852,47 @@ function install_garbd
     
     case $CLUSTER_TYPE in
 	galera)
-	    ;;
-	*)
-	    echo "./s9s_galera -- only galera is supported"
-	    exit 1;	           	     
+	        ;;
+	    *)
+	        echo "./s9s_galera -- only galera is supported"
+	        log_job 'FAILED' 'install garbd failed' 1
+	        exit 1;	           	     
     esac
     load_opts $CLUSTER_ID
     if [ -z "$VENDOR" ]; then
 	VENDOR=$XVENDOR
     fi
-
+    
     if [ -z "$VENDOR" ]; then
-	log_job_message  "No vendor was specified" 1
-	echo "./s9s-galera --install-garbd -V [percona|mariadb|codership]"
-	log_job 'FAILED' 'install garbd failed' 1
-	exit 1
+	    log_job_message  "No vendor was specified" 1
+	    echo "./s9s-galera --install-garbd -V [percona|mariadb|codership]"
+	    log_job 'FAILED' 'install garbd failed' 1
+	    exit 1
     fi
     if [ -n "$XGALERA_PORT" ]; then
-	GALERA_PORT="$XGALERA_PORT"
+	    GALERA_PORT="$XGALERA_PORT"
     fi    
     if [ -z "$GALERA_PORT" ]; then
-	GALERA_PORT=4567
+	    GALERA_PORT=4567
     fi
-
-
+    
+    
     sleep 2
     log_job 'RUNNING' 'installing garbd' 0
-
+    
     QUERY="SELECT group_concat(concat(hostname, ':', $GALERA_PORT)) FROM $CMON_DB_DB.mysql_server WHERE cid=${CLUSTER_ID}"
     DONOR_HOSTNAME=`$MYSQL_BIN -B -N $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD --host=$CMON_DB_HOST --port=$CMON_DB_PORT --database=$CMON_DB_DB  -e "$QUERY"`
     if [ -z "$DONOR_HOSTNAME" ]; then
-	echo $QUERY
-	log_job_message "Could not get a cluster address" 1
-	log_job 'FAILED' 'install garbd failed' 1
-	exit 1
+	    echo $QUERY
+	    log_job_message "Could not get a cluster address" 1
+	    log_job 'FAILED' 'install garbd failed' 1
+	    exit 1
     fi
 
     ANY_HOSTNAME=`$MYSQL_BIN -B -N $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD --host=$CMON_DB_HOST --port=$CMON_DB_PORT --database=$CMON_DB_DB  -e "SELECT hostname FROM $CMON_DB_DB.mysql_server WHERE cid=${CLUSTER_ID} AND status=0 LIMIT 1"`
     if [ -z "$ANY_HOSTNAME" ]; then
-	log_job_message "Could not get a cluster address" 1
-	log_job 'FAILED' 'install garbd failed' 1
+	    log_job_message "Could not get a cluster address" 1
+	    log_job 'FAILED' 'install garbd failed' 1
 	exit 1
     fi
     
@@ -895,11 +900,11 @@ function install_garbd
     CLUSTER_NAME=`$MYSQL_BIN $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD --host=$ANY_HOSTNAME --port=$MONITORED_MYSQL_PORT -A -Bse "$QUERY"`
     if [ $? -ne 0 ]; then
         log_job_message "Failed to get wsrep_cluster_name" 1
-	log_job 'FAILED' 'install garbd failed' 1
+	    log_job 'FAILED' 'install garbd failed' 1
         exit 1
     fi
     CLUSTER_NAME=`echo $CLUSTER_NAME | awk   '{print $2;}'`
-
+    
     echo "Hostname: $XHOSTNAME"
     echo "Donor: $DONOR_HOSTNAME"  
     echo "Galera port: $GALERA_PORT"
@@ -910,19 +915,19 @@ function install_garbd
     remote_cmd $XHOSTNAME "chown $SSH_USER:$SSH_USER $S9S_TMPDIR"
     case $VENDOR in
 	percona)
-	    if [ "$OS" = "redhat" ]; then
-		remote_cmd $XHOSTNAME "rpm -Uhv --force http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
-		if [ "$GALERA_VERSION" = "3.x" ]; then
-		    remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-galera-3"
-		fi
-		if [ "$GALERA_VERSION" = "2.x" ]; then
-		    remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-galera-2"
-		fi
-	    else
-		remote_cmd $XHOSTNAME "apt-get update"
-		remote_cmd_nofail $XHOSTNAME "apt-get -y install  libssl0.9.8  wget rsync psmisc"
-		remote_cmd_nofail $XHOSTNAME "sed -i.bak '/repo.percona.com/d'  /etc/apt/sources.list"
-		$HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona
+	        if [ "$OS" = "redhat" ]; then
+		        remote_cmd $XHOSTNAME "rpm -Uhv --force http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
+		        if [ "$GALERA_VERSION" = "3.x" ]; then
+		            remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-garbd-3"
+		        fi
+		        if [ "$GALERA_VERSION" = "2.x" ]; then
+		            remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-garbd-2"
+		        fi
+	        else
+		        remote_cmd $XHOSTNAME "apt-get update"
+		        remote_cmd_nofail $XHOSTNAME "apt-get -y install  libssl0.9.8  wget rsync psmisc"
+		        remote_cmd_nofail $XHOSTNAME "sed -i.bak '/repo.percona.com/d'  /etc/apt/sources.list"
+		        $HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona
 		if [ $? -ne 0 ]; then
 		    log_job_message "Failed: $HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona" 1
 		    log_job 'FAILED' 'install garbd failed' 1
@@ -935,7 +940,7 @@ function install_garbd
 		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
 		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
 		remote_cmd $XHOSTNAME "apt-get -q -y update"
-
+        
 		if [ "$GALERA_VERSION" = "3.x" ]; then
 		    remote_cmd $XHOSTNAME "$HTTP_PROXY LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install percona-xtradb-cluster-garbd-3.x"
 		fi
@@ -1027,21 +1032,22 @@ EOF
 		remote_cmd $XHOSTNAME "mv -f ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL}.tmp /etc/yum.repos.d/MariaDB.repo"
                 remote_cmd $XHOSTNAME "yum -y install galera"
 	    else
-		wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona	
-		remote_copy ${S9S_TMPDIR}/RPM-GPG-KEY-percona ${XHOSTNAME} ${S9S_TMPDIR}/RPM-GPG-KEY-percona
-		remote_cmd $XHOSTNAME "gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'gpg -a --export CD2EFD2A | apt-key add -'"
-		remote_cmd $XHOSTNAME "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" > /etc/apt/sources.list.d/MariaDB.list'"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" >> /etc/apt/sources.list.d/MariaDB.list'"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"Package: *\nPin: origin osuosl.org\nPin-Priority: 1000\n\nPackage: *\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\n\nPackage: libmysqlclient18\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\" > /etc/apt/preferences.d/00MariaDB.pref'"
-		remote_cmd $XHOSTNAME "apt-get -q -y update"
-		remote_cmd $XHOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' --force-yes -y -q install  galera "
+		    wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona	
+		    remote_copy ${S9S_TMPDIR}/RPM-GPG-KEY-percona ${XHOSTNAME} ${S9S_TMPDIR}/RPM-GPG-KEY-percona
+		    remote_cmd $XHOSTNAME "gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
+		    remote_cmd $XHOSTNAME "/bin/sh -c 'gpg -a --export CD2EFD2A | apt-key add -'"
+		    remote_cmd $XHOSTNAME "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db"
+		    remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" > /etc/apt/sources.list.d/MariaDB.list'"
+		    remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" >> /etc/apt/sources.list.d/MariaDB.list'"
+		    remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"Package: *\nPin: origin osuosl.org\nPin-Priority: 1000\n\nPackage: *\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\n\nPackage: libmysqlclient18\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\" > /etc/apt/preferences.d/00MariaDB.pref'"
+		    remote_cmd $XHOSTNAME "apt-get -q -y update"
+		    remote_cmd $XHOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' --force-yes -y -q install  galera "
 	    fi
 	    ;;
-	*)
-	    echo "Not a supported vendor"
-	    exit 1;	           	     
+	    *)
+	        echo "Not a supported vendor"
+	        log_job 'FAILED' 'install garbd failed' 1
+	        exit 1;	           	     
     esac
     QUERY="INSERT IGNORE INTO cmon_configuration(cid,param,value,report_ts) VALUES($CLUSTER_ID,'VENDOR', '$VENDOR', now())"
     `$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "$QUERY"`
