bug fix

diff --git a/cluster/s9s_galera b/cluster/s9s_galera
--- a/cluster/s9s_galera
+++ b/cluster/s9s_galera
@@ -421,7 +421,8 @@ function stop_node
     fi
 
     if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_galera --stop-cluster -i <clusterid>  missing"
+      echo "s9s_galera --stop-node -i <clusterid>  missing"
+      exit 1
     fi
 
     if [ -z "$XHOSTNAME" ]; then
