replica set backup

diff --git a/cluster/s9s_mongodb_admin b/cluster/s9s_mongodb_admin
--- a/cluster/s9s_mongodb_admin
+++ b/cluster/s9s_mongodb_admin
@@ -418,6 +418,19 @@ function get_count_all
 }
 
 
+function get_count_type
+{
+    local TYPE=$1
+    local QUERY="select count(m.id) from mongodb_server m,mongodb_nodetype_map n WHERE m.cid=$CLUSTER_ID  and m.node_type=n.id and n.name='$TYPE'"
+    local CNT=`$MYSQL_BIN $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=127.0.0.1 --port=$CMON_DB_PORT -N -Bse "$QUERY"`   
+    if [ $? -ne 0 ]; then
+	echo "getting server list failed"
+	exit 1
+    fi
+    echo "$CNT"
+}
+
+
 function get_rs_victims
 {
     local QUERY="select group_concat(concat(hostname, ',', nodeid, ',', port, ',', rs_name, ',', dbpath) SEPARATOR ' ') from (select m.hostname, m.nodeid, m.port, m.rs_name, m.dbpath from mongodb_server m,mongodb_nodetype_map n WHERE m.cid=$CLUSTER_ID and m.node_type=n.id and n.name='shardsvr' and m.status=2 group by rs_name) t"  
@@ -657,6 +670,14 @@ EOF
       echo "All servers are not started - refusing to start backup."
       exit 1
   fi
+
+  CNT_CFG=$(get_count_type "configsvr")
+  CNT_MONGOS=$(get_count_type "mongos")
+  
+  if [ $CNT_CFG -eq 0 ]; then
+      REPLICASET_BACKUP=1
+  fi
+
   BACKUP_ID=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select ifnull(max(backupid)+1,1) from mongodb_backup"`
   
 
@@ -672,22 +693,24 @@ EOF
   fi
 
 
-
   ##  STOP CONFIG SVR
-  TYPE="configsvr"
-  SERVER_LIST=$(get_servers $TYPE)
-  if [ "$SERVER_LIST" != "NULL" ]; then
-      for r in $SERVER_LIST
-      do	  
-	  CONFIG_SVR_HNAME=`echo $r | awk -F ',' '{print $1};'`
-	  CONFIG_SVR_NODEID=`echo $r | awk -F ',' '{print $2};'`
-	  stop_node $CONFIG_SVR_HNAME $CONFIG_SVR_NODEID	 
-	  break
-      done
-  else
-      ##set_backup_status 'failed' 1
-      log_job_message "No cfg servers found" 0
-      #exit 1
+  if [ $REPLICASET_BACKUP -eq 0 ]; then      
+      TYPE="configsvr"
+      SERVER_LIST=$(get_servers $TYPE)
+      if [ "$SERVER_LIST" != "NULL" ]; then
+	  for r in $SERVER_LIST
+	  do	  
+	      CONFIG_SVR_HNAME=`echo $r | awk -F ',' '{print $1};'`
+	      CONFIG_SVR_NODEID=`echo $r | awk -F ',' '{print $2};'`
+	      stop_node $CONFIG_SVR_HNAME $CONFIG_SVR_NODEID	 
+	      break
+	  done
+      else
+	  set_backup_status 'failed' 1
+	  log_job_message "No cfg servers found" 0
+	  log_job "FAILED" "Backup Failed" 1
+	  exit 1
+      fi
   fi
 
   TYPE="shardsvr"
@@ -712,33 +735,37 @@ EOF
   else
       echo "No rs servers"
       set_backup_status 'failed' 1
+      log_job "FAILED" "Backup Failed" 1
       exit 1
   fi
   curr_time=`date +%Y-%m-%d-%H-%M-%S`;
   
   BACKUPDIR=$BACKUPDIR/$curr_time
-
-  TYPE="configsvr"
-  CFG_VICTIM_LIST=$(get_configsvr $TYPE)
-  if [ "$CFG_VICTIM_LIST" != "NULL" ]; then
-      for r in $CFG_VICTIM_LIST
-      do	  
-	  CFG_HNAME=`echo $r | awk -F ',' '{print $1};'`
-	  CFG_NODEID=`echo $r | awk -F ',' '{print $2};'`
-	  CFG_PORT=`echo $r | awk -F ',' '{print $3};'`
-	  log_job_message "Backing up config server $CFG_HNAME:$CFG_PORT" 0
-	  mkdir -p $BACKUPDIR/config/
-	  if [ "$VENDOR" = "tokutek" ]; then
-	      LC_ALL=C  $MONGODB_BASEDIR/bin/mongodump --db config -h $CFG_HNAME:$CFG_PORT -o $BACKUPDIR  >> $BACKUP_LOGFILE  2>&1
-	  else
-	      LC_ALL=C  $MONGODB_BASEDIR/bin/mongodump --journal --db config -h $CFG_HNAME:$CFG_PORT -o $BACKUPDIR  >> $BACKUP_LOGFILE  2>&1
-	  fi
-	  break
-      done
-#  else
- #     set_backup_status 'failed' 1
-  #    log_job_message "No cfg server to dump from" 1
-  #    exit 1
+  if [ $REPLICASET_BACKUP -eq 0 ]; then      
+      
+      TYPE="configsvr"
+      CFG_VICTIM_LIST=$(get_configsvr $TYPE)
+      if [ "$CFG_VICTIM_LIST" != "NULL" ]; then
+	  for r in $CFG_VICTIM_LIST
+	  do	  
+	      CFG_HNAME=`echo $r | awk -F ',' '{print $1};'`
+	      CFG_NODEID=`echo $r | awk -F ',' '{print $2};'`
+	      CFG_PORT=`echo $r | awk -F ',' '{print $3};'`
+	      log_job_message "Backing up config server $CFG_HNAME:$CFG_PORT" 0
+	      mkdir -p $BACKUPDIR/config/
+	      if [ "$VENDOR" = "tokutek" ]; then
+		  LC_ALL=C  $MONGODB_BASEDIR/bin/mongodump --db config -h $CFG_HNAME:$CFG_PORT -o $BACKUPDIR  >> $BACKUP_LOGFILE  2>&1
+	      else
+		  LC_ALL=C  $MONGODB_BASEDIR/bin/mongodump --journal --db config -h $CFG_HNAME:$CFG_PORT -o $BACKUPDIR  >> $BACKUP_LOGFILE  2>&1
+	      fi
+	      break
+	  done
+      else
+	  set_backup_status 'failed' 1
+	  log_job_message "No cfg server to dump from" 1
+	  log_job "FAILED" "Backup Failed" 1
+	  exit 1
+      fi
   fi
 
   if [ "$RS_VICTIM_LIST" != "NULL" ]; then
@@ -762,6 +789,7 @@ EOF
   else
       set_backup_status 'failed' 1
       log_job_message "No rs servers" 1
+      log_job "FAILED" "Backup Failed" 1
       exit 1
   fi
  
@@ -807,64 +835,66 @@ EOF
       exit 1
   fi
 
-  echo "Starting config server" >> $BACKUP_LOGFILE
-  
+  if [ $REPLICASET_BACKUP -eq 0 ]; then
+      echo "Starting config server" >> $BACKUP_LOGFILE
+      
   ##  START CONFIG SVR
-  start_node $CONFIG_SVR_HNAME $CONFIG_SVR_NODEID	 
-
+      start_node $CONFIG_SVR_HNAME $CONFIG_SVR_NODEID	 
+      
   ## WAIT FOR CLUSTER TO BECOME STARTED"
-  echo "Waiting for cluster to become STARTED" >> $BACKUP_LOGFILE
+      echo "Waiting for cluster to become STARTED" >> $BACKUP_LOGFILE
+  fi
   wait_for_cluster_state "STARTED"
   sleep 30
+  
+  if [ $REPLICASET_BACKUP -eq 0 ]; then
   ## START BALANCER
-  TYPE="mongos"
-  OK=0
-  MONGOS_LIST=$(get_servers $TYPE)
-  if [ "$MONGOS_LIST" != "NULL" ]; then
-      echo "Starting balancer" >> $BACKUP_LOGFILE
-      for r in $MONGOS_LIST
-      do	  
-	  HNAME=`echo $r | awk -F ',' '{print $1};'`
-	  NODEID=`echo $r | awk -F ',' '{print $2};'`
-	  PORT=`echo $r | awk -F ',' '{print $3};'`
-	  while [ $retry -lt $START_BALANCER_TIMEOUT ]; 
-	  do
-	      LC_ALL=C  $MONGODB_BASEDIR/bin/mongo $HNAME:$PORT /tmp/startBalancer.js >> $BACKUP_LOGFILE  2>&1 
-	      if [ $? -ne 0 ];  then
-		  echo "Failed to start balancer" >> $BACKUP_LOGFILE
-		  log_job_message "Failed to start balancer (1) - could not connect to mongos  $HNAME:$PORT" 1
-		  set_backup_status 'failed' 1
-		  exit 1
-	      fi
-	      sleep 1
-	      BAL_STATE=`$MONGODB_BASEDIR/bin/mongo $HNAME:$PORT --quiet --eval "sh.getBalancerState()"`
-	      if [ $? -ne 0 ];  then
-		  echo "Failed to start balancer" >> $BACKUP_LOGFILE
-		  log_job_message "Failed to start balancer (2) - could not connect to mongos  $HNAME:$PORT" 1
-		  set_backup_status 'failed' 1
-		  exit 1
-	      fi
-	      if [ "$BAL_STATE" = "true" ]; then
-		  echo "Started balancer" >> $BACKUP_LOGFILE
-		  log_job_message "Balancer started" 0
-		  OK=1
-		  break
-	      else
-		  retry=`expr $retry + 1`
-	      fi
-	  done	  
-	  break
-      done
-      if [ $OK -eq 0 ]; then
-	  log_job_message "Failed to start balancer" 1
-	  set_backup_status 'failed' 1
-	  exit 1
+      TYPE="mongos"
+      OK=0
+      MONGOS_LIST=$(get_servers $TYPE)
+      if [ "$MONGOS_LIST" != "NULL" ]; then
+	  echo "Starting balancer" >> $BACKUP_LOGFILE
+	  for r in $MONGOS_LIST
+	  do	  
+	      HNAME=`echo $r | awk -F ',' '{print $1};'`
+	      NODEID=`echo $r | awk -F ',' '{print $2};'`
+	      PORT=`echo $r | awk -F ',' '{print $3};'`
+	      while [ $retry -lt $START_BALANCER_TIMEOUT ]; 
+	      do
+		  LC_ALL=C  $MONGODB_BASEDIR/bin/mongo $HNAME:$PORT /tmp/startBalancer.js >> $BACKUP_LOGFILE  2>&1 
+		  if [ $? -ne 0 ];  then
+		      echo "Failed to start balancer" >> $BACKUP_LOGFILE
+		      log_job_message "Failed to start balancer (1) - could not connect to mongos  $HNAME:$PORT" 1
+		      set_backup_status 'failed' 1
+		      exit 1
+		  fi
+		  sleep 1
+		  BAL_STATE=`$MONGODB_BASEDIR/bin/mongo $HNAME:$PORT --quiet --eval "sh.getBalancerState()"`
+		  if [ $? -ne 0 ];  then
+		      echo "Failed to start balancer" >> $BACKUP_LOGFILE
+		      log_job_message "Failed to start balancer (2) - could not connect to mongos  $HNAME:$PORT" 1
+		      set_backup_status 'failed' 1
+		      exit 1
+		  fi
+		  if [ "$BAL_STATE" = "true" ]; then
+		      echo "Started balancer" >> $BACKUP_LOGFILE
+		      log_job_message "Balancer started" 0
+		      OK=1
+		      break
+		  else
+		      retry=`expr $retry + 1`
+		  fi
+	      done	  
+	      break
+	  done
+	  if [ $OK -eq 0 ]; then
+	      log_job_message "Failed to start balancer" 1
+	      set_backup_status 'failed' 1
+	      exit 1
+	  fi
       fi
-#  else
-#      log_job_message "No mongos servers" 1
-#      set_backup_status 'failed' 1
-#      exit 1
   fi
+
   if [ $FAIL -eq 0 ]; then
      set_backup_status 'completed' 0
   else
