s9s_haproxy

diff --git a/cluster/s9s_haproxy b/cluster/s9s_haproxy
--- a/cluster/s9s_haproxy
+++ b/cluster/s9s_haproxy
@@ -6,42 +6,54 @@
 
 # Also see CREDITS, many thanks to Timothy Der (randomorzero.wordpress.com)
 # for the work on the makecfg, mysqlckk, and haproxy.cfg.tmpl
-
-
-if [ ! -e /etc/cmon.cnf ] ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
-else
-    source /etc/cmon.cnf
-fi
-
-
-CMON_DB_HOST=127.0.0.1
-CMON_DB_PORT=$mysql_port
-CMON_USER=cmon
-CMON_DB_DB=cmon
-CMON_PASSWORD=$mysql_password
-MYSQL_BIN=$mysql_basedir/bin/mysql
-CONNECT_TIMEOUT=10
-CLUSTER_TYPE=$type
-MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
-LOCKFILE="/tmp/s9s_haproxy.lock"
-OSUSER=$USER
-SUFFIX="1"
-PREFIX="s9s"
 JOBID=0
-HAPROXY_MYSQL_LISTEN_PORT="33306"
-HAPROXY_OPTS="-f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -st \$(cat /var/run/haproxy.pid)"
-LB_ADMIN_USER='admin'
-LB_ADMIN_PORT="9600"
-LB_ADMIN_PASSWORD='admin'
+LOCKFILE="/tmp/s9s_haproxy.lock"
+function init
+{    
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`
+    FILES="$FILES $FILES2"
+    configfile=""
+    for f in $FILES
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `
+	if [ $? -eq 0 ]; then
+            source $f
+            configfile=$f
+        fi
+    done
 
-if [ "$OSUSER" != "root" ]; then
-    echo "must be executed as 'root' or with 'sudo'"
-    exit 1
-fi
- 
-TMPDIR=/Users/johan/tmp
+    if [ -z "$configfile" ]; then
+        echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+        exit 1
+    fi
+
+    source $configfile;
+
+    CMON_DB_HOST=127.0.0.1
+    CMON_DB_PORT=$mysql_port
+    CMON_USER=cmon
+    CMON_DB_DB=cmon
+    CMON_PASSWORD=$mysql_password
+    MYSQL_BIN=$mysql_basedir/bin/mysql
+    CONNECT_TIMEOUT=10
+    CLUSTER_TYPE=$type
+    MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
+    OSUSER=$USER
+    SUFFIX="1"
+    PREFIX="s9s"
+    HAPROXY_MYSQL_LISTEN_PORT="33306"
+    HAPROXY_OPTS="-f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -st \$(cat /var/run/haproxy.pid)"
+    LB_ADMIN_USER='admin'
+    LB_ADMIN_PORT="9600"
+    LB_ADMIN_PASSWORD='admin'
+
+    if [ "$OSUSER" != "root" ]; then
+	echo "must be executed as 'root' or with 'sudo'"
+	exit 1
+    fi
+}
+
 
 function log_job_message
 {    
@@ -760,15 +772,17 @@ function install_haproxy
                 esac
     done
 
-    
-    if [ -z "$CMON_PASSWORD" ]; then
-      log_job_message  "s9s_haproxy --install -p  missing" 1
-      log_job 'FAILED' 's9s_haproxy failed' 1
-      exit 1
-    fi
-
     if [ -z "$CLUSTER_ID" ]; then
 	log_job_message "s9s_haproxy --install -i <cluster id>  missing" 1
+	log_job 'FAILED' 's9s_haproxy failed' 1
+      exit 1
+    fi
+    
+    init
+    log_job 'RUNNING' 'Job is running' 0
+
+    if [ -z "$CMON_PASSWORD" ]; then
+      log_job_message  "s9s_haproxy --install -p  missing" 1
       log_job 'FAILED' 's9s_haproxy failed' 1
       exit 1
     fi
@@ -782,22 +796,19 @@ function install_haproxy
     if [ -z "$LB_NAME" ]; then
         LB_NAME="production"
     fi
-
-    if [ -z "$JOBID" ]; then
-	JOBID=0
-    fi
-
     sleep 1
     log_job 'RUNNING' 'Job is running' 0
+    sleep 2
+    log_job 'RUNNING' 'Job is running' 0
     load_opts $CLUSTER_ID
-    
+    log_job 'RUNNING' 'Job is running' 0
     test_ssh $LB_HOSTNAME
     sleep 2
     log_job 'RUNNING' 'Job is running' 0
     rm -rf $TMPDIR/haproxy/*
     prepare
     chown -R $SSH_USER:$SSH_USER $TMPDIR
-    sleep 2
+    sleep 1
     log_job 'RUNNING' 'Job is running' 0
     case $OS in
         rhel|redhat)
@@ -837,7 +848,7 @@ function install_haproxy
             exit
             ;;
     esac
-    
+    log_job 'RUNNING' 'Job is running' 0
     case $CLUSTER_TYPE in
         galera)
         ;;
@@ -849,7 +860,7 @@ function install_haproxy
 	exit 1
         ;;
     esac
-
+    log_job 'RUNNING' 'Job is running' 0
     if [ -n "$LB_NODE_LIST" ]; then
 	LB_NODE_LIST2=`echo $LB_NODE_LIST | sed "s/,/','/g" | sed "s/^/'/g" | sed "s/$/'/g" |sed "s/[ ]*//g"`
 	
@@ -892,9 +903,10 @@ function install_haproxy
     echo "*************************************************************"
     for h in $hostnames
     do
+	log_job 'RUNNING' 'Job is running' 0
 	install_mysqlchk $h
     done
-
+    log_job 'RUNNING' 'Job is running' 0
 
     echo ""
     echo "*************************************************************"
@@ -958,7 +970,7 @@ function install_haproxy
     echo ""
     echo "** Tuning Network **"
     echo ""
-
+    log_job 'RUNNING' 'Job is running' 0
     remote_cmd_nofail $LB_HOSTNAME "sed  -i.bak  '/net.ipv4.ip_nonlocal_bind.*/d' /etc/sysctl.conf"
     remote_cmd $LB_HOSTNAME  "/bin/sh -c 'echo \"net.ipv4.ip_nonlocal_bind=1\" >> /etc/sysctl.conf'"
     remote_cmd_nofail $LB_HOSTNAME "sed  -i.bak  '/net.ipv4.tcp_tw_reuse.*/d' /etc/sysctl.conf"
@@ -1061,16 +1073,17 @@ function install_keepalived
                 esac
     done
 
+    if [ -z "$CLUSTER_ID" ]; then
+	log_job_message "s9s_haproxy --install-ka -i <cluster id>  missing" 1
+	log_job 'FAILED' 's9s_haproxy failed' 1
+      exit 1
+    fi
+    init
+
     
     if [ -z "$CMON_PASSWORD" ]; then
       log_job_message  "s9s_haproxy --install-ka -p  missing" 1
       log_job 'FAILED' 's9s_haproxy failed' 1
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-	log_job_message "s9s_haproxy --install-ka -i <cluster id>  missing" 1
-	log_job 'FAILED' 's9s_haproxy failed' 1
       exit 1
     fi
 
@@ -1156,7 +1169,7 @@ function install_keepalived
 	echo "** Tuning Network **"
 	echo ""    
 	remote_cmd $LB_HOSTNAME  "/bin/sh -c 'echo \"net.ipv4.ip_nonlocal_bind=1\" >> /etc/sysctl.conf'"
-	remote_cmd $LB_HOSTNAME  "sysctl -e -p"    
+	remote_cmd $LB_HOSTNAME  "/sbin/sysctl -e -p"    
 	
 
 	QUERY="REPLACE INTO keepalived(cid, keepalived_addr, virtual_ip ,haproxy_addr1,haproxy_addr2, name) VALUES ($CLUSTER_ID, '$LB_HOSTNAME','$VIRTUAL_IP','$LB_HOSTNAME1','$LB_HOSTNAME2','$KEEPALIVED_NAME')"
@@ -1227,17 +1240,16 @@ function delete_keepalived
                 shift; break;;
                 esac
     done
-
+    if [ -z "$CLUSTER_ID" ]; then
+	log_job_message "s9s_haproxy --delete-ka -i <cluster id>  missing" 1
+	log_job 'FAILED' 's9s_haproxy failed' 1
+      exit 1
+    fi
+    init
     
     if [ -z "$CMON_PASSWORD" ]; then
       log_job_message  "s9s_haproxy --delete-ka -p  missing" 1
       log_job 'FAILED' 's9s_haproxy failed' 1
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-	log_job_message "s9s_haproxy --delete-ka -i <cluster id>  missing" 1
-	log_job 'FAILED' 's9s_haproxy failed' 1
       exit 1
     fi
 
@@ -1369,16 +1381,15 @@ function delete_haproxy
                 shift; break;;
                 esac
     done
-
-    
-    if [ -z "$CMON_PASSWORD" ]; then
-      log_job_message "s9s_haproxy --delete -p  missing" 1
+    if [ -z "$CLUSTER_ID" ]; then
+      log_job_message "s9s_haproxy --delete -i <cluster id>  missing" 1
       log_job "FAILED" "s9s_haproxy failed" 1
       exit 1
     fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      log_job_message "s9s_haproxy --delete -i <cluster id>  missing" 1
+    init
+    
+    if [ -z "$CMON_PASSWORD" ]; then
+      log_job_message "s9s_haproxy --delete -p  missing" 1
       log_job "FAILED" "s9s_haproxy failed" 1
       exit 1
     fi
@@ -1491,15 +1502,14 @@ function remove_node
                 shift; break;;
                 esac
     done
-
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_haproxy --remove-node -i <cluster id>  missing"
+      exit 1
+    fi
+    init
     
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_haproxy --remove-node -p  missing"
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_haproxy --remove-node -i <cluster id>  missing"
       exit 1
     fi
 
@@ -1587,15 +1597,14 @@ function add_node
                 shift; break;;
                 esac
     done
-
+    if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_haproxy --remove-node -i <cluster id>  missing"
+      exit 1
+    fi
+    init
     
     if [ -z "$CMON_PASSWORD" ]; then
       echo "s9s_haproxy --remove-node -p  missing"
-      exit 1
-    fi
-
-    if [ -z "$CLUSTER_ID" ]; then
-      echo "s9s_haproxy --remove-node -i <cluster id>  missing"
       exit 1
     fi
 
@@ -1673,12 +1682,6 @@ function add_node
     remote_cmd $LB_HOSTNAME "/usr/sbin/haproxy ${HAPROXY_OPTS}"    
 
 }
-
-
-
-
-
-
 
 
 if [ ! -e $LOCKFILE ]; then
