s9s_aws script update

diff --git a/cluster/s9s_aws b/cluster/s9s_aws
--- a/cluster/s9s_aws
+++ b/cluster/s9s_aws
@@ -3,33 +3,49 @@
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
 
+function init
+{
+    FILES=`ls /etc/cmon.cnf 2>&1`
+    FILES2=`ls /etc/cmon.d/*.cnf 2>&1`    
+    FILES="$FILES FILES2"
+    configfile=""
+    for f in $FILES 
+    do
+	X=`grep -l cluster_id=${CLUSTER_ID} $f 2>&1 `	
+	if [ $? -eq 0 ]; then 
+	    source $f
+            configfile=$f
+	fi
+    done
 
-if [ ! -e /etc/cmon.cnf ] ; then
-    echo "Could not find /etc/cmon.cnf"
-    exit 1
-else
-    source /etc/cmon.cnf
-fi
+    if [ -z "$configfile" ]; then
+	echo "No matching configuration file found having cluster_id=${CLUSTER_ID}"
+	exit 1
+    fi
+    
+    echo $configfile
+    source $configfile
+    
+    CMON_DB_HOST=127.0.0.1
+    CMON_DB_PORT=$mysql_port
+    CMON_USER=cmon
+    CMON_DB_DB=cmon
+    CMON_PASSWORD=$mysql_password
+    MYSQL_BIN=$mysql_basedir/bin/mysql
+    CONNECT_TIMEOUT=10
+    CLUSTER_TYPE=$type
+    MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
+    OSUSER=$USER
+    jobid=0    
+        
+    if [ "$OSUSER" != "root" ]; then
+	echo "must be executed as 'root' or with 'sudo'"
+	exit 1
+    fi
+    check_mysql_client
+}
 
-
-CMON_DB_HOST=127.0.0.1
-CMON_DB_PORT=$mysql_port
-CMON_USER=cmon
-CMON_DB_DB=cmon
-CMON_PASSWORD=$mysql_password
-MYSQL_BIN=$mysql_basedir/bin/mysql
-CONNECT_TIMEOUT=10
-CLUSTER_TYPE=$type
-MYSQL_OPTS="--connect-timeout=$CONNECT_TIMEOUT"
 LOCKFILE="/tmp/s9s_aws.lock"
-OSUSER=$USER
-jobid=0
-
-
-if [ "$OSUSER" != "root" ]; then
-    echo "must be executed as 'root' or with 'sudo'"
-    exit 1
-fi
 
 function log_job_message
 {
@@ -231,6 +247,22 @@ function load_opts
     SSH_OPTS="$SSH_OPTSX -p$SSH_PORT $SSH_OPTS"
 }
 
+function valid_ip()
+{
+    local  ip=$1
+    local  stat=1
+
+    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+        OIFS=$IFS
+        IFS='.'
+        ip=($ip)
+        IFS=$OIFS
+        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
+        stat=$?
+    fi
+    return $stat
+}
+
 
 function change_ip
 {
@@ -265,15 +297,17 @@ function change_ip
 
 
 
-    if [ -z "$CMON_PASSWORD" ]; then
-      echo "s9s_aws --change-ip -p  missing"
-      exit 1
-    fi
-
     if [ -z "$CLUSTER_ID" ]; then
       echo "s9s_aws --change-ip -i <clusterid>  missing"
       exit 1
     fi
+    init 
+    if [ -z "$CMON_PASSWORD" ]; then
+      echo "s9s_aws --change-ip -p <cmon_password>  missing"
+      exit 1
+    fi
+
+
     if [ -z "$OLD_HOSTNAME" ]; then
       echo "s9s_aws --change-ip -h <old_hostname>  missing"
       exit 1
@@ -284,10 +318,14 @@ function change_ip
     fi
 
 
+
+
     case $CLUSTER_TYPE in
 	galera)
 	    ;;
 	*)
+	    echo "$CLUSTER_TYPE not supported"
+#	    exit;
     esac
 
     check_cluster_id $CLUSTER_ID
@@ -295,6 +333,7 @@ function change_ip
 
     QUERY="select ip from ${CMON_DB_DB}.hosts where cid=${CLUSTER_ID} and (hostname='$OLD_HOSTNAME' OR ip='$OLD_HOSTNAME')"
     OLD_IP=`$MYSQL_BIN $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD  --host=127.0.0.1 --port=$CMON_DB_PORT --auto-vertical-output -Bse "$QUERY"  2>/dev/null`
+
     [ -z $OLD_IP ] && echo "Unable to find old host/ip address $OLD_HOSTNAME, please check that it's correct." && exit 1
 
     if [ -z "$OS" ]; then
@@ -304,9 +343,20 @@ function change_ip
 	    OS="debian"
 	fi
     fi
-    if [ -z "$NEW_IP" ]; then
-        NEW_IP=$(nslookup $NEW_HOSTNAME | tail --lines=2 | head --lines=1 | cut -f 2 -d " ")
+
+    
+    if valid_ip $NEW_HOSTNAME ; then
+	NEW_IP=$NEW_HOSTNAME
+    else	
+	NEW_IP=`$MYSQL_BASEDIR/bin/resolveip -s $NEW_HOSTNAME`
+        #NEW_IP=$(nslookup $NEW_HOSTNAME | tail --lines=2 | head --lines=1 | cut -f 2 -d " ")
+	if [ $? -ne 0 ]; then
+	    echo "$MYSQL_BASEDIR/bin/resolveip -s $NEW_HOSTNAM failed"
+	    exit 1
+	fi
     fi
+    
+
     if [ -z "$NEW_IP" ]; then
         echo "failed to determine ip, specify the ip manually with -k <new ip>"
         echo "even if new_hostname is also the new ip"
@@ -314,8 +364,18 @@ function change_ip
     fi
 
     # ping new IP
+    echo "Changing from $OLD_HOSTNAME ($OLD_IP) --> to $NEW_HOSTNAME ($NEW_IP)"
+    read -p "Is the new ip address '$NEW_IP' correct? (y/n):  " yn
+    case $yn in
+        [Yy]* ) break;;
+        [Nn]* ) exit;;
+        * ) echo "Please answer yes or no.";;
+    esac
+
     echo "Pinging new host..."
     remote_cmd $NEW_IP "echo 2>&1"
+
+    echo "Updating IP"
 
     QUERY="BEGIN; UPDATE hosts SET hostname='$NEW_HOSTNAME', ip='$NEW_IP'  WHERE cid=$CLUSTER_ID AND (hostname='$OLD_HOSTNAME' OR ip='$OLD_IP')"
     QUERY="$QUERY;UPDATE mysql_server SET hostname='$NEW_HOSTNAME'   WHERE cid=$CLUSTER_ID AND (hostname='$OLD_HOSTNAME'); COMMIT"
@@ -403,15 +463,15 @@ function check_mysql_client()
    fi
 }
 
-if [ ! -e $LOCKFILE ]; then
+if [ ! -f $LOCKFILE ]; then
     trap "rm -f $LOCKFILE; exit" INT TERM EXIT
     touch $LOCKFILE
 
-    check_mysql_client
-
-    case $1 in
+    ARG=$1
+    shift
+    case $ARG in
 	--change-ip)
-	    change_ip  $2 $3 $4 $5 $6 $7 $8 $9
+	    change_ip  $*
 	    ;;
 	*)
 	    echo "Usage: "
@@ -422,6 +482,6 @@ if [ ! -e $LOCKFILE ]; then
     rm $LOCKFILE
     trap - INT TERM EXIT
 else
-    echo "$LOCKFILE exists, perhaps someone is using s9s_galera? Else remove the lock file if it is spurious"
+    echo "$LOCKFILE exists, perhaps someone is using s9s_aws? Else remove the lock file if it is spurious"
 fi
 
