backup fixes

diff --git a/cluster/s9s_backup_wd b/cluster/s9s_backup_wd
--- a/cluster/s9s_backup_wd
+++ b/cluster/s9s_backup_wd
@@ -4,6 +4,7 @@ BACKUP_LOGFILE=$1
 SLEEPTIME=10
 
 searchexpr="innobackupex: Error: "
+searchexpr2="innobackupex: completed OK!"
 #give xtrabackup a chance to start
 sleep 60
 
@@ -19,11 +20,24 @@ do
         exit 1
       fi
       if  grep " Starting to lock all tables" $BACKUP_LOGFILE ;  then
-          sleep 60
+          sleep 10
           rm -rf /tmp/xtrabackup_suspended_2
       fi
    else
-      exit 0
+      err=`grep "$searchexpr" $BACKUP_LOGFILE`
+      if [ $? -eq 0 ]; then
+        sleep $SLEEPTIME
+        killall -9 xtrabackup innobackupex xtrabackup_55 xtrabackup_56
+        echo "BACKUP FAILED: $err " >> $BACKUP_LOGFILE
+        exit 1
+      fi
+      err=`grep "$searchexpr2" $BACKUP_LOGFILE`
+      if [ $? -eq 0 ]; then
+        echo "BACKUP Completed OK: $err " >> $BACKUP_LOGFILE
+        exit 0
+      fi
+      echo "BACKUP FAILED: Unknonw reason at this point. " >> $BACKUP_LOGFILE
+      exit 1
    fi
    sleep 2
 done
diff --git a/cluster/s9s_backupc_wd b/cluster/s9s_backupc_wd
--- a/cluster/s9s_backupc_wd
+++ b/cluster/s9s_backupc_wd
@@ -35,6 +35,9 @@ do
     if [ -n "$x" ]; 
     then
 	scp -q $SCP_OPTS $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE $BACKUP_LOGFILE
+	if  [ $? -ne 0 ]; then
+	    exit 1
+	fi
 	err=`grep "$searchexpr" $BACKUP_LOGFILE`
 	if [ -n "$err" ]; then
             sleep $SLEEPTIME
@@ -50,11 +53,35 @@ do
 	    do
 		ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME "$SUDO kill -15 $p"
 	    done
-            echo "BACKUP FAILED: $err " >> /tmp/s9s_backupc_wd.log
+            echo "BACKUP OK: $err " >> /tmp/s9s_backupc_wd.log
 	    kill -9 $pid 2>/dev/null
 	    exit 0
 	fi
     else
+
+	scp -q $SCP_OPTS $SSH_USER@$BACKUP_HOSTNAME:$BACKUP_LOGFILE $BACKUP_LOGFILE
+	if  [ $? -ne 0 ]; then
+	    exit 1
+	fi
+	err=`grep "$searchexpr" $BACKUP_LOGFILE`
+	if [ -n "$err" ]; then
+            sleep $SLEEPTIME
+            ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME "$SUDO killall -q -9 xtrabackup innobackupex xtrabackup_55 xtrabackup_56"
+            echo "BACKUP FAILED: $err " >> $BACKUP_LOGFILE
+            echo "BACKUP FAILED: $err " >> /tmp/s9s_backupc_wd.log
+	    kill -9 $pid 2>/dev/null
+            exit 1
+	fi
+	err=`grep "$searchexpr2" $BACKUP_LOGFILE`
+	if [ -n "$err" ]; then
+	    for p in $x 
+	    do
+		ssh $SSH_OPTS $SSH_USER@$BACKUP_HOSTNAME "$SUDO kill -15 $p"
+	    done
+            echo "BACKUP ok: $err " >> /tmp/s9s_backupc_wd.log
+	    kill -9 $pid 2>/dev/null
+	    exit 0
+	fi
 	kill -9 $pid 2>/dev/null
 	exit 0
     fi
