arbiter

diff --git a/cluster/s9s_mongodb_admin b/cluster/s9s_mongodb_admin
--- a/cluster/s9s_mongodb_admin
+++ b/cluster/s9s_mongodb_admin
@@ -1352,11 +1352,141 @@ EOF
   if [ -z "$mongoarbiter_server_addresses" ]; then 
       echo "mongoarbiter_server_addresses=${ARBIT_HOSTNAME}:${ARBIT_PORT}" >> /etc/cmon.cnf
   else
-      sed  -i.bak "s#mongoarbiter_server_addresses=.*#mongoarbiter_server_addresses=${mongoarbiter_server_addresses},$ARBIT_HOSTNAME:$ARBIT_PORT#g"  /etc/cmon.cnf
+      x=`cat /etc/cmon.cnf |grep ${ARBIT_HOSTNAME}:${ARBIT_PORT}`
+      if [ -z "$x" ]; then
+	  sed  -i.bak "s#mongoarbiter_server_addresses=.*#mongoarbiter_server_addresses=${mongoarbiter_server_addresses},$ARBIT_HOSTNAME:$ARBIT_PORT#g"  /etc/cmon.cnf
+      fi
   fi
 
   QUERY="REPLACE INTO mongodb_server(cid, serverid , hostname, port, report_ts, status, arbiter, hidden, votes, slave_delay, username, password, node_type, rs_name, dbpath,logpath, shardsvr, pidfilepath,cmdline)"
   QUERY="$QUERY VALUES ($CLUSTER_ID, $SERVERID, '$ARBIT_HOSTNAME', $ARBIT_PORT, now(), $mystate, 1, 0,1,0,'','',3,'$RS_NAME', '$ARBIT_DATADIR', '/var/log/mongodb/arbiter_${ARBIT_PORT}.log', 0, '$PIDFILE', '$CMDLINE')"
+  $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log
+  if [ $? -ne 0 ]; then
+      echo "Failed: $QUERY"
+      echo "You must restart cmon contoller: service cmon restart"
+      exit 1
+  fi
+  
+  
+  exit 0
+}
+
+
+
+## REMOVE RS MEMBER
+function remove_member
+{        
+    args=`getopt i:N:P:j:d:h: $*`
+    set -- $args
+    for i
+    do
+	case "$i" in
+	    -i)
+		CLUSTER_ID="$2"; shift;
+		shift;;
+	    -j)
+		JOBID="$2"; shift;
+		shift;;
+	    -N)
+		RS_NAME="$2"; shift;
+		shift;;
+	    -h)
+		XHOSTNAME="$2"; shift;
+		shift;;
+	    -P)
+		XPORT="$2"; shift;
+		shift;;
+	    -d)
+		ARBIT_DATADIR="$2"; shift;
+		shift;;
+            --)
+		shift; break;;
+	esac
+    done    
+
+
+  if [ -z "$CLUSTER_ID" ]; then
+      echo "s9s_mongodb_admin --remove-member -i <cluster id>"
+      exit 1
+  fi
+
+  if [ -z "$RS_NAME" ]; then
+      echo "s9s_mongodb_admin --remove-member -N <replica set name to add the arbiter to>"
+      exit 1
+  fi
+
+  if [ -z "$XHOSTNAME" ]; then
+      echo "s9s_mongodb_admin --remove-member -h <arbiter hostname>"
+      exit 1
+  fi
+
+  if [ -z "$XPORT" ]; then
+      echo "s9s_mongodb_admin --remove-member -P <arbiter port>"
+      exit 1
+  fi
+
+
+  echo $CLUSTER_ID
+  load_opts $CLUSTER_ID
+
+  SERVERID=$(check_host_exists $CLUSTER_ID $ARBIT_HOSTNAME)
+
+
+  ARBIT_DATADIR=$ARBIT_DATADIR/$ARBIT_PORT
+  
+  cat << 'EOF' > /tmp/remove.js
+   rs.remove("ARBIT_HOSTNAME:ARBIT_PORT")
+
+EOF
+
+
+  TYPE="shardsvr"
+  RS_VICTIM_LIST=$(get_rs_primary $RS_NAME)
+  if [ "$RS_VICTIM_LIST" != "NULL" ]; then
+      for r in $RS_VICTIM_LIST
+      do	 
+	  RS_HNAME=`echo $r | awk -F ',' '{print $1};'`
+	  RS_NODEID=`echo $r | awk -F ',' '{print $2};'`
+	  RS_PORT=`echo $r | awk -F ',' '{print $3};'`
+      done
+  else
+      log_job_message "No PRIMARY found in replica set $RS_NAME" 1      
+      exit 1
+  fi
+    
+  TYPE="shardsvr"
+  SERVER_LIST=$(get_servers $TYPE)
+  if [ "$SERVER_LIST" != "NULL" ]; then
+      for r in $SERVER_LIST
+      do
+	  HNAME=`echo $r | awk -F ',' '{print $1};'`
+	  NODEID=`echo $r | awk -F ',' '{print $2};'`
+	  PORT=`echo $r | awk -F ',' '{print $3};'`
+	  if [ "$HNAME" = "$XNAME" ] -a [ "$PORT" = "$XPORT" ]; then
+	      stop_node $HNAME $NODEID
+	  fi
+      done
+  fi  
+
+
+  sed  -i.bak "s#ARBIT_HOSTNAME#${XHOSTNAME}#g"  /tmp/remove.js
+  sed  -i.bak "s#ARBIT_PORT#${XPORT}#g"  /tmp/remove.js
+  
+  ${MONGODB_BASEDIR}/bin/mongo ${RS_HNAME}:${RS_PORT} /tmp/remove.js
+  
+
+  if [ $? -ne 0 ]; then
+      echo "failed to remove $XHOSTNAME:$XPORT"
+      exit 1
+  fi      
+    
+  if [ -z "$mongoarbiter_server_addresses" ]; then 
+      echo "mongoarbiter_server_addresses=${ARBIT_HOSTNAME}:${ARBIT_PORT}" >> /etc/cmon.cnf
+  else
+      sed  -i.bak "s#mongoarbiter_server_addresses=.*#mongoarbiter_server_addresses=${mongoarbiter_server_addresses},$ARBIT_HOSTNAME:$ARBIT_PORT#g"  /etc/cmon.cnf
+  fi
+
+  QUERY="DELETE FROM mongodb_server WHERE cid=$CLUSTER_ID AND hostname=$XHOST AND port=$XPORT AND nodeid=$NODEID"
   $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log
   if [ $? -ne 0 ]; then
       echo "Failed: $QUERY"
@@ -1408,10 +1538,12 @@ case $ARG in
     ;;
     --add-arbiter)
 	add_arbiter $*
+    --remove-member)
+	remove_member $*
     ;;
     *)
     echo "Usage:"
-    echo "bash ./s9s_mongodb_admin <--remove-lockfile|start-cluster|stop-cluster|--backup> <options follows>"
+    echo "bash ./s9s_mongodb_admin <--remove-lockfile|start-cluster|stop-cluster|--backup|--remove-member> <options follows>"
     exit 1
     ;;
 esac
