collect more host info + mongodb love

diff --git a/ccadmin/s9s_error_reporter b/ccadmin/s9s_error_reporter
--- a/ccadmin/s9s_error_reporter
+++ b/ccadmin/s9s_error_reporter
@@ -303,8 +303,6 @@ function collect_mysql_logs()
 	    fi
 	fi
 	remote_cmd_nofail $host "cp $CONFIGDIR/my.cnf /tmp"
-	remote_cmd_nofail $host "/sbin/iptables -L > /tmp/iptables_out"
-	remote_cmd_nofail $host "/sbin/ifconfig > /tmp/ifconfig_out"
 	remote_cmd_nofail $host "cp $ERRLOG /tmp"
 	if [ "$CLUSTER_TYPE" = "galera" ]; then
 	    remote_cmd_nofail $host "cp $DATADIR/GRA* /tmp"
@@ -322,14 +320,10 @@ function collect_mysql_logs()
 	    remote_cmd_nofail $host "rm /tmp/GRA*"
 	fi
 	remote_cmd_nofail $host "chown $SSH_USER /tmp/error.log"
-	remote_cmd_nofail $host "chown $SSH_USER /tmp/iptables_out"
-	remote_cmd_nofail $host "chown $SSH_USER /tmp/ifconfig_out"
 	remote_cmd_nofail $host "chown $SSH_USER /tmp/mysql*.log"
 	remote_copy_from_r2 $host /tmp/error.log $tmpsavedir/
 	remote_copy_from_r2 $host /tmp/mysql*.log $tmpsavedir/
 	remote_copy_from_r2 $host /tmp/my.cnf $tmpsavedir/
-	remote_copy_from_r2 $host /tmp/iptables_out $tmpsavedir/
-	remote_copy_from_r2 $host /tmp/ifconfig_out $tmpsavedir/
 	if [ $AGENTLESS -eq 0 ]; then 
 	   remote_cmd_nofail $host "cp /var/log/cmon.log* /tmp"
 	   remote_cmd_nofail $host "chown $SSH_USER /tmp/cmon.log*"
@@ -343,8 +337,6 @@ function collect_mysql_logs()
        remote_cmd_nofail $host "rm /tmp/error.log"
        remote_cmd_nofail $host "rm /tmp/my.cnf"
        remote_cmd_nofail $host "rm /tmp/mysql*.log"
-       remote_cmd_nofail $host "rm /tmp/iptables_out"
-       remote_cmd_nofail $host "rm /tmp/ifconfig_out"
     done
 }
 
@@ -440,6 +432,43 @@ function collect_mongodb_logs()
     done
 }
 
+function collect_host_info()
+{
+    HOSTNAMES=`$MYSQL_BIN -B -N $MYSQL_OPTS --user=$CMON_USER --password=$CMON_PASSWORD --host=$CMON_DB_HOST --port=$CMON_DB_PORT --database=$CMON_DB_DB  -e "SELECT group_concat(hostname SEPARATOR ' ') FROM hosts WHERE cid=${CLUSTER_ID}"`
+    if [ -z "HOSTNAMES" ]; then
+	log_job_message "Could not get hostnames" 1
+	log_job 'FAILED' 'Create error report failed.' 1
+	exit 1
+    fi
+    for host in $HOSTNAMES
+    do
+	mkdir -p $savedir/$host
+	tmpsavedir=$savedir/$host
+
+	remote_cmd_nofail $host "/sbin/iptables -L > /tmp/iptables_out"
+	remote_cmd_nofail $host "/sbin/ifconfig > /tmp/ifconfig_out"
+	remote_cmd_nofail $host "dmesg > /tmp/dmesg_out"
+	remote_cmd_nofail $host "free -m > /tmp/freem_out"
+	remote_cmd_nofail $host "df -h > /tmp/dfh_out"
+	remote_cmd_nofail $host "chown $SSH_USER /tmp/iptables_out"
+	remote_cmd_nofail $host "chown $SSH_USER /tmp/ifconfig_out"
+	remote_cmd_nofail $host "chown $SSH_USER /tmp/dmesg_out"
+	remote_cmd_nofail $host "chown $SSH_USER /tmp/freem_out"
+	remote_cmd_nofail $host "chown $SSH_USER /tmp/dfh_out"
+	remote_copy_from_r2 $host /tmp/iptables_out $tmpsavedir/
+	remote_copy_from_r2 $host /tmp/ifconfig_out $tmpsavedir/
+	remote_copy_from_r2 $host /tmp/dmesg_out $tmpsavedir/
+	remote_copy_from_r2 $host /tmp/freem_out $tmpsavedir/
+	remote_copy_from_r2 $host /tmp/dfh_out $tmpsavedir/	
+	remote_cmd_nofail $host "rm /tmp/iptables_out"
+	remote_cmd_nofail $host "rm /tmp/ifconfig_out"
+	remote_cmd_nofail $host "rm /tmp/dmesg_out"
+	remote_cmd_nofail $host "rm /tmp/freem_out"
+	remote_cmd_nofail $host "rm /tmp/dfh_out"
+
+    done
+}
+
 function collect_ui_logs() 
 {
     mkdir -p $savedir/ui/clustercontrol/logs
@@ -516,6 +545,7 @@ function create_report
     if [ "$CLUSTER_TYPE" = "mongodb" ]; then
 	collect_mongodb_logs
     fi    
+    collect_host_info
     collect_ui_logs
 
     currdir=`pwd`
diff --git a/cluster/s9s_mongodb_admin b/cluster/s9s_mongodb_admin
--- a/cluster/s9s_mongodb_admin
+++ b/cluster/s9s_mongodb_admin
@@ -228,6 +228,12 @@ function load_opts
     SUDO=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='SUDO' AND cid=$CLUSTER_ID"`
     VENDOR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='VENDOR' AND cid=$CLUSTER_ID"`
     S9S_TMPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='STAGING_DIR' AND cid=$CLUSTER_ID"`
+    CLUSTER_TYPE=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select type FROM cluster WHERE id=$CLUSTER_ID"`
+    if [ "${CLUSTER_TYPE}" != "mongodb" ]; then
+	log_job_message "This is not a mongodb cluster, aborting. " 1
+	exit 1
+    fi
+
     BACKUPDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='BACKUPDIR' AND cid=$CLUSTER_ID"`
 
     MONGODB_PORT=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MONGODB_PORT' AND cid=$CLUSTER_ID"`
@@ -235,8 +241,20 @@ function load_opts
     MONGODB_DATADIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select dbpath from  mongodb_server where node_type=0 AND dbpath<>'' and cid=$CLUSTER_ID limit 1"`
     MONGODB_PIDFILEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select pidfilepath from  mongodb_server where node_type=0 and pidfilepath<>'' and cid=$CLUSTER_ID limit 1"`
     MONGODB_PIDFILEPATH=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select pidfilepath from  mongodb_server where node_type=0 and pidfilepath<>'' and cid=$CLUSTER_ID limit 1"`
+    if [ -z ${MONGODB_PIDFILEPATH} ]; then
+	log_job_message "Failed to MONGODB_PIDFILEPATH " 1
+	exit 1
+    fi
+    if [ -z ${MONGODB_PIDFILEDIR} ]; then
+	log_job_message "Failed to MONGODB_PIDFILEDIR " 1
+	exit 1
+    fi
     MONGODB_PIDFILEDIR=`dirname $MONGODB_PIDFILEDIR`
     MONGODB_LOGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select logpath from  mongodb_server where node_type=0 and logpath<>'' and cid=$CLUSTER_ID limit 1"`
+    if [ -z ${MONGODB_LOGDIR} ]; then
+	log_job_message "Failed to MONGODB_LOGDIR " 1
+	exit 1
+    fi
     MONGODB_LOGDIR=`dirname $MONGODB_LOGDIR`
     MONGODB_BASEDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MONGODB_BASEDIR' AND cid=$CLUSTER_ID"`
     MONGODB_CONFIGDIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='MONGODB_CONFIGDIR' AND cid=$CLUSTER_ID"`
@@ -929,7 +947,7 @@ function stop_node
     local xNODEID=$2    
     local cmdline=$(get_field $xNODEID "cmdline")
     local pidfile=$(get_field $xNODEID "pidfilepath")
-    
+
     if [ -z "$cmdline" ]; then 
 	echo "could not read cmdline argument"
 	exit 1
@@ -999,12 +1017,17 @@ function check_node_up
     local xNODEID=$2    
     local cmdline=$(get_field $xNODEID "cmdline")
     local pidfile=$(get_field $xNODEID "pidfilepath")
-    PID=$(remote_cmd_getreply $xHNAME "pgrep -f  '${cmdline}'")
-    if [ -n "$PID" ]; then
+    if [ "$cmdline" != "" ]; then	
+	PID=$(remote_cmd_getreply $xHNAME "pgrep -f  '${cmdline}'")
+	if [ -n "$PID" ]; then
+	    echo "UP"
+	    return
+	fi
+	echo "DOWN"
+    else
+	## If we dont have a cmdline, then assume the node is up
 	echo "UP"
-	return
     fi
-    echo "DOWN"
 }
 
 function check_node_up2
@@ -1710,7 +1733,7 @@ function add_secondary
 		XHOSTNAME="$2"; shift;
 		shift;;
 	    -P)
-		MONGODB_PORT="$2"; shift;
+		XMONGODB_PORT="$2"; shift;
 		shift;;
             --)
 		shift; break;;
@@ -1735,12 +1758,16 @@ function add_secondary
 
   echo $CLUSTER_ID
   load_opts $CLUSTER_ID
+
+  if [ -n "$XMONGODB_PORT" ]; then
+      MONGODB_PORT=$XMONGODB_PORT
+  fi
   
   if [ -z "$MONGODB_PORT" ]; then
       echo "s9s_mongodb_admin --add-secondary -P <secondary port>"
       exit 1
   fi
-
+  
 
   SERVERID=$(check_host_exists $CLUSTER_ID $XHOSTNAME)
   if [ $? -eq 1 ]; then
@@ -2085,7 +2112,7 @@ EOF
       log_job_message "No PRIMARY found in replica set $RS_NAME" 1      
       exit 1
   fi
-    
+
   TYPE="'shardsvr','arbiter'"
   SERVER_LIST=$(get_servers2 $TYPE)
   FOUND=0
@@ -2124,6 +2151,7 @@ EOF
       log_job_message "No PRIMARY found in replica set $RS_NAME" 1      
       exit 1
   fi
+
 ###
   NODEID=$(get_nodeid $XHOSTNAME $XPORT)
 
@@ -2134,10 +2162,12 @@ EOF
   STATE=$(check_node_up $XHOSTNAME $NODEID)
 
   if [ "$STATE" != "DOWN" ]; then
-      ${MONGODB_BASEDIR}/bin/mongo ${XHOSTNAME}:${XPORT} --eval "db.shutdownServer()"      
+      OUT=`${MONGODB_BASEDIR}/bin/mongo ${XHOSTNAME}:${XPORT} --quiet --eval "db.shutdownServer()" `
       if [ $? -ne 0 ];  then
-	  log_job_message "No PRIMARY found in replica set $RS_NAME" 1      
-	  exit 1
+	  log_job_message "Could not shutdown server" 1      
+	  if [ echo '$OUT' | grep 'connect failed' ]; then
+	      exit 1
+	  fi
       fi
   fi
 
