install mysql

diff --git a/ccadmin/s9s_sw_update b/ccadmin/s9s_sw_update
--- a/ccadmin/s9s_sw_update
+++ b/ccadmin/s9s_sw_update
@@ -502,6 +502,21 @@ function install_mysql
 	remote_cmd_nofail $XHOSTNAME "apt-get -y remove MySQL* mysql* Percona* percona* MariaDB* mariadb* MySQL-Cluster* MySQL-cluster* mysql-cluster* galera*"	
     fi
 
+    QUERY="GRANT INSERT,UPDATE,DELETE, SELECT ON '$CMON_DB_DB'.* TO 'cmon'@'$XHOSTNAME' IDENTIFIED BY '$CMON_PASSWORD'"    
+    $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log    
+    if [ $? -ne 0 ]; then 
+	echo "FAILED: $QUERY"
+	echo ""
+	exit 1
+    fi	
+    QUERY="GRANT SUPER ON *.* TO 'cmon'@'$XHOSTNAME' IDENTIFIED BY '$CMON_PASSWORD'"    
+    $MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY" 2>&1 >/tmp/err.log    
+    if [ $? -ne 0 ]; then 
+	echo "FAILED: $QUERY"
+	echo ""
+	exit 1
+    fi	
+
     case $VENDOR in
 	percona)
 	    if [ "$OS" = "redhat" ]; then
