install mysql pkg added, apt install of pxc

diff --git a/ccadmin/s9s_sw_update b/ccadmin/s9s_sw_update
--- a/ccadmin/s9s_sw_update
+++ b/ccadmin/s9s_sw_update
@@ -358,106 +358,6 @@ function update_mysql_pkg
 }
 
 
-function install_mysql_pkg
-{   
-    args=`getopt p:s:P:h:i:N:n:f: $*`
-    set -- $args
-    for i
-    do
-        case "$i" in
-            -p)
-                CMON_PASSWORD="$2"; shift;
-                shift;;
-            -i)
-                CID="$2"; shift;
-                shift;;
-            -h)
-		XHOSTNAME="$2"; shift;
-                shift;;
-            -n)
-                PKG_NAME="$2"; shift;
-                shift;;
-            --)
-                shift; break;;
-                esac
-    done
-
-
-    if [ -z "$XHOSTNAME" ]; then
-	echo 'Syntax:'
-	echo ' s9s_sw_update --install-mysql -i <clusterid> -n <package_name> -h <hostname>'
-	exit 1
-    fi
-    if [ -z "$CID" ]; then
-	echo 'Syntax:'
-	echo ' s9s_sw_update --install-mysql -i <clusterid> -n <package_name> -h <hostname>'
-	exit 1
-    fi
-    load_opts $CID
-    CMON_DB='cmon'
-    echo "Do you want install $PKG_NAME on '$XHOSTNAME' (press y or Y to continue)?"
-    read x
-    if [ "$x" == "y" ] || [ "$x" == "Y" ]; then	
-	QUERY="SELECT packageid FROM ${CMON_DB}.cmon_sw_package WHERE name='$PKG_NAME' AND cid=$CID"
-	PID=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`	
-	if [ -z "$PID" ]; then
-	    echo "Invalid $PKG_NAME"
-	    exit 1
-	fi
-	QUERY="SELECT group_concat(concat(path,',', filename) SEPARATOR ' ') FROM ${CMON_DB}.cmon_uploads WHERE packageid='$PID' AND cid=$CID"
-	FILELIST=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`
-	
-	if [ -z "$FILELIST" ]; then
-	    echo "No files in package $PKG_NAME"
-	    exit 1	    
-	fi
-
-	if [ "$FILELIST" = "NULL" ]; then
-	    echo "No files in package $PKG_NAME"
-	    exit 1	    
-	fi
-
-	remote_cmd $XHOSTNAME "mkdir -p $STAGING_DIR"
-	remote_cmd $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $STAGING_DIR"
-	
-	for f in $FILELIST 
-	do
-	    path=`echo $f | awk -F, '{print $1;}'`
-	    filename=`echo $f | awk -F, '{print $2;}'`	    
-	    remote_copy $path/$filename $XHOSTNAME $STAGING_DIR	    	    
-	done
-	RPMLIST=""
-	for f in $FILELIST 
-	do
-	    filename=`echo $f | awk -F, '{print $2;}'`	    
-	    ext=${filename##*.}
-	    case $ext in
-		gz)
-		    MYSQL_BASEDIR2=${MYSQL_BASEDIR%/}
-		    remote_cmd_nofail $XHOSTNAME "rm -f ${MYSQL_BASEDIR2}*"
-		    remote_cmd $XHOSTNAME "tar xvfz ${STAGING_DIR}/$filename -C `dirname $MYSQL_BASEDIR`"
-		    remote_cmd $XHOSTNAME "ln -s `dirname $MYSQL_BASEDIR`/`basename $filename .tar.gz`  $MYSQL_BASEDIR2"
-		    ;;
-		rpm)
-		    RPMLIST="$RPMLIST $STAGING_DIR/$filename"
-		    ;;
-		deb)
-		    DEBLIST="$DEBLIST $STAGING_DIR/$filename"
-		    ;;
-	    esac	    
-	done
-	if [ -n "$RPMLIST" ]; then
-	    remote_cmd $XHOSTNAME "rpm -Uvh $RPMLIST"
-	fi
-	if [ -n "$DEBLIST" ]; then
-	    remote_cmd $XHOSTNAME "/usr/bin/dpkg -i $DEBLIST"
-	fi
-	echo "Installed $PKG_NAME on $XHOSTNAME"		    
-    fi
-}
-
-
-
 
 function install_mysql
 {
@@ -552,10 +452,10 @@ function install_mysql
     remote_cmd_nofail $XHOSTNAME "rm -rf /etc/init.d/mysql.server"
     
     remote_cmd_nofail $XHOSTNAME "mkdir -p $S9S_TMPDIR"
-    remote_cmd_nofail $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $STAGING_DIR"
-     remote_copy /usr/bin/s9s_backup $XHOSTNAME $S9S_TMPDIR
-     remote_cmd $XHOSTNAME "mv $S9S_TMPDIR/s9s_backup /usr/bin"
-     remote_cmd_nofail $XHOSTNAME "chmod u+x /usr/bin/s9s_backup"
+    remote_cmd_nofail $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
+    remote_copy /usr/bin/s9s_backup $XHOSTNAME $S9S_TMPDIR/s9s_backup
+    remote_cmd $XHOSTNAME "mv $S9S_TMPDIR/s9s_backup /usr/bin"
+    remote_cmd_nofail $XHOSTNAME "chmod u+x /usr/bin/s9s_backup"
      #remote_copy $S9S_TMPDIR/my.cnf $XHOSTNAME $S9S_TMPDIR
 #    remote_cmd $XHOSTNAME "mkdir -p $CONFIGDIR/"
 #    remote_cmd $XHOSTNAME "mv -f $S9S_TMPDIR/my.cnf $CONFIGDIR/"
@@ -590,6 +490,11 @@ function install_mysql
     if [ "$NETWORKLESS" = "yes" ]; then
 	VENDOR=percona_nonet
     fi    
+
+    if [ "$RPM" = "0" ]; then
+	VENDOR="${VENDOR}_tgz"
+    fi    
+    echo $VENDOR
     case $VENDOR in
 	percona)
 	    if [ "$OS" = "redhat" ]; then
@@ -616,7 +521,7 @@ function install_mysql
 		remote_cmd $XHOSTNAME "sync"	
 	    fi
 	    ;;
-	internal_pkg | codership | percona_nonet)	    
+	internal_pkg | codership | percona_nonet | mariadb_tgz | percona_tgz)	    
 	    if [ -z "$PKG_NAME" ]; then
 		## default to MYSQL_INITIAL_DEPLOY if not set
 		PKG_NAME="MYSQL_INITIAL_DEPLOY"
@@ -644,15 +549,15 @@ function install_mysql
 	    fi
 	    
 	    
-	    remote_cmd $XHOSTNAME "mkdir -p $STAGING_DIR"
-	    remote_cmd $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $STAGING_DIR"
+	    remote_cmd $XHOSTNAME "mkdir -p $S9S_TMPDIR"
+	    remote_cmd $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
 	    
 	    for f in $FILELIST 
 	    do
 		path=`echo $f | awk -F, '{print $1;}'`
 		filename=`echo $f | awk -F, '{print $2;}'`	 
 		if [ -f $path/$filename ]; then
-		    remote_copy $path/$filename $XHOSTNAME $STAGING_DIR	    	    
+		    remote_copy $path/$filename $XHOSTNAME $S9S_TMPDIR	    	    
 		else
 		    log_job_message "File did not exist: $path/$filename" 1
 		    log_job 'FAILED' 'job failed' 1
@@ -668,14 +573,14 @@ function install_mysql
 		    gz)
 			MYSQL_BASEDIR2=${MYSQL_BASEDIR%/}
 			remote_cmd_nofail $XHOSTNAME "rm -f ${MYSQL_BASEDIR2}*"
-			remote_cmd $XHOSTNAME "tar xvfz ${STAGING_DIR}/$filename -C `dirname $MYSQL_BASEDIR`"
+			remote_cmd $XHOSTNAME "tar xvfz ${S9S_TMPDIR}/$filename -C `dirname $MYSQL_BASEDIR`"
 			remote_cmd $XHOSTNAME "ln -s `dirname $MYSQL_BASEDIR`/`basename $filename .tar.gz`  $MYSQL_BASEDIR2"
 			;;
 		    rpm)
-			RPMLIST="$RPMLIST $STAGING_DIR/$filename"
+			RPMLIST="$RPMLIST $S9S_TMPDIR/$filename"
 			;;
 		    deb)
-			DEBLIST="$DEBLIST $STAGING_DIR/$filename"
+			DEBLIST="$DEBLIST $S9S_TMPDIR/$filename"
 			;;
 		esac	    
 	    done
@@ -838,16 +743,119 @@ EOF
 		remote_cmd $XHOSTNAME "/sbin/chkconfig --add mysql "
 		remote_cmd $XHOSTNAME "/sbin/chkconfig mysql off --level 2345"
 	    else
-		echo "debian/ubuntu not supported yet"
 		remote_cmd_nofail $XHOSTNAME "/usr/sbin/update-rc.d -f mysql remove"
 		remote_cmd_nofail $XHOSTNAME "/usr/sbin/update-rc.d mysql stop 20 0 1 6 ."
 	    fi
+	    ;;
+	mariadb_tgz | percona_tgz)	 	    
+	    remote_cmd $XHOSTNAME "cp /usr/local/mysql/support-files/mysql.server  /etc/init.d/mysql"
+	    remote_cmd $XHOSTNAME "chown 755 /etc/init.d/mysql"
+	    remote_cmd_nofail $XHOSTNAME "/usr/sbin/update-rc.d -f mysql remove"
+	    remote_cmd_nofail $XHOSTNAME "/usr/sbin/update-rc.d mysql stop 20 0 1 6 ."	    
 	    ;;
 	*)
 	    log_job_message  "Not a supported vendor" 1
 	    log_job 'FAILED' 'job failed' 1
 	    exit 1;	           	     
     esac    
+}
+
+function install_mysql_pkg
+{   
+    args=`getopt p:s:P:h:i:N:n:f: $*`
+    set -- $args
+    for i
+    do
+        case "$i" in
+            -p)
+                CMON_PASSWORD="$2"; shift;
+                shift;;
+            -i)
+                CID="$2"; shift;
+                shift;;
+            -h)
+		XHOSTNAME="$2"; shift;
+                shift;;
+            -n)
+                PKG_NAME="$2"; shift;
+                shift;;
+            --)
+                shift; break;;
+                esac
+    done
+
+
+    if [ -z "$XHOSTNAME" ]; then
+	echo 'Syntax:'
+	echo ' s9s_sw_update --install-mysql-pkg -i <clusterid> -n <package_name> -h <hostname>'
+	exit 1
+    fi
+    if [ -z "$CID" ]; then
+	echo 'Syntax:'
+	echo ' s9s_sw_update --install-mysql-pkg -i <clusterid> -n <package_name> -h <hostname>'
+	exit 1
+    fi
+    load_opts $CID
+    CMON_DB='cmon'
+    echo "Do you want install $PKG_NAME on '$XHOSTNAME' (press y or Y to continue)?"
+    read x
+    if [ "$x" == "y" ] || [ "$x" == "Y" ]; then
+	QUERY="SELECT packageid FROM ${CMON_DB}.cmon_sw_package WHERE name='$PKG_NAME' AND cid=$CID"
+	PID=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`
+	if [ -z "$PID" ]; then
+	    echo "Invalid package name $PKG_NAME - not found."
+	    exit 1
+	fi
+	QUERY="SELECT group_concat(concat(path,',', filename) SEPARATOR ' ') FROM ${CMON_DB}.cmon_uploads WHERE packageid='$PID' AND cid=$CID"
+	FILELIST=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`
+	
+	if [ -z "$FILELIST" ]; then
+	    echo "No files in package $PKG_NAME"
+	    exit 1    
+	fi
+	
+	if [ "$FILELIST" = "NULL" ]; then
+	    echo "No files in package $PKG_NAME"
+	    exit 1    
+	fi
+	
+	remote_cmd $XHOSTNAME "mkdir -p $STAGING_DIR"
+	remote_cmd $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $STAGING_DIR"
+	
+	for f in $FILELIST 
+	do
+	    path=`echo $f | awk -F, '{print $1;}'`
+	    filename=`echo $f | awk -F, '{print $2;}'`    
+	    remote_copy $path/$filename $XHOSTNAME $STAGING_DIR        
+	done
+	RPMLIST=""
+	for f in $FILELIST 
+	do
+	    filename=`echo $f | awk -F, '{print $2;}'`    
+	    ext=${filename##*.}
+	    case $ext in
+		gz)
+		    MYSQL_BASEDIR2=${MYSQL_BASEDIR%/}
+		    remote_cmd_nofail $XHOSTNAME "rm -f ${MYSQL_BASEDIR2}*"
+		    remote_cmd $XHOSTNAME "tar xvfz ${STAGING_DIR}/$filename -C `dirname $MYSQL_BASEDIR`"
+		    remote_cmd $XHOSTNAME "ln -s `dirname $MYSQL_BASEDIR`/`basename $filename .tar.gz`  $MYSQL_BASEDIR2"
+		    ;;
+		rpm)
+		    RPMLIST="$RPMLIST $STAGING_DIR/$filename"
+		    ;;
+		deb)
+		    DEBLIST="$DEBLIST $STAGING_DIR/$filename"
+	            ;;
+	    esac    
+	done
+	if [ -n "$RPMLIST" ]; then
+	    remote_cmd $XHOSTNAME "rpm -Uvh $RPMLIST"
+	fi
+	if [ -n "$DEBLIST" ]; then
+	    remote_cmd $XHOSTNAME "/usr/bin/dpkg -i $DEBLIST"
+	fi
+		echo "Installed $PKG_NAME on $XHOSTNAME"    
+    fi
 }
 
 function install_mongodb
@@ -928,7 +936,7 @@ function install_mongodb
     remote_cmd_nofail $XHOSTNAME "rm -rf /etc/init.d/mysql.server"
     
     remote_cmd_nofail $XHOSTNAME "mkdir -p $S9S_TMPDIR"
-    remote_cmd_nofail $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $STAGING_DIR"
+    remote_cmd_nofail $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
 
     if [ -n "$DATADIR" ]; then
 	if [ "$DATADIR" != "/" ]; then
@@ -1023,10 +1031,64 @@ function update_mysql_pkg_yum
     fi
     load_opts $CID
     CMON_DB='cmon'
-    echo "Do you want update yum packages on '$XHOSTNAME' (press y or Y to continue)?"
+    echo "Do you want update the database yum packages on '$XHOSTNAME' (press y or Y to continue)?"
     read x
     if [ "$x" == "y" ] || [ "$x" == "Y" ]; then	
 	remote_cmd $XHOSTNAME "yum update `rpm -qa | egrep -i  '(percona|mysql|galera|maria)'`"
+	echo "Updated packages on $XHOSTNAME"		    
+    fi
+    echo "Updated packages on $XHOSTNAME"		    
+    exit 0
+}
+
+
+function update_mysql_pkg_apt
+{   
+    args=`getopt p:s:P:h:i:N:n:f: $*`
+    set -- $args
+    for i
+    do
+        case "$i" in
+            -p)
+                CMON_PASSWORD="$2"; shift;
+                shift;;
+            -i)
+                CID="$2"; shift;
+                shift;;
+            -h)
+		XHOSTNAME="$2"; shift;
+                shift;;
+            --)
+                shift; break;;
+                esac
+    done
+
+
+    if [ -z "$XHOSTNAME" ]; then
+	echo 'Syntax:'
+	echo ' s9s_sw_update --update-mysql-apt -i <clusterid> -h <hostname>'
+	exit 1
+    fi
+    if [ -z "$CID" ]; then
+	echo 'Syntax:'
+	echo ' s9s_sw_update --update-mysql-apt -i <clusterid> -h <hostname>'
+	exit 1
+    fi
+    load_opts $CID
+    CMON_DB='cmon'
+    echo "Do you want update database apt packages on '$XHOSTNAME' (press y or Y to continue)?"
+    read x
+    if [ "$x" == "y" ] || [ "$x" == "Y" ]; then	
+	####
+	case $XVENDOR in
+	    percona)
+		remote_cmd $XHOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -y install percona-xtradb-cluster-galera percona-xtradb-cluster-client-5.5 percona-xtradb-cluster-server-5.5 percona-xtrabackup"
+		;;
+	    *)
+		echo "Not a supported vendor: $XVENDOR"
+		exit 1
+		;;
+	esac
 	echo "Updated packages on $XHOSTNAME"		    
     fi
     echo "Updated packages on $XHOSTNAME"		    
@@ -1054,10 +1116,13 @@ function load_opts
     XVENDOR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='VENDOR' AND cid=$CLUSTER_ID" 2>/dev/null`
     OS_USER_HOME=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='OS_USER_HOME' AND cid=$CLUSTER_ID" 2>/dev/null`
     NETWORKLESS=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='NETWORKLESS' AND cid=$CLUSTER_ID" 2>/dev/null`
+    RPM=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon_configuration where param='RPM' AND cid=$CLUSTER_ID" 2>/dev/null`
     DATADIR=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select value from cmon.cluster_config where variable='datadir' and cid=1 order by id asc limit 1" 2>/dev/null`
     MYCNF=`$MYSQL_BIN -N -B -A --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "select data  from cmon.cluster_configuration where cid=1 limit 1"`
 
-
+    if [ -z "$RPM" ]; then
+	RPM=1
+    fi
 
     
     SSH_OPTS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -oNumberOfPasswordPrompts=0 -oConnectTimeout=10"
@@ -1080,6 +1145,8 @@ function load_opts
         SSH_PORT="22"
     fi
 
+    S9S_TMPDIR=$STAGING_DIR
+    
     if [ "$S9S_TMPDIR" = "" ] || [ "$TMPDIR" = "NULL" ];  then
 	S9S_TMPDIR="/tmp/"
 	TMPDIR="/tmp/"
@@ -1107,11 +1174,17 @@ case $ARG in
     --install-mysql)
         install_mysql $*
 	;;
+    --install-mysql-pkg)
+        install_mysql_pkg $*
+	;;
     --install-mongodb)
         install_mongodb $*
 	;;
     --update-mysql-yum)
         update_mysql_pkg_yum $*
+	;;
+    --update-mysql-apt)
+        update_mysql_pkg_apt $*
 	;;
     --list)
 	list_pkgs
