updated scripts

diff --git a/ccadmin/s9s_sw_update b/ccadmin/s9s_sw_update
--- a/ccadmin/s9s_sw_update
+++ b/ccadmin/s9s_sw_update
@@ -4,6 +4,9 @@
 #
 # MODIFY THE BELOW TO SUIT YOU ENV:
 JOBID=0
+
+PERCONA_RELEASE_LINK='http://www.percona.com/redir/downloads/percona-release/redhat/0.0-1/percona-release-0.0-1.x86_64.rpm'
+
 function init
 {    
     FILES=`ls /etc/cmon.cnf 2>&1`
@@ -635,7 +638,7 @@ function install_mysql
 	percona)
 	        if [ "$OS" = "redhat" ]; then
 		#remote_cmd_nofail $XHOSTNAME "$HTTP_PROXY yum -y install perl-DBD-MySQL.x86_64"	
-		        remote_cmd $XHOSTNAME "$HTTP_PROXY rpm -Uhv --force http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
+		        remote_cmd $XHOSTNAME "$HTTP_PROXY rpm -Uhv --force $PERCONA_RELEASE_LINK"
                 MYSQL_VERSION2=`echo $MYSQL_VERSION | tr -d .`
 		        if [ "$GALERA_VERSION" = "3.x" ]; then            
                     GALERA_VERSION2=3
@@ -668,89 +671,89 @@ function install_mysql
 	        fi
 	        ;;
 	    internal_pkg | codership | percona_nonet | mariadb_tgz | percona_tgz)	    
-	    if [ -z "$PKG_NAME" ]; then
+	        if [ -z "$PKG_NAME" ]; then
 		## default to MYSQL_INITIAL_DEPLOY if not set
-		    PKG_NAME="MYSQL_INITIAL_DEPLOY"
-	    fi
-	    QUERY="SELECT packageid FROM ${CMON_DB}.cmon_sw_package WHERE name='$PKG_NAME' AND cid=$CLUSTER_ID"
-	    PID=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`	
-	    if [ -z "$PID" ]; then
-		    log_job_message "Invalid package name $PKG_NAME" 1
-		    log_job 'FAILED' 'job failed' 1
-		    write_email "s9s_sw_update failed" "Invalid package name $PKG_NAME. Check job messages."
-		    exit 1
-	    fi
-	    QUERY="SELECT group_concat(concat(path,',', filename) SEPARATOR ' ') FROM ${CMON_DB}.cmon_uploads WHERE packageid='$PID' AND cid=$CLUSTER_ID"
-	    FILELIST=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`	    
-	    if [ -z "$FILELIST" ]; then
-		    log_job_message "No files in package $PKG_NAME" 1
-		    log_job 'FAILED' 'job failed' 1
-		    write_email "s9s_sw_update failed" "No files in $PKG_NAME. Check job messages."
-		    exit 1	    
-	    fi
-	    
-	    if [ "$FILELIST" = "NULL" ]; then
-		    log_job_message "No files in package $PKG_NAME" 1
-		    log_job 'FAILED' 'job failed' 1
-		    write_email "s9s_sw_update failed" "No files in $PKG_NAME. Check job messages."
-		    exit 1	    
-	    fi
-	    
-	    
-	    remote_cmd $XHOSTNAME "mkdir -p $S9S_TMPDIR"
-	    remote_cmd $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
-	    if [ "$VENDOR" = "codership" ] && [ "$OS" = "debian" ]; then
-		    remote_cmd_nofail $XHOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install mysql-client"            
-		    remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
-		    remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
-		    remote_cmd $XHOSTNAME "apt-get -q -y update"
-		    remote_cmd $XHOSTNAME "LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' --force-yes -y -q install percona-xtrabackup percona-toolkit"
-	    fi
-	    if [ "$VENDOR" = "codership" ] && [ "$OS" = "redhat" ]; then
-            remote_cmd $XHOSTNAME "$HTTP_PROXY rpm -Uhv --force http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
-		    remote_cmd $XHOSTNAME "$HTTP_PROXY yum -y install percona-xtrabackup"
-        fi
-	    for f in $FILELIST 
-	    do
-		path=`echo $f | awk -F, '{print $1;}'`
-		filename=`echo $f | awk -F, '{print $2;}'`	 
-		if [ -f $path/$filename ]; then
-		    remote_copy $path/$filename $XHOSTNAME $S9S_TMPDIR	    	    
-		else
-		    log_job_message "File did not exist: $path/$filename" 1
-		    log_job 'FAILED' 'job failed' 1
-		    write_email "s9s_sw_update failed" "File did not exist: $path/$filename. Check job messages."
-		    exit 1	    
-		fi
-	    done
-	    RPMLIST=""
-	    for f in $FILELIST 
-	    do
-		filename=`echo $f | awk -F, '{print $2;}'`	    
-		ext=${filename##*.}
-		case $ext in
-		    gz)
-			MYSQL_BASEDIR2=${MYSQL_BASEDIR%/}
-			remote_cmd_nofail $XHOSTNAME "rm -f ${MYSQL_BASEDIR2}*"
-			remote_cmd $XHOSTNAME "tar xvfz ${S9S_TMPDIR}/$filename -C `dirname $MYSQL_BASEDIR`"
-			remote_cmd $XHOSTNAME "ln -s `dirname $MYSQL_BASEDIR`/`basename $filename .tar.gz`  $MYSQL_BASEDIR2"
-			;;
-		    rpm)
-			RPMLIST="$RPMLIST $S9S_TMPDIR/$filename"
-			;;
-		    deb)
-			DEBLIST="$DEBLIST $S9S_TMPDIR/$filename"
-			;;
-		esac	    
-	    done
-	    if [ -n "$RPMLIST" ]; then
-		remote_cmd $XHOSTNAME "rpm -Uvh $RPMLIST"
-	    fi
-	    if [ -n "$DEBLIST" ]; then
-		remote_cmd $XHOSTNAME "LC_ALL=C DEBIAN_FRONTEND=noninteractive /usr/bin/dpkg -i $DEBLIST"
-	    fi
-	    remote_cmd $XHOSTNAME "test -f ${MYSQL_BASEDIR}/bin/mysql"	    
-	    ;;
+		        PKG_NAME="MYSQL_INITIAL_DEPLOY"
+	        fi
+	        QUERY="SELECT packageid FROM ${CMON_DB}.cmon_sw_package WHERE name='$PKG_NAME' AND cid=$CLUSTER_ID"
+	        PID=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`	
+	        if [ -z "$PID" ]; then
+		        log_job_message "Invalid package name $PKG_NAME" 1
+		        log_job 'FAILED' 'job failed' 1
+		        write_email "s9s_sw_update failed" "Invalid package name $PKG_NAME. Check job messages."
+		        exit 1
+	        fi
+	        QUERY="SELECT group_concat(concat(path,',', filename) SEPARATOR ' ') FROM ${CMON_DB}.cmon_uploads WHERE packageid='$PID' AND cid=$CLUSTER_ID"
+	        FILELIST=`$MYSQL_BIN  -B -N  --user=$CMON_USER --password=$CMON_PASSWORD --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT  -e "$QUERY"`	    
+	        if [ -z "$FILELIST" ]; then
+		        log_job_message "No files in package $PKG_NAME" 1
+		        log_job 'FAILED' 'job failed' 1
+		        write_email "s9s_sw_update failed" "No files in $PKG_NAME. Check job messages."
+		        exit 1	    
+	        fi
+	        
+	        if [ "$FILELIST" = "NULL" ]; then
+		        log_job_message "No files in package $PKG_NAME" 1
+		        log_job 'FAILED' 'job failed' 1
+		        write_email "s9s_sw_update failed" "No files in $PKG_NAME. Check job messages."
+		        exit 1	    
+	        fi
+	        
+	        
+	        remote_cmd $XHOSTNAME "mkdir -p $S9S_TMPDIR"
+	        remote_cmd $XHOSTNAME "chown  -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
+	        if [ "$VENDOR" = "codership" ] && [ "$OS" = "debian" ]; then
+		        remote_cmd_nofail $XHOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install mysql-client"            
+		        remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
+		        remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
+		        remote_cmd $XHOSTNAME "apt-get -q -y update"
+		        remote_cmd $XHOSTNAME "LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' --force-yes -y -q install percona-xtrabackup-21 percona-toolkit"
+	        fi
+	        if [ "$VENDOR" = "codership" ] && [ "$OS" = "redhat" ]; then
+                remote_cmd $XHOSTNAME "$HTTP_PROXY rpm -Uhv --force $PERCONA_RELEASE_LINK"
+		        remote_cmd $XHOSTNAME "$HTTP_PROXY yum -y install percona-xtrabackup-21"
+            fi
+	        for f in $FILELIST 
+	        do
+		        path=`echo $f | awk -F, '{print $1;}'`
+		        filename=`echo $f | awk -F, '{print $2;}'`	 
+		        if [ -f $path/$filename ]; then
+		            remote_copy $path/$filename $XHOSTNAME $S9S_TMPDIR	    	    
+		        else
+		            log_job_message "File did not exist: $path/$filename" 1
+		            log_job 'FAILED' 'job failed' 1
+		            write_email "s9s_sw_update failed" "File did not exist: $path/$filename. Check job messages."
+		            exit 1	    
+		        fi
+	        done
+	        RPMLIST=""
+	        for f in $FILELIST 
+	        do
+		        filename=`echo $f | awk -F, '{print $2;}'`	    
+		        ext=${filename##*.}
+		        case $ext in
+		            gz)
+			            MYSQL_BASEDIR2=${MYSQL_BASEDIR%/}
+			            remote_cmd_nofail $XHOSTNAME "rm -f ${MYSQL_BASEDIR2}*"
+			            remote_cmd $XHOSTNAME "tar xvfz ${S9S_TMPDIR}/$filename -C `dirname $MYSQL_BASEDIR`"
+			            remote_cmd $XHOSTNAME "ln -s `dirname $MYSQL_BASEDIR`/`basename $filename .tar.gz`  $MYSQL_BASEDIR2"
+			            ;;
+		            rpm)
+			            RPMLIST="$RPMLIST $S9S_TMPDIR/$filename"
+			            ;;
+		            deb)
+			            DEBLIST="$DEBLIST $S9S_TMPDIR/$filename"
+			            ;;
+		        esac	    
+	        done
+	        if [ -n "$RPMLIST" ]; then
+		        remote_cmd $XHOSTNAME "rpm -Uvh $RPMLIST"
+	        fi
+	        if [ -n "$DEBLIST" ]; then
+		        remote_cmd $XHOSTNAME "LC_ALL=C DEBIAN_FRONTEND=noninteractive /usr/bin/dpkg -i $DEBLIST"
+	        fi
+	        remote_cmd $XHOSTNAME "test -f ${MYSQL_BASEDIR}/bin/mysql"	    
+	        ;;
 	    mariadb)
 	        if [ "$OS" = "redhat" ]; then                
                 if [ "$MYSQL_VERSION" = "5.5" ]; then
@@ -824,7 +827,7 @@ EOF
 		        remote_copy ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL} $XHOSTNAME ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL}.tmp
 		        remote_cmd $XHOSTNAME "mv -f ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL}.tmp /etc/yum.repos.d/MariaDB.repo"
                 remote_cmd $XHOSTNAME "$HTTP_PROXY yum -y install MariaDB-Galera-server.x86_64 MariaDB-client.x86_64 galera"
-		        remote_cmd $XHOSTNAME "$HTTP_PROXY rpm -Uhv --force http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
+		        remote_cmd $XHOSTNAME "$HTTP_PROXY rpm -Uhv --force $PERCONA_RELEASE_LINK"
 		        remote_cmd $XHOSTNAME "$HTTP_PROXY yum -y install percona-xtrabackup"
 	        else
 		        remote_cmd_nofail $XHOSTNAME "killall -9 mysqld mysqld_safe mysql mysql_chk ndb_mgmd ndbmtd ndbd cmon"
diff --git a/cluster/s9s_galera b/cluster/s9s_galera
--- a/cluster/s9s_galera
+++ b/cluster/s9s_galera
@@ -6,7 +6,7 @@ LOCKFILE="/tmp/s9s_galera.lock"
 
 [ ! -f /etc/mysql/my.cnf ] && MYSQL_CONFIG=/etc/my.cnf || MYSQL_CONFIG=/etc/mysql/my.cnf
 MYSQL_OPTIONS="--defaults-file=$MYSQL_CONFIG --defaults-group-suffix=_cmon"
-
+PERCONA_RELEASE_LINK='http://www.percona.com/redir/downloads/percona-release/redhat/0.0-1/percona-release-0.0-1.x86_64.rpm'
 
 jobid=0
 function init
@@ -927,11 +927,11 @@ function install_garbd
     CLUSTER_NAME=`$MYSQL_BIN $MYSQL_OPTS --host=$ANY_HOSTNAME --port=$MONITORED_MYSQL_PORT -A -Bse "$QUERY"`
     if [ $? -ne 0 ]; then
         log_job_message "Failed to get wsrep_cluster_name" 1
-	log_job 'FAILED' 'install garbd failed' 1
+	    log_job 'FAILED' 'install garbd failed' 1
         exit 1
     fi
     CLUSTER_NAME=`echo $CLUSTER_NAME | awk   '{print $2;}'`
-
+    
     echo "Hostname: $XHOSTNAME"
     echo "Donor: $DONOR_HOSTNAME"  
     echo "Galera port: $GALERA_PORT"
@@ -941,144 +941,138 @@ function install_garbd
     remote_cmd_nofail $XHOSTNAME "mkdir -p $S9S_TMPDIR"
     remote_cmd $XHOSTNAME "chown $SSH_USER:$SSH_USER $S9S_TMPDIR"
     case $VENDOR in
-	percona)
-	    if [ "$OS" = "redhat" ]; then
-		remote_cmd $XHOSTNAME "rpm -Uhv --force http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm"
-		if [ "$GALERA_VERSION" = "3.x" ]; then
-		    remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-garbd-3"
-		fi
-		if [ "$GALERA_VERSION" = "2.x" ]; then
-		    remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-garbd-2"
-		fi
-	    else
-		remote_cmd $XHOSTNAME "apt-get update"
-		remote_cmd_nofail $XHOSTNAME "apt-get -y install  libssl0.9.8  wget rsync psmisc"
-		remote_cmd_nofail $XHOSTNAME "sed -i.bak '/repo.percona.com/d'  /etc/apt/sources.list"
-		$HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona
-		if [ $? -ne 0 ]; then
-		    log_job_message "Failed: $HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona" 1
-		    log_job 'FAILED' 'install garbd failed' 1
-		    exit 1
-		fi
-		remote_cmd $XHOSTNAME "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
-		remote_copy $S9S_TMPDIR/RPM-GPG-KEY-percona ${XHOSTNAME} ${S9S_TMPDIR}/RPM-GPG-KEY-percona
-		remote_cmd $XHOSTNAME "gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'gpg -a --export CD2EFD2A | apt-key add -'"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
-		remote_cmd $XHOSTNAME "apt-get -q -y update"
-
-		if [ "$GALERA_VERSION" = "3.x" ]; then
-		    remote_cmd $XHOSTNAME "$HTTP_PROXY LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install percona-xtradb-cluster-garbd-3.x"
-		fi
-		if [ "$GALERA_VERSION" = "2.x" ]; then
-		    remote_cmd $XHOSTNAME "$HTTP_PROXY LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install  percona-xtradb-cluster-garbd-2.x"
-		fi
-
-		remote_cmd $XHOSTNAME "sync"
-	    fi
-	    ;;
-	codership)	    
-
-	    if [ -z "$XFILENAME" ]; then
-		
-		if [ "$OS" = "redhat" ]; then
-		    QUERY="select concat(path, filename) from cmon_uploads a , cmon_sw_package b where a.packageid=b.packageid and a.cid=b.cid and a.cid=${CLUSTER_ID} and b.selected=1 and (filename like 'galera%.rpm')"
-		else
-		    QUERY="select concat(path, filename) from cmon_uploads a , cmon_sw_package b where a.packageid=b.packageid and a.cid=b.cid and a.cid=${CLUSTER_ID} and b.selected=1 and (filename like 'galera%.deb')"
-		fi
-		
-		XFILENAME=`$MYSQL_BIN $MYSQL_OPTS -NAB --host=$CMON_DB_HOST --port=$CMON_DB_PORT --database=$CMON_DB_DB  -e "$QUERY"`
-		if [ ! -f $XFILENAME ]; then
-		    log_job_message "Could not find $XFILENAME - You must have a selected deployment package, or specify with -f <package name>" 1
-		    log_job 'FAILED' 'install garbd failed' 1
-		    exit 1
-		fi
-	    fi
-	    
-	    if [ -z "$XFILENAME" ]; then
-		log_job_message "s9s_galera --install-garbd -f <galera package missing>" 1
-		log_job 'FAILED' 'install garbd failed' 1
-		exit 1
-	    fi
-	    if [ ! -f "$XFILENAME" ]; then
-		log_job_message "s9s_galera --install-garbd -f <galera package missing>" 1
-		log_job 'FAILED' 'install garbd failed' 1
-		exit 1
-	    fi	    
-	    remote_cmd $XHOSTNAME "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
-	    remote_copy $XFILENAME $XHOSTNAME $TMPDIR	    
-	    XFILE=`basename $XFILENAME`
-	    if [ "$OS" = "redhat" ]; then
-		remote_cmd $XHOSTNAME "rpm -Uhv --force $TMPDIR/$XFILE"
-	    else
-		remote_cmd $XHOSTNAME "dpkg -P galera"
-		remote_cmd $XHOSTNAME "apt-get install -y libssl0.9.8"
-		remote_cmd $XHOSTNAME "dpkg -i $TMPDIR/$XFILE"
-	    fi
-	    ;;
-	mariadb)
-	    if [ "$OS" = "redhat" ]; then
-		cat << 'EOF' > $S9S_TMPDIR/MariaDB.centos5
+        percona)
+            if [ "$OS" = "redhat" ]; then
+                remote_cmd $XHOSTNAME "rpm -Uhv --force $PERCONA_RELEASE_LINK"
+                if [ "$GALERA_VERSION" = "3.x" ]; then
+                    remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-garbd-3"
+                fi
+                if [ "$GALERA_VERSION" = "2.x" ]; then
+                    remote_cmd $XHOSTNAME "yum -y install Percona-XtraDB-Cluster-garbd-2"
+                fi
+            else
+		        remote_cmd $XHOSTNAME "apt-get update"
+		        remote_cmd_nofail $XHOSTNAME "apt-get -y install  libssl0.9.8  wget rsync psmisc"
+		        remote_cmd_nofail $XHOSTNAME "sed -i.bak '/repo.percona.com/d'  /etc/apt/sources.list"
+		        $HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona
+		        if [ $? -ne 0 ]; then
+		            log_job_message "Failed: $HTTP_PROXY wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona" 1
+		            log_job 'FAILED' 'install garbd failed' 1
+		            exit 1
+		        fi
+                remote_cmd $XHOSTNAME "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
+                remote_copy $S9S_TMPDIR/RPM-GPG-KEY-percona ${XHOSTNAME} ${S9S_TMPDIR}/RPM-GPG-KEY-percona
+                remote_cmd $XHOSTNAME "gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
+                remote_cmd $XHOSTNAME "/bin/sh -c 'gpg -a --export CD2EFD2A | apt-key add -'"
+                remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
+                remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://repo.percona.com/apt `lsb_release -c -s` main\" >> /etc/apt/sources.list'"
+                remote_cmd $XHOSTNAME "apt-get -q -y update"
+                if [ "$GALERA_VERSION" = "3.x" ]; then
+                    remote_cmd $XHOSTNAME "$HTTP_PROXY LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install percona-xtradb-cluster-garbd-3.x"
+                fi
+                if [ "$GALERA_VERSION" = "2.x" ]; then
+                    remote_cmd $XHOSTNAME "$HTTP_PROXY LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' -y -q install  percona-xtradb-cluster-garbd-2.x"
+                fi                
+                remote_cmd $XHOSTNAME "sync"
+            fi
+            ;;
+        codership)	                
+            if [ -z "$XFILENAME" ]; then		        
+                if [ "$OS" = "redhat" ]; then
+                    QUERY="select concat(path, filename) from cmon_uploads a , cmon_sw_package b where a.packageid=b.packageid and a.cid=b.cid and a.cid=${CLUSTER_ID} and b.selected=1 and (filename like 'galera%.rpm')"
+                else
+                    QUERY="select concat(path, filename) from cmon_uploads a , cmon_sw_package b where a.packageid=b.packageid and a.cid=b.cid and a.cid=${CLUSTER_ID} and b.selected=1 and (filename like 'galera%.deb')"
+                fi
+                XFILENAME=`$MYSQL_BIN $MYSQL_OPTS -NAB --host=$CMON_DB_HOST --port=$CMON_DB_PORT --database=$CMON_DB_DB  -e "$QUERY"`
+                if [ ! -f $XFILENAME ]; then
+                    log_job_message "Could not find $XFILENAME - You must have a selected deployment package, or specify with -f <package name>" 1
+                    log_job 'FAILED' 'install garbd failed' 1
+                    exit 1
+                fi
+            fi	        
+            if [ -z "$XFILENAME" ]; then
+                log_job_message "s9s_galera --install-garbd -f <galera package missing>" 1
+                log_job 'FAILED' 'install garbd failed' 1
+                exit 1
+            fi
+            if [ ! -f "$XFILENAME" ]; then
+                log_job_message "s9s_galera --install-garbd -f <galera package missing>" 1
+                log_job 'FAILED' 'install garbd failed' 1
+                exit 1
+            fi	    
+            remote_cmd $XHOSTNAME "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
+            remote_copy $XFILENAME $XHOSTNAME $TMPDIR	    
+            XFILE=`basename $XFILENAME`
+            if [ "$OS" = "redhat" ]; then
+                remote_cmd $XHOSTNAME "rpm -Uhv --force $TMPDIR/$XFILE"
+            else
+                remote_cmd $XHOSTNAME "dpkg -P galera"
+                remote_cmd $XHOSTNAME "apt-get install -y libssl0.9.8"
+                remote_cmd $XHOSTNAME "dpkg -i $TMPDIR/$XFILE"
+            fi
+            ;;
+        mariadb)
+        if [ "$OS" = "redhat" ]; then
+            cat << 'EOF' > $S9S_TMPDIR/MariaDB.centos5
 [mariadb]
 name = MariaDB
 baseurl = http://yum.mariadb.org/5.5/centos5-amd64
 gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
 gpgcheck=1                 
 EOF
-		cat << 'EOF' > $S9S_TMPDIR/MariaDB.centos6
+            cat << 'EOF' > $S9S_TMPDIR/MariaDB.centos6
 [mariadb]
 name = MariaDB
 baseurl = http://yum.mariadb.org/5.5/centos6-amd64
 gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
 gpgcheck=1                 
 EOF
-		cat << 'EOF' > $S9S_TMPDIR/MariaDB.rhel5
+            cat << 'EOF' > $S9S_TMPDIR/MariaDB.rhel5
 [mariadb]
 name = MariaDB
 baseurl = http://yum.mariadb.org/5.5/rhel5-amd64
 gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
 gpgcheck=1                 
 EOF
-		cat << 'EOF' > $S9S_TMPDIR/MariaDB.rhel6
+            cat << 'EOF' > $S9S_TMPDIR/MariaDB.rhel6
 [mariadb]
 name = MariaDB
 baseurl = http://yum.mariadb.org/5.5/rhel6-amd64
 gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
 gpgcheck=1                 
 EOF
-		if [ -f /etc/system-release ]; then
-		    RHEL=6
-		    OS2='rhel'		    
-		else
-		    RHEL=$(cat /etc/redhat-release | egrep "[0-9]" -o | head -1)
-		    OS2=$(awk '{print $1}' /etc/redhat-release | tr '[:upper:]' '[:lower:]')
-		fi
-		remote_cmd $XHOSTNAME "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
-		remote_copy ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL} $XHOSTNAME ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL}.tmp
-		remote_cmd $XHOSTNAME "mv -f ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL}.tmp /etc/yum.repos.d/MariaDB.repo"
-                remote_cmd $XHOSTNAME "yum -y install galera"
-	    else
-		wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona	
-		remote_copy ${S9S_TMPDIR}/RPM-GPG-KEY-percona ${XHOSTNAME} ${S9S_TMPDIR}/RPM-GPG-KEY-percona
-		remote_cmd $XHOSTNAME "gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'gpg -a --export CD2EFD2A | apt-key add -'"
-		remote_cmd $XHOSTNAME "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" > /etc/apt/sources.list.d/MariaDB.list'"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" >> /etc/apt/sources.list.d/MariaDB.list'"
-		remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"Package: *\nPin: origin osuosl.org\nPin-Priority: 1000\n\nPackage: *\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\n\nPackage: libmysqlclient18\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\" > /etc/apt/preferences.d/00MariaDB.pref'"
-		remote_cmd $XHOSTNAME "apt-get -q -y update"
-		remote_cmd $XHOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' --force-yes -y -q install  galera "
-	    fi
-	    ;;
-	*)
-	    echo "Not a supported vendor"
-	    exit 1;	           	     
+            if [ -f /etc/system-release ]; then
+                RHEL=6
+                OS2='rhel'		    
+            else
+                RHEL=$(cat /etc/redhat-release | egrep "[0-9]" -o | head -1)
+                OS2=$(awk '{print $1}' /etc/redhat-release | tr '[:upper:]' '[:lower:]')
+            fi
+            remote_cmd $XHOSTNAME "chown -R $SSH_USER:$SSH_USER $S9S_TMPDIR"
+            remote_copy ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL} $XHOSTNAME ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL}.tmp
+            remote_cmd $XHOSTNAME "mv -f ${S9S_TMPDIR}/MariaDB.${OS2}${RHEL}.tmp /etc/yum.repos.d/MariaDB.repo"
+            remote_cmd $XHOSTNAME "yum -y install galera"
+        else
+            wget --no-check-certificate --tries=5  -O ${S9S_TMPDIR}/RPM-GPG-KEY-percona http://www.percona.com/redir/downloads/RPM-GPG-KEY-percona	
+            remote_copy ${S9S_TMPDIR}/RPM-GPG-KEY-percona ${XHOSTNAME} ${S9S_TMPDIR}/RPM-GPG-KEY-percona
+            remote_cmd $XHOSTNAME "gpg --import ${S9S_TMPDIR}/RPM-GPG-KEY-percona"
+            remote_cmd $XHOSTNAME "/bin/sh -c 'gpg -a --export CD2EFD2A | apt-key add -'"
+            remote_cmd $XHOSTNAME "apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db"
+            remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" > /etc/apt/sources.list.d/MariaDB.list'"
+            remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"deb-src http://ftp.osuosl.org/pub/mariadb/repo/5.5/`lsb_release -i -s | tr '[A-Z]' '[a-z]'` `lsb_release -c -s` main\" >> /etc/apt/sources.list.d/MariaDB.list'"
+            remote_cmd $XHOSTNAME "/bin/sh -c 'echo \"Package: *\nPin: origin osuosl.org\nPin-Priority: 1000\n\nPackage: *\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\n\nPackage: libmysqlclient18\nPin: origin ftp.osuosl.org\nPin-Priority: 1000\" > /etc/apt/preferences.d/00MariaDB.pref'"
+            remote_cmd $XHOSTNAME "apt-get -q -y update"
+            remote_cmd $XHOSTNAME "LC_ALL=en_US.utf8 DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::='--force-confnew' --force-yes -y -q install  galera "
+        fi
+        ;;
+        *)
+            echo "Not a supported vendor"
+            exit 1;	           	     
     esac
     QUERY="INSERT IGNORE INTO cmon_configuration(cid,param,value,report_ts) VALUES($CLUSTER_ID,'VENDOR', '$VENDOR', now())"
     `$MYSQL_BIN $MYSQL_OPTS -NAB --database=$CMON_DB_DB --host=$CMON_DB_HOST --port=$CMON_DB_PORT -e "$QUERY"`
     if [  $? -ne 0 ]; then
-	log_job_message  "Query failed. $QUERY"  1	
+        log_job_message  "Query failed. $QUERY"  1	
     fi
     echo "Starting garbd"
     start_garbd $XHOSTNAME $DONOR_HOSTNAME $GALERA_PORT $CLUSTER_NAME
@@ -1086,11 +1080,11 @@ EOF
     QUERY="REPLACE INTO ext_proc (cid, hostname,bin, opts,cmd, proc_name, port, status) VALUES($CLUSTER_ID, '$XHOSTNAME','/usr/bin/garbd', '-a gcomm://${DONOR_HOSTNAME} -g -o gmcast.listen_addr=tcp://0.0.0.0:${GALERA_PORT}  -d', '/usr/bin/garbd  -a gcomm://${DONOR_HOSTNAME} -g $CLUSTER_NAME -o gmcast.listen_addr=tcp://0.0.0.0:${GALERA_PORT} -d','garbd', $GALERA_PORT , 0)"
     $MYSQL_BIN $MYSQL_OPTS --host=$CMON_DB_HOST --port=$CMON_DB_PORT --database=$CMON_DB_DB -N -Bse "$QUERY"  2>&1 >${S9S_TMPDIR}/err.log    
     if [  $? -ne 0 ]; then
-	log_job_message "Query failed: $QUERY" 1
-	log_job_message "Garbd started but ClusterControl will not be able to manage the garbd" 1
-	log_job 'FAILED' 'install garbd failed' 1
-	cat ${S9S_TMPDIR}/err.log
-	exit 1
+        log_job_message "Query failed: $QUERY" 1
+        log_job_message "Garbd started but ClusterControl will not be able to manage the garbd" 1
+        log_job 'FAILED' 'install garbd failed' 1
+        cat ${S9S_TMPDIR}/err.log
+        exit 1
     fi
     log_job 'FINISHED' 'install garbd' 0
     log_job_message "Successfully installed garbd on $XHOSTNAME" 0
